import { getCloudflareContext } from '@opennextjs/cloudflare'
import type { NextRequest,NextResponse } from 'next/server'

export const CONTRIBUTOR_COOKIE='sx_contributor_session'
const SESSION_DAYS=30,PBKDF2_ITERATIONS=120000
function runtime(){const {env}=getCloudflareContext(),db=(env as any).DB;if(!db)throw new Error('Cloudflare D1 binding DB is unavailable');return{db,env:env as any}}
function bytesToBase64(bytes:Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
function base64ToBytes(value:string){const s=atob(value),out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return bytesToBase64(new Uint8Array(digest))}
export async function hashPassword(password:string,salt?:string){const saltBytes=salt?base64ToBytes(salt):crypto.getRandomValues(new Uint8Array(16)),key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']),bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:saltBytes,iterations:PBKDF2_ITERATIONS},key,256);return{hash:bytesToBase64(new Uint8Array(bits)),salt:bytesToBase64(saltBytes)}}
export async function verifyPassword(password:string,salt:string,expected:string){const {hash}=await hashPassword(password,salt);return hash===expected}
export function normalizeEmail(v:unknown){const email=String(v||'').trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)?email:''}
export function randomCode(){return String(crypto.getRandomValues(new Uint32Array(1))[0]%1000000).padStart(6,'0')}
export async function createVerificationCode(accountId:string){const {db}=runtime(),code=randomCode(),id=crypto.randomUUID(),expires=new Date(Date.now()+15*60_000).toISOString();await db.prepare('DELETE FROM contributor_auth_codes WHERE account_id=? AND used_at IS NULL').bind(accountId).run();await db.prepare('INSERT INTO contributor_auth_codes (id,account_id,code_hash,expires_at,created_at) VALUES (?,?,?,?,?)').bind(id,accountId,await sha256(code),expires,new Date().toISOString()).run();return code}
export async function consumeVerificationCode(accountId:string,code:string){const {db}=runtime(),row:any=await db.prepare('SELECT id,code_hash,expires_at FROM contributor_auth_codes WHERE account_id=? AND used_at IS NULL ORDER BY created_at DESC LIMIT 1').bind(accountId).first();if(!row||row.expires_at<new Date().toISOString()||row.code_hash!==await sha256(code))return false;await db.prepare('UPDATE contributor_auth_codes SET used_at=? WHERE id=?').bind(new Date().toISOString(),row.id).run();await db.prepare('UPDATE contributor_auth_accounts SET verified_at=COALESCE(verified_at,?),updated_at=? WHERE id=?').bind(new Date().toISOString(),new Date().toISOString(),accountId).run();return true}
export async function sendVerificationEmail(email:string,code:string){const {env}=runtime(),key=String(env.RESEND_API_KEY||process.env.RESEND_API_KEY||''),from=String(env.FAN_ALERTS_FROM||process.env.FAN_ALERTS_FROM||'Section X Scoreboard <alerts@updates.sectionxscoreboard.com>');if(!key)throw new Error('Contributor verification email is not configured yet.');const res=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[email],subject:'Your Section X Scoreboard verification code',text:`Your Section X Scoreboard contributor verification code is ${code}. It expires in 15 minutes.`})});if(!res.ok)throw new Error('Could not send verification email.')}
export async function createSession(accountId:string,response:NextResponse){const {db}=runtime(),token=crypto.randomUUID()+crypto.randomUUID(),hash=await sha256(token),expires=new Date(Date.now()+SESSION_DAYS*86400_000);await db.prepare('DELETE FROM contributor_auth_sessions WHERE expires_at<?').bind(new Date().toISOString()).run();await db.prepare('INSERT INTO contributor_auth_sessions (token_hash,account_id,expires_at,created_at,last_seen_at) VALUES (?,?,?,?,?)').bind(hash,accountId,expires.toISOString(),new Date().toISOString(),new Date().toISOString()).run();response.cookies.set(CONTRIBUTOR_COOKIE,token,{httpOnly:true,secure:true,sameSite:'lax',path:'/',expires});return response}
export async function clearSession(req:NextRequest,response:NextResponse){const token=req.cookies.get(CONTRIBUTOR_COOKIE)?.value;if(token){const {db}=runtime();await db.prepare('DELETE FROM contributor_auth_sessions WHERE token_hash=?').bind(await sha256(token)).run().catch(()=>null)}response.cookies.set(CONTRIBUTOR_COOKIE,'',{httpOnly:true,secure:true,sameSite:'lax',path:'/',expires:new Date(0)});return response}
export async function contributorAccountFromRequest(req:NextRequest){const token=req.cookies.get(CONTRIBUTOR_COOKIE)?.value||req.headers.get('authorization')?.replace(/^Bearer\s+/i,'').trim();if(!token)return null;const {db}=runtime(),row:any=await db.prepare(`SELECT a.id,a.email,a.display_name,a.verified_at,s.expires_at FROM contributor_auth_sessions s JOIN contributor_auth_accounts a ON a.id=s.account_id WHERE s.token_hash=? LIMIT 1`).bind(await sha256(token)).first();if(!row||row.expires_at<new Date().toISOString())return null;await db.prepare('UPDATE contributor_auth_sessions SET last_seen_at=? WHERE token_hash=?').bind(new Date().toISOString(),await sha256(token)).run().catch(()=>null);return{id:row.id,email:row.email,display_name:row.display_name,verified_at:row.verified_at}}
export async function findAccountByEmail(email:string){const {db}=runtime();return await db.prepare('SELECT * FROM contributor_auth_accounts WHERE email=? LIMIT 1').bind(email).first() as any}
export function contributorDb(){return runtime().db}
