import { NextRequest,NextResponse } from 'next/server'
import { arbiterApi,ArbiterApiError } from '@/lib/arbiter/client'
import { runScheduleAudit } from '@/lib/arbiter/schedule-intelligence'
import { getCloudflareContext } from '@opennextjs/cloudflare'

export const dynamic='force-dynamic'
export const maxDuration=300
const CONFIRMATION='APPLY_ARBITER_SCHEDULE_SYNC',STALE_RUN_MINUTES=20
const clean=(v:unknown)=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const meaningfulLocation=(v:unknown)=>{const c=clean(v);return Boolean(c)&&!['tba','not listed','z','unknown'].includes(c)}
const sourceStatus=(v:unknown)=>['canceled','cancelled','deleted'].includes(clean(v))?'Canceled':['postponed','ppd'].includes(clean(v))?'Postponed':'Scheduled'
const contestType=(v:unknown)=>clean(v)==='scrimmage'?'Scrimmage':'Game'
function deletedIds(payload:unknown){const values=Array.isArray(payload)?payload:payload==null?[]:[payload],ids:number[]=[];for(const item of values as any[]){const id=Number(item?.uniqueGameId??item?.gameId??item?.id??item);if(Number.isFinite(id))ids.push(id)}return[...new Set(ids)]}
function getDb(){const {env}=getCloudflareContext(),db=(env as any).DB;if(!db)throw new Error('Cloudflare D1 binding DB is unavailable');return db}

export async function POST(req:NextRequest){
 const db=getDb();let runId:string|null=null
 try{
  const body=await req.json().catch(()=>({}))
  if(body?.confirm!==CONFIRMATION)return NextResponse.json({ok:false,error:'Explicit confirmation required.',requiredConfirmation:CONFIRMATION},{status:400})
  const audit=await runScheduleAudit({start:body.start,end:body.end,seasonId:body.seasonId,seasonType:body.seasonType,year:body.year==null?null:Number(body.year)})
  if(!audit.comparison.writerReady)return NextResponse.json({ok:false,error:'Writer halted because orphaned stable-identity links exist.',comparison:audit.comparison},{status:409})

  const staleCutoff=new Date(Date.now()-STALE_RUN_MINUTES*60_000).toISOString(),running:any=await db.prepare("SELECT id,created_at FROM arbiter_sync_runs WHERE season_id=? AND status='running' ORDER BY created_at DESC LIMIT 1").bind(audit.season.id).first()
  if(running?.id&&String(running.created_at||'')>=staleCutoff)return NextResponse.json({ok:false,error:'A controlled sync is already running for this season.',runId:running.id},{status:409})
  if(running?.id)await db.prepare("UPDATE arbiter_sync_runs SET status='stale',finished_at=?,summary=? WHERE id=?").bind(new Date().toISOString(),JSON.stringify({reason:'Previous run exceeded stale-run window.'}),running.id).run()

  runId=crypto.randomUUID();const now=new Date().toISOString()
  await db.prepare('INSERT INTO arbiter_sync_runs (id,season_id,mode,window_start,window_end,status,summary,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(runId,audit.season.id,'controlled',audit.window.start,audit.window.end,'running',JSON.stringify({planned:audit.comparison.counts,eligible:audit.comparison.eligible,quarantined:audit.comparison.quarantined,pendingChanges:audit.comparison.pendingChanges,progress:{processed:0,total:audit.rows.length}}),now).run()

  const totals={linked:0,updated:0,created:0,externalCreated:0,quarantined:0,ignoredOtherSeason:0,deletedMarked:0,failed:0,verifiedStable:0};let processed=0;const responseLogs:any[]=[]
  const currentSummary=()=>({...totals,planned:audit.comparison.counts,eligible:audit.comparison.eligible,quarantinedPlanned:audit.comparison.quarantined,pendingChanges:audit.comparison.pendingChanges,progress:{processed,total:audit.rows.length}})
  async function progress(force=false){if(force||processed%50===0)await db.prepare('UPDATE arbiter_sync_runs SET summary=? WHERE id=?').bind(JSON.stringify(currentSummary()),runId).run()}
  async function log(row:any,action:string,outcome:string,gameId:string|null,details:any={}){responseLogs.push({arbiterGameId:row?.uniqueGameId??null,action,outcome,gameId,...details});await db.prepare('INSERT INTO arbiter_sync_actions (id,run_id,arbiter_game_id,game_id,action,outcome,details,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),runId,row?.uniqueGameId??null,gameId,action,outcome,JSON.stringify(details),new Date().toISOString()).run()}
  async function ensureExternal(side:any){if(side.kind!=='external')return side.id||null;if(side.id)return side.id;if(!side.create?.name)return null;const desiredSlug=side.create.slug,existing:any=await db.prepare('SELECT id FROM external_opponents WHERE slug=? OR lower(name)=lower(?) LIMIT 1').bind(desiredSlug,side.create.name).first();if(existing?.id)return existing.id;const id=crypto.randomUUID();await db.prepare("INSERT INTO external_opponents (id,name,slug,is_section_x,created_at) VALUES (?,?,?,0,datetime('now'))").bind(id,side.create.name,desiredSlug).run();totals.externalCreated++;return id}
  async function link(row:any,gameId:string){await db.prepare(`INSERT INTO arbiter_game_links (arbiter_game_id,game_id,last_modified_at,last_seen_at,source_status,source_payload,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(arbiter_game_id) DO UPDATE SET game_id=excluded.game_id,last_modified_at=excluded.last_modified_at,last_seen_at=excluded.last_seen_at,source_status=excluded.source_status,source_payload=excluded.source_payload,updated_at=excluded.updated_at`).bind(row.uniqueGameId,gameId,row.lastModifiedDate||null,new Date().toISOString(),row.status||null,JSON.stringify(row.sourcePayload||null),new Date().toISOString()).run()}
  async function updateExisting(row:any,gameId:string){const current=row.existing||{},patch:Record<string,any>={};if(!current||current.gameDate!==row.date)patch.game_date=row.date;if(row.time&&String(current?.gameTime||'').slice(0,5)!==row.time)patch.game_time=row.time;if(meaningfulLocation(row.location)&&clean(current?.location)!==clean(row.location))patch.location=row.location;if(sourceStatus(row.status)==='Canceled'&&!['canceled','cancelled'].includes(clean(current?.status)))patch.status='Canceled';else if(sourceStatus(row.status)==='Postponed'&&clean(current?.status)!=='postponed')patch.status='Postponed';else if(sourceStatus(row.status)==='Scheduled'&&['canceled','cancelled','postponed'].includes(clean(current?.status))&&['canceled','cancelled','deleted','postponed','ppd'].includes(clean(row.linked?.sourceStatus)))patch.status='Scheduled';const desiredContest=contestType(row.type);if(clean(current?.contestType||'Game')!==clean(desiredContest))patch.contest_type=desiredContest;const entries=Object.entries(patch);if(entries.length){await db.prepare(`UPDATE games SET ${entries.map(([k])=>`${k}=?`).join(',')},updated_at=datetime('now') WHERE id=?`).bind(...entries.map(([,v])=>v),gameId).run();totals.updated++}else totals.verifiedStable++;await link(row,gameId);totals.linked++;await log(row,entries.length?'update-and-link':'verify-and-link','ok',gameId,{bucket:row.bucket,driftReasons:row.driftReasons||[]})}
  async function createGame(row:any){if(!row.sportId||!row.date||row.uniqueGameId==null)throw new Error('Missing sport/date/stable identity for create.');const linked:any=await db.prepare('SELECT game_id FROM arbiter_game_links WHERE arbiter_game_id=? LIMIT 1').bind(row.uniqueGameId).first();if(linked?.game_id){await updateExisting(row,linked.game_id);return}const hi=row.home.kind==='internal'?row.home.id:null,ai=row.away.kind==='internal'?row.away.id:null,he=row.home.kind==='external'?await ensureExternal(row.home):null,ae=row.away.kind==='external'?await ensureExternal(row.away):null;if((!hi&&!he)||(!ai&&!ae))throw new Error('Opponent resolution incomplete during create.');const same=(await db.prepare('SELECT id,game_time,home_team_id,away_team_id,external_home_opponent_id,external_away_opponent_id FROM games WHERE game_date=? AND sport_id=?').bind(row.date,row.sportId).all()).results||[],h=hi?`t:${hi}`:`e:${he}`,a=ai?`t:${ai}`:`e:${ae}`,tok=(g:any,home:boolean)=>{const t=home?g.home_team_id:g.away_team_id,e=home?g.external_home_opponent_id:g.external_away_opponent_id;return t?`t:${t}`:e?`e:${e}`:'tba'},matches=same.filter((g:any)=>(tok(g,true)===h&&tok(g,false)===a)||(tok(g,true)===a&&tok(g,false)===h));let duplicate:any=null;if(row.time){const exact=matches.filter((g:any)=>String(g.game_time||'').slice(0,5)===row.time);if(exact.length>1)throw new Error('Multiple same-team same-time games already exist; manual reconciliation required.');duplicate=exact[0]||null}else if(matches.length)throw new Error('Same teams already play on this date and Arbiter has no reliable time; manual reconciliation required.');if(duplicate){row.existing={id:duplicate.id,gameTime:duplicate.game_time};await updateExisting(row,duplicate.id);await log(row,'duplicate-prevented','ok',duplicate.id,{bucket:row.bucket});return}const id=crypto.randomUUID();await db.prepare(`INSERT INTO games (id,season_id,sport_id,home_team_id,away_team_id,external_home_opponent_id,external_away_opponent_id,game_date,game_time,location,status,verification_status,source,contest_type,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,datetime('now'),datetime('now'))`).bind(id,audit.season.id,row.sportId,hi,ai,he,ae,row.date,row.time||null,meaningfulLocation(row.location)?row.location:null,sourceStatus(row.status),'Reported','arbiter-api',contestType(row.type)).run();try{await link(row,id)}catch(error){await db.prepare('DELETE FROM games WHERE id=?').bind(id).run();throw error}totals.created++;totals.linked++;await log(row,'create-and-link','ok',id,{bucket:row.bucket})}

  for(const row of audit.rows){if(!row.safelyActionable){if(row.bucket==='other-season'){totals.ignoredOtherSeason++;await log(row,'ignore-other-season','skipped',row.existingGameId,{bucket:row.bucket})}else{totals.quarantined++;await log(row,'quarantine','skipped',row.existingGameId,{bucket:row.bucket,issues:row.mappingIssues,warnings:row.warnings})}processed++;await progress();continue}try{if(['stable-id-match','stable-id-update','exact-match','probable-match'].includes(row.bucket)){if(!row.existingGameId)throw new Error(`${row.bucket} missing existingGameId`);await updateExisting(row,row.existingGameId)}else await createGame(row)}catch(error){totals.failed++;await log(row,'write','failed',row.existingGameId,{bucket:row.bucket,error:error instanceof Error?error.message:String(error)})}processed++;await progress()}
  await progress(true)
  try{const deleted=await arbiterApi.deletedGames(audit.window.start,audit.window.end);for(const arbiterId of deletedIds(deleted)){const linked:any=await db.prepare('SELECT game_id FROM arbiter_game_links WHERE arbiter_game_id=? LIMIT 1').bind(arbiterId).first();if(!linked?.game_id)continue;await db.prepare("UPDATE games SET status='Canceled',updated_at=datetime('now') WHERE id=?").bind(linked.game_id).run();await db.prepare("UPDATE arbiter_game_links SET source_status='Deleted',last_seen_at=?,updated_at=? WHERE arbiter_game_id=?").bind(new Date().toISOString(),new Date().toISOString(),arbiterId).run();totals.deletedMarked++;await log({uniqueGameId:arbiterId},'mark-deleted','ok',linked.game_id,{source:'Arbiter DeletedGames'})}}catch(error){await log(null,'deleted-games-check','warning',null,{error:error instanceof Error?error.message:String(error)})}
  const status=totals.failed?'completed-with-errors':'completed';await db.prepare('UPDATE arbiter_sync_runs SET status=?,summary=?,finished_at=? WHERE id=?').bind(status,JSON.stringify(currentSummary()),new Date().toISOString(),runId).run()
  return NextResponse.json({ok:totals.failed===0,controlledWrite:true,runId,season:audit.season,window:audit.window,totals,comparison:audit.comparison,actions:responseLogs.slice(0,200),note:'Only confidently resolved rows were written. Ambiguous or unsafe source rows remain quarantined.'},{status:totals.failed?207:200})
 }catch(error){console.error('Arbiter controlled sync error:',error);if(runId)await db.prepare('UPDATE arbiter_sync_runs SET status=?,summary=?,finished_at=? WHERE id=?').bind('failed',JSON.stringify({error:error instanceof Error?error.message:String(error)}),new Date().toISOString(),runId).run().catch(()=>null);if(error instanceof ArbiterApiError)return NextResponse.json({ok:false,error:error.message,arbiterStatus:error.status,details:error.details},{status:502});return NextResponse.json({ok:false,error:error instanceof Error?error.message:'Unknown error'},{status:500})}
}
