import AdminLayout from '@/components/layout/AdminLayout'
import { getCloudflareContext } from '@opennextjs/cloudflare'

export const revalidate = 0
const n=(v:any)=>Number(v||0)

export default async function TrafficPage(){
 const {env}=getCloudflareContext(),db=(env as any).DB
 let error='';let summary:any={},topPages:any[]=[],sources:any[]=[],daily:any[]=[],devices:any[]=[]
 try{
  if(!db)throw new Error('Cloudflare D1 binding DB is unavailable')
  const now=new Date(),today=now.toISOString().slice(0,10),yesterday=new Date(now.getTime()-86400000).toISOString().slice(0,10),week=new Date(now.getTime()-7*86400000).toISOString(),month=new Date(now.getTime()-30*86400000).toISOString(),five=new Date(now.getTime()-5*60000).toISOString()
  const [s,t,y,w,m,a,tp,src,day,dev]=await Promise.all([
   db.prepare(`SELECT count(*) pageviews,count(DISTINCT visitor_id) visitors,count(DISTINCT session_id) sessions FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=?`).bind(`${today}T00:00:00`).first(),
   db.prepare(`SELECT count(*) pageviews,count(DISTINCT visitor_id) visitors,count(DISTINCT session_id) sessions FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=?`).bind(`${today}T00:00:00`).first(),
   db.prepare(`SELECT count(*) pageviews FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=? AND occurred_at<?`).bind(`${yesterday}T00:00:00`,`${today}T00:00:00`).first(),
   db.prepare(`SELECT count(*) pageviews,count(DISTINCT visitor_id) visitors,count(DISTINCT session_id) sessions FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=?`).bind(week).first(),
   db.prepare(`SELECT count(*) pageviews,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=?`).bind(month).first(),
   db.prepare(`SELECT count(*) pageviews,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0`).first(),
   db.prepare(`SELECT path,max(page_title) title,count(*) pageviews,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=? GROUP BY path ORDER BY pageviews DESC LIMIT 12`).bind(week).all(),
   db.prepare(`SELECT COALESCE(NULLIF(source,''),'Direct / Private Referral') source,count(DISTINCT session_id) visits,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=? GROUP BY COALESCE(NULLIF(source,''),'Direct / Private Referral') ORDER BY visits DESC LIMIT 10`).bind(week).all(),
   db.prepare(`SELECT substr(occurred_at,1,10) day,count(*) pageviews,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=datetime('now','-14 days') GROUP BY substr(occurred_at,1,10) ORDER BY day`).all(),
   db.prepare(`SELECT COALESCE(NULLIF(device_type,''),'Unknown') device,count(DISTINCT session_id) visits,count(DISTINCT visitor_id) visitors FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=? GROUP BY device ORDER BY visits DESC`).bind(week).all(),
  ])
  const live:any=await db.prepare(`SELECT count(DISTINCT visitor_id) c FROM site_traffic_events WHERE is_admin=0 AND is_bot=0 AND occurred_at>=?`).bind(five).first()
  summary={last5m:n(live?.c),todayPageviews:n(t?.pageviews),todayVisitors:n(t?.visitors),todaySessions:n(t?.sessions),yesterdayPageviews:n(y?.pageviews),weekPageviews:n(w?.pageviews),weekVisitors:n(w?.visitors),weekSessions:n(w?.sessions),monthPageviews:n(m?.pageviews),monthVisitors:n(m?.visitors),allPageviews:n(a?.pageviews),allVisitors:n(a?.visitors)}
  topPages=tp.results||[];sources=src.results||[];daily=day.results||[];devices=dev.results||[]
 }catch(e){error=e instanceof Error?e.message:'Traffic query failed'}
 const pct=summary.yesterdayPageviews?Math.round(((summary.todayPageviews-summary.yesterdayPageviews)/summary.yesterdayPageviews)*100):summary.todayPageviews?100:0
 return <AdminLayout><div className="p-4 md:p-6 max-w-7xl mx-auto"><div className="mb-6"><div className="text-xs font-black uppercase tracking-[.22em] text-blue-400 mb-1">Section X Intelligence</div><h1 className="text-3xl font-black text-white">Traffic Command Center</h1><p className="text-sm text-slate-400 mt-1">Cloudflare D1 first-party traffic · bots and admin pages excluded</p></div>{error&&<div className="card p-4 text-red-300 mb-5">{error}</div>}<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3 mb-6">{[['Live now',summary.last5m,'visitors · last 5 min'],['Today',summary.todayPageviews,`pageviews · ${pct>=0?'+':''}${pct}% vs yesterday`],['Today',summary.todayVisitors,'unique visitors'],['7 days',summary.weekPageviews,'pageviews'],['30 days',summary.monthPageviews,'pageviews'],['All time',summary.allPageviews,'pageviews']].map(([l,v,s],i)=><div key={i} className="card p-4"><div className="text-[10px] uppercase font-black tracking-[.18em] text-slate-500">{l}</div><div className="text-3xl font-black text-white mt-1">{n(v).toLocaleString()}</div><div className="text-xs text-slate-500 mt-1">{s}</div></div>)}</div><div className="grid xl:grid-cols-2 gap-5 mb-5"><section className="card p-5"><h2 className="font-black text-white mb-3">Top Pages · 7 days</h2>{topPages.map((r:any,i)=><div key={r.path} className="grid grid-cols-[28px_1fr_auto] gap-3 py-2 border-b border-white/5"><b className="text-blue-400">#{i+1}</b><div className="min-w-0"><div className="text-white truncate">{r.title||r.path}</div><div className="text-xs text-slate-500 truncate">{r.path}</div></div><div className="text-right"><b className="text-white">{n(r.pageviews).toLocaleString()}</b><div className="text-xs text-slate-500">{n(r.visitors)} visitors</div></div></div>)}</section><section className="card p-5"><h2 className="font-black text-white mb-3">Traffic Sources · 7 days</h2>{sources.map((r:any)=><div key={r.source} className="flex justify-between py-2 border-b border-white/5"><span className="text-slate-300">{r.source}</span><span className="text-right"><b className="text-white">{n(r.visits)}</b><span className="text-xs text-slate-500 ml-2">{n(r.visitors)} visitors</span></span></div>)}</section></div><div className="grid xl:grid-cols-2 gap-5"><section className="card p-5"><h2 className="font-black text-white mb-3">14-Day Growth</h2>{daily.map((r:any)=><div key={r.day} className="flex justify-between py-1.5"><span className="text-slate-400">{r.day}</span><b className="text-white">{n(r.pageviews).toLocaleString()} views</b></div>)}</section><section className="card p-5"><h2 className="font-black text-white mb-3">Devices · 7 days</h2>{devices.map((r:any)=><div key={r.device} className="flex justify-between py-2"><span className="text-slate-300">{r.device}</span><b className="text-white">{n(r.visits)} visits</b></div>)}</section></div></div></AdminLayout>
}
