import { notFound } from 'next/navigation'
import { Metadata } from 'next'
import Link from 'next/link'
import PublicLayout from '@/components/layout/PublicLayout'
import { getPlayoffRepository } from '@/lib/data/runtime-playoff-repository'

export const dynamic='force-dynamic'
type Props={params:Promise<{id:string}>}

export async function generateMetadata({params}:Props):Promise<Metadata>{const{id}=await params;const t=await getPlayoffRepository().getTournamentById(id);return{title:t?`${t.name} | Section X Playoffs`:'Playoffs'}}

function fmt(d:string|null,t:string|null){if(!d)return null;const date=new Date(d+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'});if(!t)return date;try{const[h,m]=t.split(':').map(Number),pm=h<8||h>=12;return`${date} · ${h%12||12}:${String(m).padStart(2,'0')} ${pm?'PM':'AM'}`}catch{return date}}
function MatchupCard({game}:{game:any}){const isFinal=String(game?.status||'').toLowerCase()==='final',away=game?.away_name||(game?.seed_away?`#${game.seed_away} Seed`:'TBD'),home=game?.home_name||(game?.seed_home?`#${game.seed_home} Seed`:'TBD'),homeWins=isFinal&&game.home_score!=null&&game.away_score!=null&&game.home_score>game.away_score,awayWins=isFinal&&game.home_score!=null&&game.away_score!=null&&game.away_score>game.home_score,when=fmt(game?.game_date,game?.game_time);return <div className="rounded-xl overflow-hidden w-56 flex-shrink-0" style={{border:isFinal?'1px solid rgba(34,197,94,0.25)':'1px solid rgba(255,255,255,0.1)',background:'rgba(8,12,20,0.95)'}}>{when&&<div className="px-3 py-1 text-xs border-b" style={{borderColor:'rgba(255,255,255,0.06)',background:'rgba(255,255,255,0.03)',color:isFinal?'#4ade80':'#60a5fa'}}>{isFinal?'FINAL':when}</div>}<div className={`flex items-center gap-2 px-3 py-2.5 border-b ${isFinal&&!awayWins?'opacity-35':''}`} style={{borderColor:'rgba(255,255,255,0.05)'}}>{game?.seed_away!=null&&<span className="text-xs font-black text-slate-500 w-5">#{game.seed_away}</span>}<span className="flex-1 text-sm font-bold truncate">{away}</span>{isFinal&&<span className="font-mono font-black">{game.away_score}</span>}</div><div className={`flex items-center gap-2 px-3 py-2.5 ${isFinal&&!homeWins?'opacity-35':''}`}>{game?.seed_home!=null&&<span className="text-xs font-black text-slate-500 w-5">#{game.seed_home}</span>}<span className="flex-1 text-sm font-bold truncate">{home}</span>{isFinal&&<span className="font-mono font-black">{game.home_score}</span>}</div>{game?.location&&<div className="px-3 pb-2 text-xs text-slate-700 truncate">📍 {game.location}</div>}</div>}

export default async function BracketPage({params}:Props){const{id}=await params,repo=getPlayoffRepository(),[tournament,games]=await Promise.all([repo.getTournamentById(id),repo.getGamesForTournament(id)]);if(!tournament)notFound();const rounds=[...new Set(games.map((g:any)=>Number(g.round)))].sort((a,b)=>a-b),names:Record<number,string>={0:'Play-in',1:'Quarterfinals',2:'Semifinals',3:'Final'};return <PublicLayout><div className="max-w-7xl mx-auto px-4 py-6"><div className="flex items-center justify-between mb-6 flex-wrap gap-3"><div><Link href="/playoffs" className="text-xs text-slate-500 hover:text-slate-300 mb-1 block">← All Brackets</Link><div className="flex items-center gap-3"><span className="text-3xl">🏆</span><div><p className="text-xs font-black text-blue-400 uppercase tracking-widest">Class {tournament.class} · {tournament.sport?.gender} {tournament.sport?.sport_name}</p><h1 className="text-2xl md:text-3xl font-black text-white">{tournament.name}</h1><p className="text-slate-500 text-sm">{tournament.season?.name}</p></div></div></div><span className="text-sm font-black px-3 py-1.5 rounded-full uppercase">{tournament.status}</span></div>{rounds.length===0?<div className="rounded-2xl p-16 text-center border border-white/6" style={{background:'rgba(8,12,20,0.7)'}}><p className="text-5xl mb-3">🏆</p><p className="text-white font-black text-lg">Bracket Coming Soon</p><p className="text-slate-500 text-sm mt-1">Matchups will appear here once seedings are set.</p></div>:<><div className="md:hidden space-y-6">{rounds.map(round=><div key={round}><p className="text-xs font-black text-slate-500 uppercase tracking-widest mb-3">{names[round]||`Round ${round}`}</p><div className="space-y-3">{games.filter((g:any)=>Number(g.round)===round).map((g:any)=><MatchupCard key={g.id} game={g}/>)}</div></div>)}</div><div className="hidden md:flex gap-6 overflow-x-auto pb-4">{rounds.map(round=><div key={round} className="flex-shrink-0"><p className="text-xs font-black text-slate-500 uppercase tracking-widest mb-4 text-center">{names[round]||`Round ${round}`}</p><div className="space-y-6">{games.filter((g:any)=>Number(g.round)===round).map((g:any)=><MatchupCard key={g.id} game={g}/>)}</div></div>)}</div></>}</div></PublicLayout>}
