'use client'
import { useState,useEffect,useCallback } from 'react'
import { Trash2,Edit2,Save,X,Search } from 'lucide-react'
import { format } from 'date-fns'

interface Props{
  sports:{id:string;sport_name:string;gender:string}[]
  seasons:{id:string;name:string;is_active:boolean}[]
  teams:{id:string;team_name:string;sport_id:string;school:{school_name:string}|null}[]
}

export default function GamesManager({sports,seasons,teams}:Props){
 const activeSeason=seasons.find(s=>s.is_active)||seasons[0]
 const [games,setGames]=useState<any[]>([]),[loading,setLoading]=useState(true),[seasonFilter,setSeasonFilter]=useState(activeSeason?.id||''),[sportFilter,setSportFilter]=useState(''),[statusFilter,setStatusFilter]=useState(''),[playoffFilter,setPlayoffFilter]=useState(''),[search,setSearch]=useState(''),[editingId,setEditingId]=useState<string|null>(null),[editScores,setEditScores]=useState({home:'',away:'',status:'',date:'',time:''}),[editTeams,setEditTeams]=useState({home_team_id:'',away_team_id:'',external_home_name:'',external_away_name:''}),[editSportId,setEditSportId]=useState(''),[deleting,setDeleting]=useState<string|null>(null),[saving,setSaving]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[bulkDeleting,setBulkDeleting]=useState(false)

 const fetchGames=useCallback(async()=>{
  setLoading(true)
  try{
   const p=new URLSearchParams();if(seasonFilter)p.set('seasonId',seasonFilter);if(sportFilter)p.set('sportId',sportFilter);if(statusFilter)p.set('status',statusFilter);if(playoffFilter)p.set('playoff',playoffFilter)
   const res=await fetch(`/api/admin/games/manage?${p}`,{credentials:'include',cache:'no-store'}),json=await res.json();if(!res.ok)throw new Error(json.error||'Could not load games')
   const today=format(new Date(),'yyyy-MM-dd'),data=json.games||[]
   data.sort((a:any,b:any)=>{const ad=String(a.game_date||''),bd=String(b.game_date||''),at=String(a.game_time||''),bt=String(b.game_time||'');if(ad===today&&bd!==today)return-1;if(bd===today&&ad!==today)return 1;const ap=ad<today,bp=bd<today;if(ap!==bp)return ap?-1:1;if(ap&&bp)return bd.localeCompare(ad)||bt.localeCompare(at);return ad.localeCompare(bd)||at.localeCompare(bt)})
   setGames(data);setSelected(new Set())
  }catch(e:any){alert(e.message||'Could not load games')}finally{setLoading(false)}
 },[seasonFilter,sportFilter,statusFilter,playoffFilter])
 useEffect(()=>{void fetchGames()},[fetchGames])

 async function deleteGame(id:string){if(!confirm('Delete this game and its attached Game Center data?'))return;setDeleting(id);try{const res=await fetch('/api/admin/game-center/cleanup',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId:id,action:'delete'})}),json=await res.json();if(!res.ok)throw new Error(json.error||'Delete failed');setGames(p=>p.filter(g=>g.id!==id));setSelected(p=>{const n=new Set(p);n.delete(id);return n})}catch(e:any){alert(e.message||'Delete failed')}finally{setDeleting(null)}}
 async function bulkDelete(){if(!selected.size||!confirm(`Permanently delete ${selected.size} selected game${selected.size===1?'':'s'} and attached Game Center data?`))return;setBulkDeleting(true);try{for(const id of selected){const res=await fetch('/api/admin/game-center/cleanup',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({gameId:id,action:'delete'})});if(!res.ok){const j=await res.json().catch(()=>({}));throw new Error(j.error||`Delete failed for ${id}`)}}await fetchGames()}catch(e:any){alert(e.message||'Bulk delete failed')}finally{setBulkDeleting(false)}}
 async function saveEdit(id:string){setSaving(true);try{const game=games.find(g=>g.id===id),payload:any={id};if(editScores.home!=='')payload.home_score=parseInt(editScores.home);if(editScores.away!=='')payload.away_score=parseInt(editScores.away);if(editScores.status)payload.status=editScores.status;if(editScores.date)payload.game_date=editScores.date;if(editScores.time)payload.game_time=editScores.time.length===5?editScores.time+':00':editScores.time;if(game?.sport_id)payload.sport_id=game.sport_id;if(editTeams.home_team_id==='EXTERNAL'&&editTeams.external_home_name)payload.external_home_name=editTeams.external_home_name;else if(editTeams.home_team_id)payload.home_team_id=editTeams.home_team_id;if(editTeams.away_team_id==='EXTERNAL'&&editTeams.external_away_name)payload.external_away_name=editTeams.external_away_name;else if(editTeams.away_team_id)payload.away_team_id=editTeams.away_team_id;const res=await fetch('/api/admin/games',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify([payload])}),json=await res.json();if(!res.ok||json?.some?.((x:any)=>x.error))throw new Error(json?.find?.((x:any)=>x.error)?.error||json.error||'Save failed');setEditingId(null);await fetchGames()}catch(e:any){alert(e.message||'Save failed')}finally{setSaving(false)}}
 async function toggleGotn(game:any){try{const res=await fetch('/api/admin/games/manage',{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'game-of-the-night',id:game.id,value:!game.game_of_the_night,gameDate:game.game_date})});if(!res.ok){const j=await res.json().catch(()=>({}));throw new Error(j.error||'Update failed')}await fetchGames()}catch(e:any){alert(e.message||'Update failed')}}
 function startEdit(game:any){setEditingId(game.id);setEditScores({home:game.home_score!=null?String(game.home_score):'',away:game.away_score!=null?String(game.away_score):'',status:game.status||'Final',date:game.game_date||'',time:game.game_time?String(game.game_time).slice(0,5):''});setEditTeams({home_team_id:game.home_team_id||(game.external_home_opponent_id?'EXTERNAL':''),away_team_id:game.away_team_id||(game.external_away_opponent_id?'EXTERNAL':''),external_home_name:game.external_home?.name||'',external_away_name:game.external_away?.name||''});setEditSportId(game.sport?.id||game.sport_id||'')}
 function toggleSelect(id:string){setSelected(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n})}
 const filtered=games.filter(g=>{if(!search)return true;const q=search.toLowerCase(),h=g.home_team?.school?.school_name||g.external_home?.name||'',a=g.away_team?.school?.school_name||g.external_away?.name||'';return h.toLowerCase().includes(q)||a.toLowerCase().includes(q)})
 const statusColors:Record<string,string>={Final:'bg-green-500/20 text-green-400',Scheduled:'bg-blue-500/20 text-blue-400',Postponed:'bg-yellow-500/20 text-yellow-400',Canceled:'bg-red-500/20 text-red-400',Live:'bg-red-500/20 text-red-300 animate-pulse'}

 return <div className="p-4 md:p-6 max-w-6xl mx-auto">
  <h1 className="text-2xl font-bold font-display text-white mb-1">Manage Games</h1><p className="text-slate-400 text-sm mb-5">Today and recent games are shown first. All reads and writes on this screen now use Cloudflare D1.</p>
  <div className="grid grid-cols-2 md:grid-cols-5 gap-3 mb-4"><select value={seasonFilter} onChange={e=>setSeasonFilter(e.target.value)} className="input"><option value="">All Seasons</option>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}{s.is_active?' ✓':''}</option>)}</select><select value={sportFilter} onChange={e=>setSportFilter(e.target.value)} className="input"><option value="">All Sports</option>{sports.map(s=><option key={s.id} value={s.id}>{s.sport_name} ({s.gender})</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)} className="input"><option value="">All Statuses</option><option>Final</option><option>Scheduled</option><option>Postponed</option><option>Canceled</option><option>Live</option></select><select value={playoffFilter} onChange={e=>setPlayoffFilter(e.target.value)} className="input"><option value="">All Games</option><option value="playoff">🏆 Playoffs Only</option><option value="regular">Regular Season Only</option></select><div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search teams..." className="input w-full pl-8"/></div></div>
  <div className="flex flex-wrap items-center gap-2 mb-4"><span className="text-xs text-slate-400">{filtered.length} games</span>{selected.size>0&&<span className="text-xs text-white font-semibold">{selected.size} selected</span>}<div className="flex-1"/>{selected.size>0&&<><button onClick={()=>setSelected(new Set())} className="text-xs px-2 py-1 bg-white/10 rounded text-slate-300">Clear</button><button onClick={bulkDelete} disabled={bulkDeleting} className="text-xs px-3 py-1.5 rounded font-bold flex items-center gap-1 bg-red-500/20 text-red-400"><Trash2 size={12}/>{bulkDeleting?'Deleting...':`Delete ${selected.size}`}</button></>}<button onClick={()=>setSelected(new Set(filtered.filter(g=>g.status==='Postponed').map(g=>g.id)))} className="text-xs px-2 py-1 bg-yellow-500/20 text-yellow-400 rounded">Select PPD</button><button onClick={()=>setSelected(new Set(filtered.filter(g=>g.status==='Canceled').map(g=>g.id)))} className="text-xs px-2 py-1 bg-red-500/20 text-red-400 rounded">Select Canceled</button><button onClick={()=>setSelected(new Set(filtered.map(g=>g.id)))} className="text-xs px-2 py-1 bg-white/10 text-slate-300 rounded">Select All</button></div>
  {loading?<div className="text-center py-12 text-slate-400">Loading games...</div>:!filtered.length?<div className="card p-8 text-center text-slate-400">No games found.</div>:<div className="space-y-1">{filtered.map(game=>{const edit=editingId===game.id,sel=selected.has(game.id),ht=game.home_team?.school?.school_name||game.external_home?.name||'?',at=game.away_team?.school?.school_name||game.external_away?.name||'?',hc=game.home_team?.school?.primary_color||'#334155',ac=game.away_team?.school?.primary_color||'#334155';return <div key={game.id} className={`card overflow-hidden ${sel?'border-ice/40 bg-ice/5':''}`}><div className="p-3 flex items-center gap-3"><input type="checkbox" checked={sel} onChange={()=>toggleSelect(game.id)}/><div className="w-20 text-center"><p className="text-xs text-slate-400">{game.game_date?format(new Date(game.game_date+'T12:00:00'),'MMM d'):'—'}</p>{game.game_time&&<p className="text-xs text-slate-500">{String(game.game_time).slice(0,5)}</p>}</div><div className="w-24 hidden md:block"><p className="text-xs text-slate-400 truncate">{game.sport?.sport_name}</p>{game.is_playoff&&<span className="text-[10px] font-black text-yellow-400">🏆 {game.playoff_round||'PLAYOFF'}</span>}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><i className="w-3 h-3 rounded-full" style={{backgroundColor:ac}}/><span className="text-sm text-slate-200 truncate">{at}</span><b className="ml-auto font-mono">{game.away_score??'—'}</b></div><div className="flex items-center gap-2 mt-1"><i className="w-3 h-3 rounded-full" style={{backgroundColor:hc}}/><span className="text-sm text-slate-200 truncate">{ht}</span><b className="ml-auto font-mono">{game.home_score??'—'}</b></div></div><span className={`text-xs px-2 py-0.5 rounded ${statusColors[game.status]||'bg-white/10 text-slate-400'}`}>{game.status}</span><div className="flex items-center">{edit?<><button onClick={()=>saveEdit(game.id)} className="p-1.5 text-green-400"><Save size={14}/></button><button onClick={()=>setEditingId(null)} className="p-1.5 text-slate-400"><X size={14}/></button></>:<><button onClick={()=>toggleGotn(game)} className={`p-1.5 text-lg ${game.game_of_the_night?'opacity-100':'opacity-20'}`} title="Game of the Night">⭐</button><button onClick={()=>startEdit(game)} className="p-1.5 text-slate-400 hover:text-white"><Edit2 size={14}/></button><button onClick={()=>deleteGame(game.id)} disabled={deleting===game.id} className="p-1.5 text-slate-400 hover:text-red-400"><Trash2 size={14}/></button></>}</div></div>
  {edit&&<div className="border-t border-white/8 p-4 space-y-3 bg-black/20">{game.is_playoff&&<div className="text-xs text-yellow-400 bg-yellow-400/10 rounded-lg px-3 py-2">🏆 Linked playoff game. Score changes sync to the bracket automatically.</div>}<div className="grid sm:grid-cols-3 gap-3"><div><label className="label">Date</label><input type="date" className="input w-full" value={editScores.date} onChange={e=>setEditScores(p=>({...p,date:e.target.value}))}/></div><div><label className="label">Time</label><input type="time" className="input w-full" value={editScores.time} onChange={e=>setEditScores(p=>({...p,time:e.target.value}))}/></div><div><label className="label">Status</label><select className="input w-full" value={editScores.status} onChange={e=>setEditScores(p=>({...p,status:e.target.value}))}><option>Final</option><option>Scheduled</option><option>Postponed</option><option>Canceled</option><option>Live</option></select></div></div><div className="grid sm:grid-cols-2 gap-3">{(['away','home'] as const).map(side=>{const key=`${side}_team_id` as 'away_team_id'|'home_team_id',ext=`external_${side}_name` as 'external_away_name'|'external_home_name';return <div key={side}><label className="label capitalize">{side} Team</label><select className="input w-full" value={editTeams[key]} onChange={e=>setEditTeams(p=>({...p,[key]:e.target.value}))}><option value="">Select</option><option value="EXTERNAL">Non-Section X</option>{(editSportId?teams.filter(t=>t.sport_id===editSportId):teams).map(t=><option key={t.id} value={t.id}>{t.school?.school_name||t.team_name}</option>)}</select>{editTeams[key]==='EXTERNAL'&&<input className="input w-full mt-1" placeholder="Opponent name" value={editTeams[ext]} onChange={e=>setEditTeams(p=>({...p,[ext]:e.target.value}))}/>}<label className="label mt-2 capitalize">{side} Score</label><input type="number" min="0" className="input w-full text-center font-mono" value={editScores[side]} onChange={e=>setEditScores(p=>({...p,[side]:e.target.value}))}/></div>})}</div><div className="flex justify-end gap-2"><button onClick={()=>setEditingId(null)} className="btn-ghost">Cancel</button><button onClick={()=>saveEdit(game.id)} disabled={saving} className="btn-primary"><Save size={14} className="inline mr-1"/>{saving?'Saving...':'Save Changes'}</button></div></div>}</div>})}</div>}
 </div>
}
