// src/app/(public)/athletes/[slug]/page.tsx
import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import PublicLayout from '@/components/layout/PublicLayout'
import FollowButton from '@/components/FollowButton'
export const revalidate=0
type PageProps={params:{slug:string}}
const joined=<T=any>(v:T|T[]|null|undefined):T|null=>Array.isArray(v)?v[0]||null:v||null
function sportName(s:any){if(!s)return'Sport';const n=s.sport_name||'',g=s.gender||'';return(g==='Boys'||g==='Girls')&&!n.toLowerCase().startsWith(g.toLowerCase())?`${g} ${n}`:n}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const supabase=createClient(),{data:a}=await supabase.from('athletes').select('display_name,school:schools(school_name)').eq('slug',params.slug).maybeSingle();if(!a)return{title:'Athlete Not Found | Section X Scoreboard'};const s=joined<any>((a as any).school);return{title:`${a.display_name} | ${s?.school_name||'Section X'} Athlete`,description:`${a.display_name} teams, roster history, and approved photos on Section X Scoreboard.`}}
export default async function AthletePage({params}:PageProps){
 const supabase=createClient();const{data:athlete,error}=await supabase.from('athletes').select(`id,first_name,last_name,display_name,slug,active,school:schools(id,school_name,mascot,slug,city,county,primary_color,secondary_color,logo_url)`).eq('slug',params.slug).maybeSingle();if(error||!athlete)notFound();const school=joined<any>((athlete as any).school)
 const[{data:rosterRows},{data:photoTags}]=await Promise.all([
  supabase.from('roster_entries').select(`id,jersey_number,class_year,position,height,active,imported_at,team:teams(id,team_name,slug,sport:sports(id,sport_name,gender,slug,season_type)),season:seasons(id,name,year,season_type,is_active)`).eq('athlete_id',athlete.id).order('created_at',{ascending:false}),
  supabase.from('photo_athletes').select(`photo:photos(id,photo_url,caption,photographer_credit_name,game_id,created_at)`).eq('athlete_id',athlete.id)])
 const memberships=(rosterRows||[]).map((r:any)=>{const team=joined<any>(r.team),sport=joined<any>(team?.sport),season=joined<any>(r.season);return{...r,team,sport,season}}).filter((r:any)=>r.team&&r.season)
 memberships.sort((a:any,b:any)=>{if(a.season?.is_active&&!b.season?.is_active)return-1;if(!a.season?.is_active&&b.season?.is_active)return 1;return(b.season?.year||0)-(a.season?.year||0)||sportName(a.sport).localeCompare(sportName(b.sport))})
 const current=memberships.filter((r:any)=>r.active&&r.season?.is_active),history=memberships.filter((r:any)=>!r.season?.is_active||!r.active),photos=(photoTags||[]).map((r:any)=>joined<any>(r.photo)).filter(Boolean).sort((a:any,b:any)=>String(b.created_at||'').localeCompare(String(a.created_at||''))),colors={primary:school?.primary_color||'#1e3a5f',secondary:school?.secondary_color||'#0f172a'}
 return <PublicLayout><div className="max-w-4xl mx-auto px-4 py-6"><div className="rounded-2xl p-6 md:p-8 mb-6" style={{background:`linear-gradient(135deg,${colors.primary},${colors.secondary}cc)`,border:'1px solid rgba(255,255,255,.10)'}}><div className="flex items-center justify-between gap-5"><div className="min-w-0">{school&&<Link href={`/schools/${school.slug}`} className="text-xs text-white/60 hover:text-white">{school.school_name}</Link>}<h1 className="text-4xl md:text-5xl font-black text-white mt-2 leading-none" style={{fontFamily:'var(--font-display)'}}>{athlete.display_name}</h1>{school&&<p className="text-white/70 font-bold mt-2">{school.mascot}</p>}<div className="flex flex-wrap gap-2 mt-4"><span className="text-xs rounded-full px-3 py-1 bg-black/20 text-white/70">{current.length} current team{current.length===1?'':'s'}</span><span className="text-xs rounded-full px-3 py-1 bg-black/20 text-white/70">{photos.length} approved photo{photos.length===1?'':'s'}</span><FollowButton targetType="athlete" targetId={athlete.id} targetName={athlete.display_name} compact/></div></div>{school?.logo_url&&<div className="w-20 h-20 md:w-24 md:h-24 rounded-2xl flex-shrink-0 overflow-hidden bg-black/20 border border-white/10"><img src={school.logo_url} alt="" className="w-full h-full object-contain p-2"/></div>}</div></div>
 <section className="mb-7"><div className="flex items-center gap-2 mb-3"><h2 className="text-sm font-black uppercase tracking-widest text-blue-400">Current Teams</h2><div className="flex-1 h-px bg-white/[.06]"/></div>{current.length?<div className="grid md:grid-cols-2 gap-3">{current.map((r:any)=><Link key={r.id} href={`/teams/${r.team.slug}`} className="rounded-xl p-4 bg-white/[.03] border border-white/[.08]"><div className="text-xs text-slate-500 uppercase tracking-wider">{r.season.name}</div><div className="text-lg font-black text-white mt-1">{sportName(r.sport)}</div><div className="flex gap-2 flex-wrap mt-3">{r.jersey_number&&<span className="text-xs rounded-full px-2 py-1 bg-blue-500/10 text-blue-300">#{r.jersey_number}</span>}{[r.class_year,r.position,r.height].filter(Boolean).map((x:string)=><span key={x} className="text-xs rounded-full px-2 py-1 bg-white/5 text-slate-400">{x}</span>)}</div></Link>)}</div>:<div className="rounded-xl p-6 text-sm text-slate-500 bg-black/20 border border-white/[.06]">No verified current team membership is published yet.</div>}</section>
 <section className="mb-7"><div className="flex items-center gap-2 mb-3"><h2 className="text-sm font-black uppercase tracking-widest text-blue-400">Photo Gallery</h2><div className="flex-1 h-px bg-white/[.06]"/><span className="text-xs text-slate-500">{photos.length}</span></div>{photos.length?<div className="grid grid-cols-2 md:grid-cols-3 gap-3">{photos.map((p:any)=>{const card=<div className="group rounded-xl overflow-hidden border border-white/10 bg-white/[.02] h-full"><div className="aspect-[4/3] overflow-hidden bg-black/30"><img src={p.photo_url} alt={p.caption||`${athlete.display_name} photo`} className="w-full h-full object-cover"/></div><div className="p-3">{p.caption&&<div className="text-xs text-slate-300 line-clamp-2">{p.caption}</div>}<div className="text-[10px] text-slate-500 mt-1">Photo: {p.photographer_credit_name||'Section X contributor'}</div></div></div>;return p.game_id?<Link key={p.id} href={`/game-center/${p.game_id}`}>{card}</Link>:<div key={p.id}>{card}</div>})}</div>:<div className="rounded-xl p-6 text-sm text-slate-500 bg-black/20 border border-white/[.06]">No approved photos are tagged to this athlete yet.</div>}</section>
 {history.length>0&&<section className="mb-7"><div className="flex items-center gap-2 mb-3"><h2 className="text-sm font-black uppercase tracking-widest text-slate-400">Team History</h2><div className="flex-1 h-px bg-white/[.06]"/></div><div className="rounded-xl overflow-hidden bg-black/20 border border-white/[.06]">{history.map((r:any)=><Link key={r.id} href={`/teams/${r.team.slug}`} className="flex items-center justify-between gap-4 px-4 py-3 border-b border-white/[.05] last:border-0"><div><div className="font-bold text-white">{sportName(r.sport)}</div><div className="text-xs text-slate-500">{r.season.name}</div></div><div className="text-xs text-slate-500">{r.class_year||''}</div></Link>)}</div></section>}
 <div className="rounded-xl p-4 text-xs text-slate-600 bg-white/[.02] border border-white/[.05]">Current athlete memberships are shown only from verified or manually published rosters. Historical roster information remains available.</div></div></PublicLayout>
}
