// src/app/admin/schedule-audit/ScheduleAudit.tsx
'use client'

import { useMemo, useState } from 'react'
import type { Season, Sport } from '@/types'

interface TeamRecord { id:string; team_name:string; sport_id:string; level:string|null; active:boolean|null; school:{id:string;school_name:string;alias:string|null;slug:string;primary_color:string|null}|null }
interface TeamSeasonRecord { id:string; team_id:string; season_id:string; active_for_season:boolean|null; class:string|null; division:string|null }
interface GameRecord { id:string; season_id:string; sport_id:string; home_team_id:string|null; away_team_id:string|null; external_home_opponent_id:string|null; external_away_opponent_id:string|null; game_date:string; game_time:string|null; location:string|null; status:string; parser_confidence:string|null; game_number:number|null }
interface ImportSourceRecord { id:string; game_id:string; team_id:string; season_id:string; sport_id:string; source:string; imported_at:string }
interface Props { teams:TeamRecord[]; sports:Sport[]; seasons:Season[]; games:GameRecord[]; importSources:ImportSourceRecord[]; teamSeasons:TeamSeasonRecord[] }
interface TeamAudit { team:TeamRecord; sportName:string; gameCount:number; scheduleImported:boolean; confirmedCount:number; singleSourceCount:number; issueCount:number; lastImportedAt:string|null; className:string; division:string; status:'complete'|'partial'|'missing'|'issue' }

const isVarsityTeam=(team:TeamRecord)=>!team.level||team.level.toLowerCase().trim()==='varsity'

export default function ScheduleAudit({teams,sports,seasons,games,importSources,teamSeasons}:Props){
 const defaultSeason=seasons.find(s=>s.is_active)||seasons[0]
 const [seasonId,setSeasonId]=useState(defaultSeason?.id||'')
 const [sportId,setSportId]=useState('')
 const [statusFilter,setStatusFilter]=useState('all')
 const [search,setSearch]=useState('')
 const sportMap=useMemo(()=>new Map(sports.map(s=>[s.id,`${s.sport_name}${s.gender?` (${s.gender})`:''}`])),[sports])
 const participation=useMemo(()=>new Map(teamSeasons.filter(r=>r.season_id===seasonId).map(r=>[r.team_id,r])),[teamSeasons,seasonId])
 const activeTeams=useMemo(()=>teams.filter(t=>isVarsityTeam(t)&&(!sportId||t.sport_id===sportId)&&participation.get(t.id)?.active_for_season===true).sort((a,b)=>(sportMap.get(a.sport_id)||'').localeCompare(sportMap.get(b.sport_id)||'')||(a.school?.school_name||a.team_name).localeCompare(b.school?.school_name||b.team_name)),[teams,sportId,participation,sportMap])
 const activeIds=useMemo(()=>new Set(activeTeams.map(t=>t.id)),[activeTeams])
 const seasonGames=useMemo(()=>games.filter(g=>g.season_id===seasonId&&(!sportId||g.sport_id===sportId)&&((g.home_team_id&&activeIds.has(g.home_team_id))||(g.away_team_id&&activeIds.has(g.away_team_id)))),[games,seasonId,sportId,activeIds])
 const seasonImports=useMemo(()=>importSources.filter(s=>s.season_id===seasonId&&(!sportId||s.sport_id===sportId)&&activeIds.has(s.team_id)),[importSources,seasonId,sportId,activeIds])
 const sourcesByGame=useMemo(()=>{const m=new Map<string,Set<string>>(); seasonImports.forEach(s=>{if(!m.has(s.game_id))m.set(s.game_id,new Set());m.get(s.game_id)!.add(s.team_id)});return m},[seasonImports])
 const rows:TeamAudit[]=useMemo(()=>activeTeams.map(team=>{
   const tg=seasonGames.filter(g=>g.home_team_id===team.id||g.away_team_id===team.id)
   const ti=seasonImports.filter(i=>i.team_id===team.id)
   let confirmed=0,single=0,issues=0
   tg.forEach(g=>{const src=sourcesByGame.get(g.id)||new Set<string>(); const both=!!g.home_team_id&&!!g.away_team_id&&activeIds.has(g.home_team_id)&&activeIds.has(g.away_team_id)&&src.has(g.home_team_id)&&src.has(g.away_team_id); if(both)confirmed++;else single++; if(g.parser_confidence==='Low'||!g.game_date||(!g.home_team_id&&!g.external_home_opponent_id)||(!g.away_team_id&&!g.external_away_opponent_id))issues++})
   const imported=ti.length>0; const p=participation.get(team.id); const last=ti.length?ti.map(i=>i.imported_at).sort().reverse()[0]:null
   let status:TeamAudit['status']='complete'; if(issues>0)status='issue'; else if(!imported&&tg.length===0)status='missing'; else if(!imported||single>0)status='partial'
   return {team,sportName:sportMap.get(team.sport_id)||'Unknown Sport',gameCount:tg.length,scheduleImported:imported,confirmedCount:confirmed,singleSourceCount:single,issueCount:issues,lastImportedAt:last,className:p?.class||'',division:p?.division||'',status}
 }),[activeTeams,seasonGames,seasonImports,sourcesByGame,activeIds,participation,sportMap])
 const visibleRows=useMemo(()=>rows.filter(r=>(statusFilter==='all'||r.status===statusFilter)&&(!search||(r.team.school?.school_name||r.team.team_name).toLowerCase().includes(search.toLowerCase())||r.sportName.toLowerCase().includes(search.toLowerCase()))),[rows,statusFilter,search])
 const counts={complete:rows.filter(r=>r.status==='complete').length,partial:rows.filter(r=>r.status==='partial').length,missing:rows.filter(r=>r.status==='missing').length,issue:rows.filter(r=>r.status==='issue').length}
 const imported=rows.filter(r=>r.scheduleImported).length
 const readiness=rows.length?Math.round((counts.complete/rows.length)*100):0
 const selectedSeason=seasons.find(s=>s.id===seasonId)
 const uniqueGames=seasonGames.length
 const confirmedGames=seasonGames.filter(g=>{if(!g.home_team_id||!g.away_team_id)return false;const src=sourcesByGame.get(g.id);return !!src&&src.has(g.home_team_id)&&src.has(g.away_team_id)}).length
 const ringColor=readiness>=90?'#4ade80':readiness>=70?'#60a5fa':readiness>=40?'#fbbf24':'#f87171'
 return <div className="p-4 md:p-6 max-w-7xl">
   <div className="mb-5"><div className="text-xs font-bold tracking-[.22em] uppercase mb-2" style={{color:'#60a5fa'}}>Season Command Center</div><h1 className="text-3xl font-bold" style={{fontFamily:'var(--font-display)'}}>Schedule Readiness</h1><p className="text-sm mt-1" style={{color:'var(--text-secondary)'}}>One screen for the entire season. Find missing schedules, partial coverage and data problems before opening day.</p></div>
   <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-5"><div><label className="label">Season</label><select className="input" value={seasonId} onChange={e=>setSeasonId(e.target.value)}>{seasons.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div><label className="label">Sport</label><select className="input" value={sportId} onChange={e=>setSportId(e.target.value)}><option value="">All Sports — Season Overview</option>{sports.map(s=><option key={s.id} value={s.id}>{s.sport_name} ({s.gender})</option>)}</select></div></div>
   <div className="rounded-xl p-5 md:p-6 mb-5" style={{background:'linear-gradient(135deg,rgba(37,99,235,.18),var(--bg-card) 58%)',border:'1px solid rgba(96,165,250,.28)'}}><div className="flex flex-col md:flex-row md:items-center gap-6"><div className="shrink-0 w-32 h-32 rounded-full flex items-center justify-center" style={{background:`conic-gradient(${ringColor} ${readiness*3.6}deg,rgba(255,255,255,.08) 0)`,padding:8}}><div className="w-full h-full rounded-full flex flex-col items-center justify-center" style={{background:'var(--bg-card)'}}><div className="text-4xl font-bold" style={{fontFamily:'var(--font-display)'}}>{readiness}%</div><div className="text-[10px] uppercase tracking-wider" style={{color:'var(--text-muted)'}}>Ready</div></div></div><div className="flex-1"><div className="text-xl font-bold" style={{fontFamily:'var(--font-display)'}}>{sportId?(sportMap.get(sportId)||'Sport'):'All Fall Sports'} · {selectedSeason?.name}</div><div className="text-sm mt-1" style={{color:'var(--text-secondary)'}}>{rows.length} active varsity teams · {uniqueGames} unique games · {confirmedGames} games confirmed from both Section X sides</div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4"><Mini label="Complete" value={counts.complete} color="#4ade80"/><Mini label="Needs Review" value={counts.partial} color="#fbbf24"/><Mini label="Missing" value={counts.missing} color="#fb7185"/><Mini label="Data Issues" value={counts.issue} color="#f87171"/></div></div></div></div>
   <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5"><Stat label="Active Teams" value={rows.length}/><Stat label="Own Schedule Imported" value={imported} good/><Stat label="Unique Games" value={uniqueGames}/><Stat label="Confirmed Both Sides" value={confirmedGames} good/></div>
   <div className="grid grid-cols-1 md:grid-cols-[1fr_220px] gap-3 mb-4"><input className="input" placeholder="Search school or sport..." value={search} onChange={e=>setSearch(e.target.value)}/><select className="input" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All Statuses</option><option value="complete">Complete</option><option value="partial">Needs Review</option><option value="missing">Missing</option><option value="issue">Data Issues</option></select></div>
   <div className="rounded-xl overflow-hidden" style={{border:'1px solid var(--border)',background:'var(--bg-card)'}}><div className="hidden md:grid grid-cols-12 gap-2 px-4 py-3 text-xs font-bold uppercase tracking-wide" style={{color:'var(--text-muted)',borderBottom:'1px solid var(--border)'}}><div className="col-span-3">Team</div><div className="col-span-2">Sport</div><div className="col-span-2 text-center">Readiness</div><div className="col-span-1 text-center">Games</div><div className="col-span-2 text-center">Both Confirmed</div><div className="col-span-2 text-center">Single Source</div></div>
   {visibleRows.map(r=><div key={r.team.id} className="grid grid-cols-1 md:grid-cols-12 gap-2 px-4 py-4 items-center text-sm" style={{borderBottom:'1px solid var(--border)'}}><div className="md:col-span-3 min-w-0"><div className="font-semibold" style={{color:'var(--text-primary)'}}>{r.team.school?.school_name||r.team.team_name}</div><div className="text-xs mt-1" style={{color:'var(--text-muted)'}}>{r.lastImportedAt?`Last import ${new Date(r.lastImportedAt).toLocaleDateString()}`:r.gameCount?`${r.gameCount} games loaded via opponents`:'No games loaded'}</div></div><div className="md:col-span-2 text-xs" style={{color:'var(--text-secondary)'}}>{r.sportName}</div><div className="md:col-span-2 md:text-center"><Status status={r.status}/></div><div className="md:col-span-1 md:text-center font-bold">{r.gameCount}</div><div className="md:col-span-2 md:text-center" style={{color:'#4ade80'}}>{r.confirmedCount}</div><div className="md:col-span-2 md:text-center" style={{color:r.singleSourceCount?'#fbbf24':'var(--text-muted)'}}>{r.singleSourceCount}{r.issueCount>0&&<span className="ml-2" style={{color:'#f87171'}}>· {r.issueCount} issue{r.issueCount===1?'':'s'}</span>}</div></div>)}
   {!visibleRows.length&&<div className="p-10 text-center text-sm" style={{color:'var(--text-muted)'}}>Nothing matches this filter. That's either excellent news or an aggressively specific search.</div>}</div>
   <div className="mt-4 rounded-lg p-4 text-xs" style={{background:'rgba(59,130,246,.06)',border:'1px solid rgba(59,130,246,.15)',color:'var(--text-secondary)'}}><strong style={{color:'var(--text-primary)'}}>Readiness logic:</strong> Complete means the team's own schedule has been imported and every loaded Section X-vs-Section X matchup is confirmed from both sides. Needs Review means the team has schedule data but coverage is partial or single-source. Missing means no own import and no games. Data Issues means a loaded game has a parser or opponent-link problem. External opponents do not require two-sided Section X confirmation.</div>
 </div>
}
function Status({status}:{status:TeamAudit['status']}){const cfg={complete:['READY','#4ade80','rgba(74,222,128,.10)'],partial:['NEEDS REVIEW','#fbbf24','rgba(251,191,36,.10)'],missing:['MISSING','#fb7185','rgba(251,113,133,.10)'],issue:['DATA ISSUE','#f87171','rgba(248,113,113,.10)']}[status];return <span className="inline-flex px-2.5 py-1 rounded-full text-[10px] font-bold tracking-wide" style={{color:cfg[1],background:cfg[2]}}>{cfg[0]}</span>}
function Mini({label,value,color}:{label:string;value:number;color:string}){return <div className="rounded-lg px-3 py-2" style={{background:'rgba(0,0,0,.18)',border:'1px solid rgba(255,255,255,.06)'}}><div className="text-2xl font-bold" style={{fontFamily:'var(--font-display)',color}}>{value}</div><div className="text-[10px] uppercase tracking-wide" style={{color:'var(--text-muted)'}}>{label}</div></div>}
function Stat({label,value,good=false}:{label:string;value:number;good?:boolean}){return <div className="rounded-lg p-3" style={{background:'var(--bg-card)',border:'1px solid var(--border)'}}><div className="text-xs mb-1" style={{color:'var(--text-muted)'}}>{label}</div><div className="text-2xl font-bold" style={{fontFamily:'var(--font-display)',color:good?'#4ade80':'var(--text-primary)'}}>{value}</div></div>}
