import { NextRequest, NextResponse } from 'next/server'
import { getCloudflareContext } from '@opennextjs/cloudflare'
import { arbiterApi } from '@/lib/arbiter/client'

export const dynamic='force-dynamic'
export const maxDuration=300

const clean=(v:unknown)=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const text=(v:any)=>String(v??'').replace(/\s+/g,' ').trim()
const num=(v:any)=>Number.isFinite(Number(v))?Number(v):null
const arr=(v:any):any[]=>Array.isArray(v)?v:v==null?[]:[v]
const val=(o:any,...keys:string[])=>{for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null)return o[k]}return null}
const nested=(o:any,...paths:string[])=>{for(const p of paths){let cur=o;for(const part of p.split('.'))cur=cur?.[part];if(cur!==undefined&&cur!==null&&cur!=='')return cur}return null}
function fullName(p:any){return text(val(p,'displayName','fullName','name'))||text([val(p,'firstName','first_name'),val(p,'lastName','last_name')].filter(Boolean).join(' '))}
function findNamedArray(root:any,names:string[]){const wanted=new Set(names.map(clean)),seen=new Set<any>(),q=[root];while(q.length){const cur=q.shift();if(!cur||typeof cur!=='object'||seen.has(cur))continue;seen.add(cur);for(const[k,v]of Object.entries(cur)){if(wanted.has(clean(k))&&Array.isArray(v))return v as any[];if(v&&typeof v==='object')q.push(v)}}return null}
function candidateTeam(raw:any,schoolId:number){return{raw,teamId:num(val(raw,'teamId','teamID','TeamId','TeamID','id','Id','ID')??nested(raw,'team.id','team.teamId')),schoolId:num(val(raw,'schoolId','schoolID','SchoolId','SchoolID')??nested(raw,'school.id'))??schoolId,teamName:text(val(raw,'teamName','TeamName','name','Name','title','Title')??nested(raw,'team.name')),sportId:num(val(raw,'genericSportId','genericSportID','sportId','sportID','SportId','SportID')??nested(raw,'genericSport.id','sport.id')),sportName:text(val(raw,'sportName','SportName','genericSportName','GenericSportName','sport')??nested(raw,'sport.name','genericSport.name')),gender:text(val(raw,'gender','Gender','genderName','GenderName')??nested(raw,'gender.name')),level:text(val(raw,'levelName','LevelName','level','Level','levelDescription','LevelDescription')??nested(raw,'level.name','level.description'))}}
function extractTeamCandidates(root:any,schoolId:number){const out:any[]=[],seen=new Set<any>(),q=[root];while(q.length){const cur=q.shift();if(!cur||typeof cur!=='object'||seen.has(cur))continue;seen.add(cur);if(Array.isArray(cur)){q.push(...cur);continue}const c=candidateTeam(cur,schoolId);if(c.teamId&&(c.teamName||c.sportName||c.sportId))out.push(c);for(const v of Object.values(cur))if(v&&typeof v==='object')q.push(v)}const map=new Map<number,any>();for(const c of out)if(c.teamId&&!map.has(c.teamId))map.set(c.teamId,c);return[...map.values()]}
function normalizeSport(v:unknown){return clean(v).replace(/girls|boys|mens|womens|male|female/g,'').replace(/association football/g,'soccer').replace(/crosscountry/g,'cross country').replace(/volley ball/g,'volleyball').replace(/\s+/g,' ').trim()}
function sportEquivalent(a:unknown,b:unknown){const x=normalizeSport(a),y=normalizeSport(b);return Boolean(x&&y&&(x===y||x.includes(y)||y.includes(x)))}
function genderCompatible(c:unknown,t:unknown,name:unknown=''){const dg=clean(t),cg=clean(c),cn=clean(name);if(!dg)return true;if(cg)return cg===dg||cg.startsWith(dg)||dg.startsWith(cg);if(cn.includes('boys'))return dg.includes('boy')||dg.includes('male');if(cn.includes('girls'))return dg.includes('girl')||dg.includes('female');return true}
function varsity(v:unknown){const c=clean(v);return c.includes('varsity')&&!c.includes('junior')}
function normalizePlayer(p:any){const displayName=fullName(p);return{jerseyNumber:text(val(p,'jerseyNumber','jersey','number')),rawName:displayName,displayName,firstName:text(val(p,'firstName','first_name')),lastName:text(val(p,'lastName','last_name')),classYear:text(val(p,'classYear','class','grade','graduationYear')),position:text(val(p,'position','positionName')),height:text(val(p,'height'))}}
function normalizeCoach(p:any){const displayName=fullName(p);return{rawName:displayName,displayName,firstName:text(val(p,'firstName','first_name')),lastName:text(val(p,'lastName','last_name')),title:text(val(p,'title','role','position'))}}
async function fetchSchoolTeams(sid:number){const attempts=[{SchoolId:sid},{schoolId:sid},{SchoolIDs:[sid]},{SchoolIds:[sid]}],diag:any[]=[];for(const query of attempts){try{const raw=await arbiterApi.teams(query as any),teams=extractTeamCandidates(raw,sid);diag.push({query:Object.keys(query)[0],teamsFound:teams.length});if(teams.length)return{teams,diag}}catch(e){diag.push({query:Object.keys(query)[0],error:e instanceof Error?e.message:String(e)})}}return{teams:[],diag}}

export async function GET(req:NextRequest){
 try{
  const {env}=getCloudflareContext(),db=(env as any).DB;if(!db)throw new Error('Cloudflare D1 binding DB is unavailable')
  const seasonId=req.nextUrl.searchParams.get('seasonId'),offset=Math.max(0,Number(req.nextUrl.searchParams.get('teamOffset')||0)||0),rawLimit=req.nextUrl.searchParams.get('teamLimit'),limit=rawLimit===null?999:Math.max(1,Math.min(20,Number(rawLimit)||8))
  const season:any=seasonId?await db.prepare('SELECT id,name,season_type,year,is_active FROM seasons WHERE id=? LIMIT 1').bind(seasonId).first():await db.prepare('SELECT id,name,season_type,year,is_active FROM seasons WHERE is_active=1 ORDER BY year DESC LIMIT 1').first();if(!season)throw new Error('No season found')
  const [schoolQ,teamQ,sportQ,activeQ,rosterQ]=await Promise.all([db.prepare('SELECT id,school_name,arbiter_entity_id FROM schools WHERE active=1 AND arbiter_entity_id IS NOT NULL').all(),db.prepare('SELECT id,school_id,sport_id,team_name,level,active FROM teams WHERE active=1').all(),db.prepare('SELECT id,sport_name,gender,season_type,slug FROM sports').all(),db.prepare('SELECT team_id FROM team_seasons WHERE season_id=? AND active_for_season=1').bind(season.id).all(),db.prepare('SELECT team_id FROM roster_entries WHERE season_id=? AND active=1').bind(season.id).all()])
  const schools:any[]=schoolQ.results||[],teams:any[]=teamQ.results||[],sports:any[]=sportQ.results||[],activeIds=new Set((activeQ.results||[]).map((x:any)=>x.team_id)),schoolById=new Map(schools.map(s=>[s.id,s])),sportById=new Map(sports.map(s=>[s.id,s])),rosterCount=new Map<string,number>();for(const r of rosterQ.results||[])rosterCount.set((r as any).team_id,(rosterCount.get((r as any).team_id)||0)+1)
  const allVarsity=teams.filter(t=>activeIds.has(t.id)&&varsity(t.level)).sort((a,b)=>String(a.id).localeCompare(String(b.id))),batch=allVarsity.slice(offset,offset+limit),schoolIds=[...new Set(batch.map(t=>Number((schoolById.get(t.school_id) as any)?.arbiter_entity_id)).filter(Number.isFinite))]
  const arbiterBySchool=new Map<number,any[]>(),diagnostics:any[]=[];for(let i=0;i<schoolIds.length;i+=6){const ids=schoolIds.slice(i,i+6),found=await Promise.all(ids.map(async sid=>({sid,result:await fetchSchoolTeams(sid)})));for(const f of found){arbiterBySchool.set(f.sid,f.result.teams);diagnostics.push({schoolId:f.sid,teamsFound:f.result.teams.length,attempts:f.result.diag})}}
  const rows:any[]=[],importPayloads:any[]=[]
  for(const team of batch){const school:any=schoolById.get(team.school_id),sport:any=sportById.get(team.sport_id),sid=Number(school?.arbiter_entity_id),candidates=(arbiterBySchool.get(sid)||[]).filter(c=>sportEquivalent(c.sportName||c.teamName,sport?.sport_name)&&genderCompatible(c.gender,sport?.gender,c.teamName)&&(varsity(c.level)||!c.level));let best:any=null,reason='team-not-matched';if(candidates.length===1){best=candidates[0];reason='matched-by-team-endpoint'}else if(candidates.length>1)reason='ambiguous-team-endpoint';if(!best){rows.push({teamId:team.id,teamName:team.team_name,school:school?.school_name,sport:sport?.sport_name,gender:sport?.gender,arbiterTeamId:null,existingRosterCount:rosterCount.get(team.id)||0,rosterFound:false,rosterCount:0,coachesFound:false,coachCount:0,status:candidates.length>1?'ambiguous-team-match':'team-not-matched',diagnosticReason:reason,candidates:candidates.slice(0,5)});continue}
   try{const payload=await arbiterApi.teamWithRoster(best.teamId,sid),playersRaw=findNamedArray(payload,['roster','rosters','players','athletes','studentAthletes']),coachesRaw=findNamedArray(payload,['coaches','coachingStaff','staff']),roster=(playersRaw||[]).map(normalizePlayer).filter(p=>p.displayName),coaches=(coachesRaw||[]).map(normalizeCoach).filter(p=>p.displayName),rosterFound=playersRaw!==null,coachesFound=coachesRaw!==null;if(rosterFound||coachesFound)importPayloads.push({team_id:team.id,season_id:season.id,source_url:null,roster_found:rosterFound,coaches_found:coachesFound,roster,coaches});rows.push({teamId:team.id,teamName:team.team_name,school:school?.school_name,sport:sport?.sport_name,gender:sport?.gender,arbiterTeamId:best.teamId,arbiterTeamName:best.teamName,identitySource:'team-endpoint',existingRosterCount:rosterCount.get(team.id)||0,rosterFound,rosterCount:roster.length,coachesFound,coachCount:coaches.length,status:rosterFound?'available':'no-roster-published',diagnosticReason:rosterFound?'published-roster-found':'team-matched-roster-not-published'})}catch(e){rows.push({teamId:team.id,teamName:team.team_name,school:school?.school_name,sport:sport?.sport_name,arbiterTeamId:best.teamId,existingRosterCount:rosterCount.get(team.id)||0,status:'roster-fetch-error',error:e instanceof Error?e.message:String(e)})}}
  rows.sort((a,b)=>String(a.school).localeCompare(String(b.school))||String(a.sport).localeCompare(String(b.sport)));const nextOffset=Math.min(allVarsity.length,offset+rows.length),counts={teams:rows.length,totalVarsity:allVarsity.length,batchOffset:offset,batchLimit:limit,processed:rows.length,nextOffset,hasMore:nextOffset<allVarsity.length,available:rows.filter(r=>r.status==='available').length,noRosterPublished:rows.filter(r=>r.status==='no-roster-published').length,teamNotFound:rows.filter(r=>r.status==='team-not-matched').length,ambiguous:rows.filter(r=>r.status==='ambiguous-team-match').length,errors:rows.filter(r=>r.status==='roster-fetch-error').length,alreadyLoaded:rows.filter(r=>r.existingRosterCount>0).length,importPayloads:importPayloads.length}
  return NextResponse.json({ok:true,readOnly:true,season:{...season,is_active:Boolean(season.is_active)},counts,rows,importPayloads,diagnostics:{schools:diagnostics,totalArbiterTeams:[...arbiterBySchool.values()].reduce((n,a)=>n+a.length,0)}})
 }catch(error){console.error('Partner API roster scan failed:',error);return NextResponse.json({ok:false,readOnly:true,error:error instanceof Error?error.message:'Unknown error'},{status:500})}
}
