'use client'
import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'

type Participant={teamId:string;name:string;placement:string;score:string;points:string;notes:string}
const blank=():Participant=>({teamId:'',name:'',placement:'',score:'',points:'',notes:''})
const emptyForm={id:'',eventName:'',eventFormat:'invitational',sportId:'',gameDate:'',gameTime:'',location:'',status:'Final',countsForStandings:false,notes:'',participants:[blank(),blank()] as Participant[]}

export default function MeetManager(){
 const [events,setEvents]=useState<any[]>([]),[sports,setSports]=useState<any[]>([]),[teams,setTeams]=useState<any[]>([]),[form,setForm]=useState<any>(emptyForm),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/admin/meets',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not load meets');setEvents(j.events||[]);setSports(j.sports||[]);setTeams(j.teams||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const sportTeams=useMemo(()=>teams.filter(t=>!form.sportId||t.sport_id===form.sportId),[teams,form.sportId])
 function setP(i:number,patch:any){setForm((f:any)=>({...f,participants:f.participants.map((p:any,n:number)=>n===i?{...p,...patch}:p)}))}
 function addRow(){setForm((f:any)=>({...f,participants:[...f.participants,blank()]}))}
 function removeRow(i:number){setForm((f:any)=>({...f,participants:f.participants.filter((_:any,n:number)=>n!==i)}))}
 function reset(){setForm({...emptyForm,participants:[blank(),blank()]});setMessage('');setError('')}
 function edit(e:any){setForm({id:e.id,eventName:e.event_name||'',eventFormat:e.event_format||'invitational',sportId:e.sport_id||'',gameDate:e.game_date||'',gameTime:String(e.game_time||'').slice(0,5),location:e.location||'',status:e.status||'Scheduled',countsForStandings:Boolean(e.counts_for_standings),notes:e.notes||'',participants:(e.participants||[]).map((p:any)=>({teamId:p.team_id||'',name:p.team_id?'':(p.display_name||p.name||''),placement:p.placement==null?'':String(p.placement),score:p.score==null?'':String(p.score),points:p.points==null?'':String(p.points),notes:p.notes||''}))});window.scrollTo({top:0,behavior:'smooth'})}
 async function save(){setSaving(true);setError('');setMessage('');try{const r=await fetch('/api/admin/meets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'save',...form})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not save meet');setMessage('Meet saved.');reset();await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function del(id:string){if(!confirm('Delete this meet/invitational?'))return;const r=await fetch('/api/admin/meets',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'delete',id})});if(r.ok)await load()}
 return <div className="p-4 md:p-6 max-w-6xl mx-auto space-y-6">
  <div className="flex flex-col md:flex-row md:items-end justify-between gap-3"><div><div className="text-xs font-black uppercase tracking-widest text-blue-300">Multi-Team Events</div><h1 className="text-3xl font-black text-white">Meet / Invitational Manager</h1><p className="text-sm text-slate-500 mt-1">Swimming, cross country, track, golf and any event with more than two teams.</p></div><Link href="/admin/games" className="btn-ghost">Back to Game Manager</Link></div>
  {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300">{error}</div>}{message&&<div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-emerald-300">{message}</div>}
  <section className="card p-4 md:p-5 space-y-4"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-white">{form.id?'Edit Event':'Add Event'}</h2>{form.id&&<button className="btn-ghost" onClick={reset}>New Event</button>}</div>
   <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-3"><div className="lg:col-span-2"><label className="label">Event name *</label><input className="input w-full" placeholder="St. Lawrence University Invitational" value={form.eventName} onChange={e=>setForm((f:any)=>({...f,eventName:e.target.value}))}/></div><div><label className="label">Format</label><select className="input w-full" value={form.eventFormat} onChange={e=>setForm((f:any)=>({...f,eventFormat:e.target.value}))}><option value="invitational">Invitational</option><option value="meet">Meet</option></select></div><div><label className="label">Sport *</label><select className="input w-full" value={form.sportId} onChange={e=>setForm((f:any)=>({...f,sportId:e.target.value}))}><option value="">Choose sport</option>{sports.map(s=><option key={s.id} value={s.id}>{s.gender&&s.gender!=='Both'?`${s.gender} `:''}{s.sport_name}</option>)}</select></div><div><label className="label">Date *</label><input type="date" className="input w-full" value={form.gameDate} onChange={e=>setForm((f:any)=>({...f,gameDate:e.target.value}))}/></div><div><label className="label">Time</label><input type="time" className="input w-full" value={form.gameTime} onChange={e=>setForm((f:any)=>({...f,gameTime:e.target.value}))}/></div><div><label className="label">Location</label><input className="input w-full" value={form.location} onChange={e=>setForm((f:any)=>({...f,location:e.target.value}))}/></div><div><label className="label">Status</label><select className="input w-full" value={form.status} onChange={e=>setForm((f:any)=>({...f,status:e.target.value}))}><option>Scheduled</option><option>Final</option><option>Postponed</option><option>Canceled</option></select></div></div>
   <label className="flex items-start gap-3 rounded-lg border border-white/10 bg-black/20 p-3"><input type="checkbox" className="mt-1" checked={form.countsForStandings} onChange={e=>setForm((f:any)=>({...f,countsForStandings:e.target.checked}))}/><span><b className="text-white text-sm">Counts for league standings</b><span className="block text-xs text-slate-500">Leave this OFF for normal invitationals. Placements will be published without creating fake W-L results.</span></span></label>
   <div><label className="label">Notes</label><textarea className="input w-full" rows={2} value={form.notes} onChange={e=>setForm((f:any)=>({...f,notes:e.target.value}))}/></div>
   <div className="space-y-2"><div className="flex items-center justify-between"><h3 className="font-black text-white">Team Results</h3><button className="btn-ghost text-sm" onClick={addRow}>+ Add team</button></div>{form.participants.map((p:Participant,i:number)=><div key={i} className="grid grid-cols-12 gap-2 rounded-lg border border-white/10 p-3"><div className="col-span-12 md:col-span-5"><select className="input w-full" value={p.teamId} onChange={e=>setP(i,{teamId:e.target.value,name:e.target.value?'':p.name})}><option value="">Outside / other team</option>{sportTeams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{!p.teamId&&<input className="input w-full mt-2" placeholder="Team name (Peru, Plattsburgh...)" value={p.name} onChange={e=>setP(i,{name:e.target.value})}/>}</div><div className="col-span-4 md:col-span-2"><input className="input w-full" type="number" min="1" placeholder="Place" value={p.placement} onChange={e=>setP(i,{placement:e.target.value})}/></div><div className="col-span-5 md:col-span-2"><input className="input w-full" type="number" step="any" placeholder="Score" value={p.score} onChange={e=>setP(i,{score:e.target.value})}/></div><div className="col-span-2 md:col-span-2"><input className="input w-full" type="number" step="any" placeholder="Pts" value={p.points} onChange={e=>setP(i,{points:e.target.value})}/></div><div className="col-span-1 flex justify-end"><button className="text-red-400 px-2" onClick={()=>removeRow(i)} disabled={form.participants.length<=2}>×</button></div></div>)}</div>
   <div className="flex justify-end"><button className="btn-primary px-6 py-3" disabled={saving} onClick={save}>{saving?'Saving...':form.id?'Save Changes':'Create Meet / Invitational'}</button></div>
  </section>
  <section className="space-y-3"><h2 className="text-xl font-black text-white">Recent Meets</h2>{loading?<div className="text-slate-500">Loading...</div>:events.length?events.map(e=><div key={e.id} className="card p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-black text-white">{e.event_name}</div><div className="text-xs text-slate-500">{e.game_date} · {e.gender&&e.gender!=='Both'?`${e.gender} `:''}{e.sport_name} · {e.participants?.length||0} teams · {e.status}</div><div className="text-xs mt-1"><span className={e.counts_for_standings?'text-amber-300':'text-emerald-300'}>{e.counts_for_standings?'Counts for standings':'Does not affect W-L standings'}</span></div></div><div className="flex gap-2"><Link className="btn-ghost" href={`/meets/${e.id}`} target="_blank">View</Link><button className="btn-ghost" onClick={()=>edit(e)}>Edit</button><button className="btn-ghost text-red-400" onClick={()=>del(e.id)}>Delete</button></div></div>):<div className="card p-6 text-slate-500">No multi-team meets entered yet.</div>}</section>
 </div>
}
