'use client'

import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, RefreshCw, ShieldCheck, Users, Play } from 'lucide-react'

function statusTone(status:string){if(status==='completed')return{label:'Healthy',className:'text-emerald-300',dot:'bg-emerald-400'};if(status==='running')return{label:'Running',className:'text-sky-300',dot:'bg-sky-400'};if(status==='completed-with-errors')return{label:'Completed with errors',className:'text-amber-300',dot:'bg-amber-400'};return{label:'Failed',className:'text-red-300',dot:'bg-red-400'}}
function fmt(value:string|null|undefined){if(!value)return'—';return new Date(value).toLocaleString('en-US',{timeZone:'America/New_York',month:'numeric',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
function hoursSince(value:string|null|undefined){if(!value)return Number.POSITIVE_INFINITY;return Math.max(0,(Date.now()-new Date(value).getTime())/3_600_000)}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))

export default function AutomationPanel({runs,cron,rosterRuns,rosterCron}:{runs:any[];cron:any|null;rosterRuns:any[];rosterCron:any|null}){
  const router=useRouter(),[runningNow,setRunningNow]=useState(false),[runMessage,setRunMessage]=useState('')
  const latest=runs?.[0]||null,rosterLatest=rosterRuns?.[0]||null,s=latest?.summary||{},rs=rosterLatest?.summary||{},schedule=s.schedule||{},scores=s.scores||{},changed=Number(schedule.updated||0)+Number(schedule.created||0)+Number(schedule.deletedMarked||0)+Number(scores.updated||0),enabled=Boolean(cron?.active),rosterEnabled=Boolean(rosterCron?.active)
  const scheduleStale=Boolean(latest)&&hoursSince(latest?.finished_at||latest?.started_at)>8,rosterAwaitingFirst=rosterEnabled&&!rosterLatest,rosterStale=Boolean(rosterLatest)&&hoursSince(rosterLatest?.finished_at||rosterLatest?.started_at)>30
  const scheduleHardProblem=!enabled||!latest||scheduleStale||latest?.status==='failed'||Number(schedule.failed||0)>0||Number(scores.failed||0)>0||Number(schedule.blockers||0)>0
  const rosterHardProblem=!rosterEnabled||rosterStale||rosterLatest?.status==='failed'||Number(rs.failed||0)>0
  const scheduleReview=latest?.status==='completed-with-errors'
  const rosterReview=rosterLatest?.status==='completed-with-errors'||Number(rs.quarantined||0)>0||Number(rs.scanWarnings?.ambiguous||0)>0||Number(rs.scanWarnings?.apiErrors||0)>0
  const overall=scheduleHardProblem||rosterHardProblem?{label:'Automation needs attention',className:'text-red-300',border:'border-red-500/30 bg-red-500/10'}:rosterAwaitingFirst?{label:'Automation active · first roster run pending',className:'text-amber-300',border:'border-amber-500/30 bg-amber-500/10'}:scheduleReview||rosterReview?{label:'Automation healthy · review items waiting',className:'text-amber-300',border:'border-amber-500/30 bg-amber-500/10'}:{label:'Automation healthy',className:'text-emerald-300',border:'border-emerald-500/30 bg-emerald-500/10'}

  async function runRosterNow(){
    if(runningNow)return
    setRunningNow(true);setRunMessage('Requesting guarded roster reconciliation…')
    const startedMs=Date.now()
    try{
      const response=await fetch('/api/admin/arbiter-api/roster-automation',{method:'POST',cache:'no-store'}),body=await response.json()
      if(!response.ok)throw new Error(body?.error||`Request failed (${response.status})`)
      setRunMessage('Roster automation queued. Waiting for Arbiter reconciliation…')
      for(let i=0;i<80;i++){
        await sleep(3000)
        const statusResponse=await fetch('/api/admin/arbiter-api/roster-automation',{cache:'no-store'}),statusBody=await statusResponse.json()
        if(!statusResponse.ok)continue
        const candidate=(statusBody?.runs||[]).find((run:any)=>new Date(run.started_at).getTime()>=startedMs-10000)
        if(!candidate){setRunMessage('Waiting for the secure roster worker to start…');continue}
        if(candidate.status==='running'){setRunMessage('Roster reconciliation is running…');continue}
        const summary=candidate.summary||{}
        if(candidate.status==='completed')setRunMessage(`Completed: ${Number(summary.teamsUpdated||0)} teams reconciled, ${Number(summary.athletesAdded||0)} athletes added, ${Number(summary.quarantined||0)} changes held for review.`)
        else setRunMessage(candidate.status==='completed-with-errors'?`Completed with errors: ${Number(summary.failed||0)} failure(s). Review the run details below.`:`Roster automation failed: ${summary.error||'Unknown error'}`)
        router.refresh();return
      }
      setRunMessage('The roster run is taking longer than expected. It will continue server-side; refresh this page in a few minutes.')
      router.refresh()
    }catch(error){setRunMessage(error instanceof Error?error.message:'Could not start roster automation.')}
    finally{setRunningNow(false)}
  }

  return <div className="card p-4 space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><ShieldCheck size={20} className={!scheduleHardProblem&&!rosterHardProblem?'text-emerald-300':'text-amber-300'}/><h2 className="font-semibold text-white">Arbiter Automation</h2><span className={`text-[10px] px-2 py-1 rounded-full border ${enabled?'text-emerald-300 border-emerald-500/30 bg-emerald-500/10':'text-amber-300 border-amber-500/30 bg-amber-500/10'}`}>SCHEDULE {enabled?'ACTIVE':'INACTIVE'}</span><span className={`text-[10px] px-2 py-1 rounded-full border ${rosterEnabled?'text-emerald-300 border-emerald-500/30 bg-emerald-500/10':'text-amber-300 border-amber-500/30 bg-amber-500/10'}`}>ROSTERS {rosterEnabled?'ACTIVE':'INACTIVE'}</span></div><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Secure Supabase scheduler → Arbiter Partner API → safety reconciliation → controlled automatic upsert.</p></div><div className="text-xs lg:text-right" style={{color:'var(--text-muted)'}}><div>Schedules + scores: 5 checks daily</div><div>Rosters: 1 guarded reconciliation daily</div></div></div>

    <div className={`rounded-lg border p-3 ${overall.border}`}><div className="flex items-start gap-2">{scheduleHardProblem||rosterHardProblem?<AlertTriangle size={16} className="mt-0.5 text-red-300"/>:<CheckCircle2 size={16} className="mt-0.5 text-emerald-300"/>}<div><b className={overall.className}>{overall.label}</b><div className="text-xs mt-1" style={{color:'var(--text-muted)'}}>{scheduleStale?'Schedule automation has not completed within the expected window. ':''}{rosterStale?'Roster automation has missed its expected daily window. ':''}{rosterAwaitingFirst?'Roster scheduler is armed and waiting for its first successful reconciliation. ':''}{rosterReview?`${Number(rs.quarantined||0)} roster change${Number(rs.quarantined||0)===1?'':'s'} withheld for review. `:''}{!scheduleHardProblem&&!rosterHardProblem&&!rosterAwaitingFirst&&!scheduleReview&&!rosterReview?'No automation failures or unresolved blockers detected.':''}</div></div></div></div>

    <div className="grid lg:grid-cols-2 gap-4">
      <div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2"><ShieldCheck size={16}/><b className="text-white">Schedules & scores</b></div><span className="text-xs" style={{color:'var(--text-muted)'}}>{fmt(latest?.started_at)}</span></div>{!latest?<div className="text-amber-300 text-sm">No automatic schedule run recorded yet.</div>:latest.status==='running'?<div className="flex items-center gap-2 text-sky-300 text-sm"><RefreshCw size={15} className="animate-spin"/>Reconciliation is running now.</div>:latest.status==='failed'?<div className="flex items-start gap-2 text-red-300 text-sm"><AlertTriangle size={15} className="mt-0.5"/><span>{s.error||'Automatic schedule run failed.'}</span></div>:<><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(schedule.stableLinks||0)}</b><div style={{color:'var(--text-muted)'}}>Stable links checked</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{changed}</b><div style={{color:'var(--text-muted)'}}>Changes applied</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(scores.updated||0)}</b><div style={{color:'var(--text-muted)'}}>Scores applied</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(schedule.failed||0)+Number(scores.failed||0)}</b><div style={{color:'var(--text-muted)'}}>Write failures</div></div></div><div className="text-xs mt-3 flex flex-wrap gap-x-3 gap-y-1" style={{color:'var(--text-muted)'}}><span>{Number(schedule.updated||0)} updated</span><span>{Number(schedule.created||0)} created</span><span>{Number(schedule.deletedMarked||0)} cancelled</span><span>{Number(schedule.quarantined||0)} quarantined</span><span>{Number(schedule.blockers||0)} blockers</span></div></>}</div>

      <div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><div className="flex items-center gap-2"><Users size={16}/><b className="text-white">Roster intelligence</b></div><button type="button" onClick={runRosterNow} disabled={runningNow||!rosterEnabled} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40 hover:bg-white/5"><Play size={13}/>{runningNow?'Running…':'Run Roster Automation Now'}</button></div>{runMessage&&<div className={`mb-3 rounded border p-2 text-xs ${runMessage.startsWith('Roster automation failed')||runMessage.startsWith('Could not')?'border-red-500/30 bg-red-500/10 text-red-300':'border-sky-500/20 bg-sky-500/10 text-sky-200'}`}>{runMessage}</div>}{!rosterLatest?<div className="text-amber-300 text-sm">Daily roster automation is armed. First run has not completed yet.</div>:rosterLatest.status==='running'?<div className="flex items-center gap-2 text-sky-300 text-sm"><RefreshCw size={15} className="animate-spin"/>Roster reconciliation is running now.</div>:rosterLatest.status==='failed'?<div className="flex items-start gap-2 text-red-300 text-sm"><AlertTriangle size={15} className="mt-0.5"/><span>{rs.error||'Automatic roster run failed.'}</span></div>:<><div className="flex items-center justify-between gap-2 mb-3 text-xs" style={{color:'var(--text-muted)'}}><span>Last run {fmt(rosterLatest?.started_at)}</span><span>{rosterLatest?.finished_at?`Finished ${fmt(rosterLatest.finished_at)}`:'—'}</span></div><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.scanned||0)}</b><div style={{color:'var(--text-muted)'}}>Varsity teams scanned</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.teamsUpdated||0)}</b><div style={{color:'var(--text-muted)'}}>Teams reconciled</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.athletesAdded||0)}</b><div style={{color:'var(--text-muted)'}}>Athletes added</div></div><div className="rounded bg-black/20 p-3"><b className={Number(rs.quarantined||0)?'text-amber-300':'text-white'}>{Number(rs.quarantined||0)}</b><div style={{color:'var(--text-muted)'}}>Changes withheld</div></div></div><div className="text-xs mt-3 flex flex-wrap gap-x-3 gap-y-1" style={{color:'var(--text-muted)'}}><span>{Number(rs.published||0)} published</span><span>{Number(rs.unchanged||0)} unchanged</span><span>{Number(rs.athleteMetadataUpdated||0)} athlete details refreshed</span><span>{Number(rs.coachesAdded||0)} coaches added</span><span>{Number(rs.failed||0)} failures</span></div></>}</div>
    </div>

    <div className="grid lg:grid-cols-2 gap-4"><div><div className="flex items-center gap-2 mb-2"><Clock3 size={16}/><h3 className="text-sm font-semibold text-white">Schedule automation history</h3></div><div className="space-y-2">{(runs||[]).slice(0,5).map((run:any)=>{const t=statusTone(run.status),x=run.summary||{},sch=x.schedule||{},sc=x.scores||{},changes=Number(sch.updated||0)+Number(sch.created||0)+Number(sch.deletedMarked||0)+Number(sc.updated||0);return <div key={run.id} className="rounded border border-white/10 bg-black/20 p-3 flex items-center justify-between gap-2 text-xs"><div className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${t.dot}`}/><b className={t.className}>{t.label}</b><span style={{color:'var(--text-muted)'}}>{fmt(run.started_at)}</span></div><span style={{color:'var(--text-muted)'}}>{changes} changes</span></div>})}</div></div><div><div className="flex items-center gap-2 mb-2"><Users size={16}/><h3 className="text-sm font-semibold text-white">Roster automation history</h3></div><div className="space-y-2">{(rosterRuns||[]).slice(0,5).map((run:any)=>{const t=statusTone(run.status),x=run.summary||{};return <div key={run.id} className="rounded border border-white/10 bg-black/20 p-3 text-xs"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className={`w-2 h-2 rounded-full ${t.dot}`}/><b className={t.className}>{t.label}</b><span style={{color:'var(--text-muted)'}}>{fmt(run.started_at)}</span></div><span style={{color:'var(--text-muted)'}}>{Number(x.teamsUpdated||0)} teams · {Number(x.quarantined||0)} held</span></div>{run.status!=='running'&&<div className="mt-2 flex flex-wrap gap-x-3 gap-y-1" style={{color:'var(--text-muted)'}}><span>{Number(x.scanned||0)} scanned</span><span>{Number(x.athletesAdded||0)} athletes added</span><span>{Number(x.athleteMetadataUpdated||0)} details refreshed</span><span>{Number(x.failed||0)} failures</span></div>}</div>})}{(!rosterRuns||rosterRuns.length===0)&&<div className="rounded border border-white/10 bg-black/20 p-3 text-xs" style={{color:'var(--text-muted)'}}>No roster automation history yet. The scheduler is armed; you can also run the first guarded reconciliation now.</div>}</div></div></div>

    <div className="flex items-start gap-2 text-xs rounded border border-white/10 bg-black/20 p-3" style={{color:'var(--text-muted)'}}><CheckCircle2 size={15} className="text-emerald-300 mt-0.5 shrink-0"/><span>Schedules and scores only change when Schedule Intelligence already classifies the row as safe. Daily roster automation only adds or refreshes people when Arbiter returns the same roster or a safe superset; any apparent removal, replacement, duplicate-name roster, ambiguous match or suspicious expansion is withheld for admin review. Manual roster runs use the exact same guarded production pathway as the daily scheduler.</span></div>
  </div>
}
