'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { useState } from 'react'
import { AlertTriangle, Bell, CheckCircle2, ChevronDown, ChevronRight, Clock3, ExternalLink, Play, RefreshCw, ShieldCheck, Users } from 'lucide-react'

function statusTone(status:string){if(status==='completed')return{label:'Healthy',className:'text-emerald-300',dot:'bg-emerald-400'};if(status==='running')return{label:'Running',className:'text-sky-300',dot:'bg-sky-400'};if(status==='completed-with-errors')return{label:'Completed with errors',className:'text-amber-300',dot:'bg-amber-400'};return{label:'Failed',className:'text-red-300',dot:'bg-red-400'}}
function fmt(value:string|null|undefined){if(!value)return'—';return new Date(value).toLocaleString('en-US',{timeZone:'America/New_York',month:'numeric',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
function hoursSince(value:string|null|undefined){if(!value)return Number.POSITIVE_INFINITY;return Math.max(0,(Date.now()-new Date(value).getTime())/3_600_000)}
function pretty(value:unknown){return String(value??'').replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}
function clean(value:unknown){return String(value??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function triageOf(q:any){if(q?.triage)return q.triage;const severity=clean(q?.severity),bucket=clean(q?.bucket||q?.reason);if(severity==='blocker'||severity==='review')return'attention';if(bucket==='manual review'||bucket==='roster missing')return'waiting';if(bucket==='event sport'||bucket==='source cancelled')return'informational';return severity==='info'?'informational':'attention'}
function bucketSummary(items:any[]){const counts=new Map<string,number>();for(const item of items){const label=pretty(item?.bucket||item?.kind||'Informational');counts.set(label,(counts.get(label)||0)+1)}return Array.from(counts.entries()).sort((a,b)=>b[1]-a[1])}
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))

function PatchList({patch}:{patch:any}){
  const entries=Object.entries(patch||{}).filter(([key])=>key!=='updated_at')
  if(!entries.length)return <span className="text-slate-500">Stable link refreshed; no visible game field changed.</span>
  return <div className="flex flex-wrap gap-1.5 mt-1">{entries.map(([key,value])=><span key={key} className="rounded bg-white/[.05] px-2 py-1 text-[11px] text-slate-300"><b>{pretty(key)}:</b> {String(value??'—')}</span>)}</div>
}

function ScheduleRunDetails({run,health,gameLabels}:{run:any;health:any;gameLabels:Record<string,string>}){
  const s=run.summary||{},schedule=s.schedule||{},scores=s.scores||{}
  const scheduleActions=schedule.actions||[],scoreActions=scores.actions||[],quarantines=health?.quarantines||[]
  const attention=quarantines.filter((q:any)=>triageOf(q)==='attention'),waiting=quarantines.filter((q:any)=>triageOf(q)==='waiting'),informational=quarantines.filter((q:any)=>triageOf(q)==='informational')
  const applied=[...scheduleActions.filter((x:any)=>x.action!=='failed'),...scoreActions.filter((x:any)=>x.outcome==='updated')]
  const failures=[...scheduleActions.filter((x:any)=>x.action==='failed'),...scoreActions.filter((x:any)=>x.outcome==='failed')]
  return <div className="border-t border-white/[.07] mt-3 pt-3 space-y-4">
    <div><div className="text-[10px] font-black uppercase tracking-wider text-emerald-300 mb-2">Applied changes · {applied.length}</div>{applied.length===0?<div className="text-xs text-slate-500">No schedule or score writes were required on this run.</div>:<div className="space-y-2">{applied.map((a:any,i:number)=>{const gameId=a.gameId;return <div key={`${gameId||a.arbiterGameId}-${i}`} className="rounded border border-emerald-500/10 bg-emerald-500/[.035] p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-white">{gameLabels[gameId]||`Arbiter game ${a.arbiterGameId||'—'}`}</b>{gameId&&<Link href={`/admin/game-center/${gameId}`} className="inline-flex items-center gap-1 text-sky-300">Open game <ExternalLink size={11}/></Link>}</div><div className="mt-1 text-emerald-300">{a.outcome==='updated'?'Final score applied':pretty(a.action||'updated')}</div>{a.score&&<div className="mt-1 text-slate-300">Score: {a.score}</div>}<PatchList patch={a.patch}/>{Array.isArray(a.driftReasons)&&a.driftReasons.length>0&&<div className="mt-1 text-slate-500">Detected: {a.driftReasons.map(pretty).join(', ')}</div>}</div>})}</div>}</div>
    <div><div className={`text-[10px] font-black uppercase tracking-wider mb-2 ${attention.length?'text-amber-300':'text-emerald-300'}`}>Needs your attention · {attention.length}</div>{attention.length===0?<div className="text-xs text-slate-500">Nothing in this run requires a manual schedule decision.</div>:<div className="space-y-2">{attention.map((q:any,i:number)=><div key={i} className="rounded border border-amber-500/20 bg-amber-500/[.05] p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-white">{q.title||q.teamName||q.gameName||`Exception ${i+1}`}</b><span className="text-amber-300">{pretty(q.bucket||q.reason||q.kind||'Review')}</span></div>{q.detail&&<div className="mt-1 text-slate-400">{q.detail}</div>}{q.arbiterGameId&&<div className="mt-1 text-slate-500">Arbiter game: {q.arbiterGameId}</div>}{q.gameId&&<Link href={`/admin/game-center/${q.gameId}`} className="mt-1 inline-flex items-center gap-1 text-sky-300">Open game <ExternalLink size={11}/></Link>}</div>)}</div>}</div>
    {waiting.length>0&&<div><div className="text-[10px] font-black uppercase tracking-wider text-sky-300 mb-2">Waiting on Arbiter / school · {waiting.length}</div><div className="text-xs text-slate-500 mb-2">No action required. These stay protected until Arbiter supplies a real opponent, time, or current roster.</div><div className="space-y-2">{waiting.slice(0,20).map((q:any,i:number)=><div key={i} className="rounded border border-sky-500/10 bg-sky-500/[.035] p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-white">{q.title||q.teamName||q.gameName||`Waiting item ${i+1}`}</b><span className="text-sky-300">{pretty(q.bucket||q.reason||q.kind||'Waiting')}</span></div>{q.detail&&<div className="mt-1 text-slate-400">{q.detail}</div>}{q.arbiterGameId&&<div className="mt-1 text-slate-500">Arbiter game: {q.arbiterGameId}</div>}</div>)}</div>{waiting.length>20&&<div className="mt-2 text-[11px] text-slate-500">+{waiting.length-20} more waiting items hidden to keep this operational view clean.</div>}</div>}
    {informational.length>0&&<div><div className="text-[10px] font-black uppercase tracking-wider text-slate-400 mb-2">Protected / informational · {informational.length}</div><div className="text-xs text-slate-500 mb-2">Tracked for audit history, but not a job for you.</div><div className="flex flex-wrap gap-2">{bucketSummary(informational).map(([label,count])=><span key={label} className="rounded border border-white/[.07] bg-white/[.03] px-2 py-1 text-[11px] text-slate-400">{label} · {count}</span>)}</div></div>}
    {failures.length>0&&<div><div className="text-[10px] font-black uppercase tracking-wider text-red-300 mb-2">Write failures · {failures.length}</div><div className="space-y-2">{failures.map((f:any,i:number)=><div key={i} className="rounded border border-red-500/20 bg-red-500/[.05] p-3 text-xs text-red-200">{f.error||'Unknown write failure'}{f.gameId&&<Link href={`/admin/game-center/${f.gameId}`} className="ml-2 text-sky-300">Open game</Link>}</div>)}</div></div>}
    <div className="flex flex-wrap gap-3 text-[11px] text-slate-500"><span>{Number(schedule.updated||0)} updated</span><span>{Number(schedule.created||0)} created</span><span>{Number(schedule.deletedMarked||0)} cancelled</span><span>{attention.length} need attention</span><span>{waiting.length} waiting</span><span>{informational.length} informational</span><span>{Number(scores.updated||0)} scores</span><span>{Number(schedule.failed||0)+Number(scores.failed||0)} failures</span></div>
  </div>
}

function RosterRunDetails({run,teamLabels}:{run:any;teamLabels:Record<string,string>}){
  const x=run.summary||{},actions=x.actions||[],quarantines=x.quarantines||[],failures=x.failures||[]
  return <div className="border-t border-white/[.07] mt-3 pt-3 space-y-4">
    <div><div className="text-[10px] font-black uppercase tracking-wider text-emerald-300 mb-2">Reconciled teams · {actions.length}</div>{actions.length===0?<div className="text-xs text-slate-500">No roster writes were required on this run.</div>:<div className="space-y-2">{actions.map((a:any,i:number)=><div key={`${a.teamId}-${i}`} className="rounded border border-emerald-500/10 bg-emerald-500/[.035] p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-white">{teamLabels[a.teamId]||a.teamId}</b><Link href="/admin/roster-audit" className="inline-flex items-center gap-1 text-sky-300">Roster audit <ExternalLink size={11}/></Link></div>{a.roster&&<div className="mt-2 text-slate-300">Players: +{Number(a.roster.added||0)} added · {Number(a.roster.metadataUpdated||0)} details refreshed · {Number(a.roster.newCount||0)} total</div>}{a.coaches&&<div className="mt-1 text-slate-300">Coaches: +{Number(a.coaches.added||0)} added · {Number(a.coaches.metadataUpdated||0)} details refreshed · {Number(a.coaches.newCount||0)} total</div>}</div>)}</div>}</div>
    <div><div className="text-[10px] font-black uppercase tracking-wider text-sky-300 mb-2">Safely withheld · {quarantines.length}</div>{quarantines.length===0?<div className="text-xs text-slate-500">No roster changes were withheld on this run.</div>:<div><div className="text-xs text-slate-500 mb-2">Protection is working. A held roster is not published until its current-season evidence is safe.</div><div className="space-y-2">{quarantines.map((q:any,i:number)=><div key={`${q.teamId}-${q.area}-${i}`} className="rounded border border-sky-500/10 bg-sky-500/[.035] p-3 text-xs"><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-white">{teamLabels[q.teamId]||q.teamId}</b><span className="text-sky-300">{pretty(q.area)} · {pretty(q.reason)}</span></div><div className="mt-1 text-slate-400">Stored {Number(q.currentCount||0)} → incoming {Number(q.incomingCount||0)}</div>{q.removed?.length>0&&<div className="mt-1 text-slate-500">Would remove: {q.removed.join(', ')}</div>}{q.duplicates?.length>0&&<div className="mt-1 text-slate-500">Duplicates: {q.duplicates.join(', ')}</div>}</div>)}</div></div>}</div>
    {failures.length>0&&<div><div className="text-[10px] font-black uppercase tracking-wider text-red-300 mb-2">Failures · {failures.length}</div><div className="space-y-2">{failures.map((f:any,i:number)=><div key={i} className="rounded border border-red-500/20 bg-red-500/[.05] p-3 text-xs text-red-200"><b>{teamLabels[f.teamId]||f.teamId||'Roster worker'}:</b> {f.message||f.error||String(f)}</div>)}</div></div>}
    <div className="flex flex-wrap gap-3 text-[11px] text-slate-500"><span>{Number(x.scanned||0)} scanned</span><span>{Number(x.teamsUpdated||0)} reconciled</span><span>{Number(x.athletesAdded||0)} athletes added</span><span>{Number(x.athleteMetadataUpdated||0)} player details refreshed</span><span>{Number(x.coachMetadataUpdated||0)} coach details refreshed</span><span>{Number(x.quarantined||0)} safely held</span></div>
  </div>
}

export default function AutomationPanel({runs,cron,rosterRuns,rosterCron,healthByRunId,gameLabels,teamLabels,alertSummary}:{runs:any[];cron:any|null;rosterRuns:any[];rosterCron:any|null;healthByRunId:Record<string,any>;gameLabels:Record<string,string>;teamLabels:Record<string,string>;alertSummary:any}){
  const router=useRouter(),[runningNow,setRunningNow]=useState(false),[runMessage,setRunMessage]=useState(''),[liveProgress,setLiveProgress]=useState<any>(null),[openSchedule,setOpenSchedule]=useState<string|null>(null),[openRoster,setOpenRoster]=useState<string|null>(null)
  const latest=runs?.[0]||null,rosterLatest=rosterRuns?.[0]||null,s=latest?.summary||{},rs=rosterLatest?.summary||{},schedule=s.schedule||{},scores=s.scores||{},changed=Number(schedule.updated||0)+Number(schedule.created||0)+Number(schedule.deletedMarked||0)+Number(scores.updated||0),enabled=Boolean(cron?.active),rosterEnabled=Boolean(rosterCron?.active)
  const latestHealth=latest?.id?healthByRunId[latest.id]:null,latestExceptions=latestHealth?.quarantines||[],scheduleAttention=latestExceptions.filter((q:any)=>triageOf(q)==='attention').length,scheduleWaiting=latestExceptions.filter((q:any)=>triageOf(q)==='waiting').length
  const progress=liveProgress||rs.progress||{},processed=Number(progress.processed||0),total=Number(progress.total||0),pct=total>0?Math.min(100,Math.round(processed/total*100)):0
  const scheduleStale=Boolean(latest)&&hoursSince(latest?.finished_at||latest?.started_at)>8,rosterAwaitingFirst=rosterEnabled&&!rosterLatest,rosterHeartbeat=progress.heartbeatAt||rosterLatest?.finished_at||rosterLatest?.started_at,rosterStale=Boolean(rosterLatest)&&rosterLatest?.status==='running'?hoursSince(rosterHeartbeat)>.25:Boolean(rosterLatest)&&hoursSince(rosterHeartbeat)>30
  const scheduleHardProblem=!enabled||!latest||scheduleStale||latest?.status==='failed'||Number(schedule.failed||0)>0||Number(scores.failed||0)>0||Number(schedule.blockers||0)>0
  const rosterHardProblem=!rosterEnabled||rosterStale||rosterLatest?.status==='failed'||Number(rs.failed||0)>0
  const scheduleReview=scheduleAttention>0,rosterReview=rosterLatest?.status==='completed-with-errors'||Number(rs.scanWarnings?.ambiguous||0)>0||Number(rs.scanWarnings?.apiErrors||0)>0
  const overall=scheduleHardProblem||rosterHardProblem?{label:'Automation needs attention',className:'text-red-300',border:'border-red-500/30 bg-red-500/10'}:rosterAwaitingFirst?{label:'Automation active · first roster run pending',className:'text-amber-300',border:'border-amber-500/30 bg-amber-500/10'}:scheduleReview||rosterReview?{label:'Automation healthy · action items waiting',className:'text-amber-300',border:'border-amber-500/30 bg-amber-500/10'}:{label:'Automation healthy',className:'text-emerald-300',border:'border-emerald-500/30 bg-emerald-500/10'}

  async function runRosterNow(){if(runningNow)return;setRunningNow(true);setLiveProgress(null);setRunMessage('Requesting guarded roster reconciliation…');const startedMs=Date.now();try{const response=await fetch('/api/admin/arbiter-api/roster-automation',{method:'POST',cache:'no-store'}),body=await response.json();if(!response.ok&&response.status!==409)throw new Error(body?.error||`Request failed (${response.status})`);setRunMessage(response.status===409?'A roster run is already active. Following its progress…':'Roster automation queued. Waiting for the first batch…');for(let i=0;i<180;i++){await sleep(3000);const r=await fetch('/api/admin/arbiter-api/roster-automation',{cache:'no-store'}),j=await r.json();if(!r.ok)continue;const candidate=(j?.runs||[]).find((run:any)=>run.status==='running'||new Date(run.started_at).getTime()>=startedMs-20000)||(j?.runs||[])[0];if(!candidate)continue;const p=candidate.summary?.progress||{};setLiveProgress(p);if(candidate.status==='running'){setRunMessage(`Roster reconciliation: ${Number(p.processed||0)}/${Number(p.total||0)} teams complete…`);continue}setRunMessage(candidate.status==='completed'?`Completed: ${Number(candidate.summary?.scanned||0)} scanned, ${Number(candidate.summary?.teamsUpdated||0)} reconciled.`:`Roster automation ${candidate.status}. Open the newest run below for details.`);router.refresh();return}setRunMessage('Roster worker is still active server-side. Refresh for the newest heartbeat.');router.refresh()}catch(error){setRunMessage(error instanceof Error?error.message:'Could not start roster automation.')}finally{setRunningNow(false)}}

  return <div className="card p-4 space-y-5">
    <div className="flex flex-col lg:flex-row lg:items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><ShieldCheck size={20} className={!scheduleHardProblem&&!rosterHardProblem?'text-emerald-300':'text-amber-300'}/><h2 className="font-semibold text-white">Arbiter Automation</h2><span className={`text-[10px] px-2 py-1 rounded-full border ${enabled?'text-emerald-300 border-emerald-500/30 bg-emerald-500/10':'text-amber-300 border-amber-500/30 bg-amber-500/10'}`}>SCHEDULE {enabled?'ACTIVE':'INACTIVE'}</span><span className={`text-[10px] px-2 py-1 rounded-full border ${rosterEnabled?'text-emerald-300 border-emerald-500/30 bg-emerald-500/10':'text-amber-300 border-amber-500/30 bg-amber-500/10'}`}>ROSTERS {rosterEnabled?'ACTIVE':'INACTIVE'}</span></div><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Automatic writes are separated from items that truly need you, items waiting on Arbiter, and protected audit-only observations.</p></div><div className="text-xs lg:text-right" style={{color:'var(--text-muted)'}}><div>Schedules + scores: 5 checks daily</div><div>Rosters: 1 guarded batched reconciliation daily</div></div></div>
    <div className={`rounded-lg border p-3 ${overall.border}`}><div className="flex items-start gap-2">{scheduleHardProblem||rosterHardProblem?<AlertTriangle size={16} className="mt-0.5 text-red-300"/>:<CheckCircle2 size={16} className="mt-0.5 text-emerald-300"/>}<div><b className={overall.className}>{overall.label}</b><div className="text-xs mt-1" style={{color:'var(--text-muted)'}}>{scheduleStale?'Schedule automation is stale. ':''}{rosterStale?'Roster worker heartbeat is stale. ':''}{rosterAwaitingFirst?'Roster scheduler is waiting for its first run. ':''}{scheduleAttention>0?`${scheduleAttention} schedule item${scheduleAttention===1?'':'s'} actually need your attention. `:''}{scheduleWaiting>0?`${scheduleWaiting} item${scheduleWaiting===1?' is':'s are'} safely waiting on Arbiter or a school. `:''}{Number(rs.quarantined||0)>0?`${Number(rs.quarantined||0)} roster change${Number(rs.quarantined||0)===1?' is':'s are'} safely withheld. `:''}{!scheduleHardProblem&&!rosterHardProblem&&!rosterAwaitingFirst&&!scheduleReview&&!rosterReview?'No automation failures or unresolved action items detected.':''}</div></div></div></div>

    <div className="grid lg:grid-cols-2 gap-4"><div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex items-center justify-between gap-3 mb-3"><b className="text-white">Schedules & scores</b><span className="text-xs text-slate-500">{fmt(latest?.started_at)}</span></div><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(schedule.stableLinks||0)}</b><div className="text-slate-500">Stable links checked</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{changed}</b><div className="text-slate-500">Changes applied</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(scores.updated||0)}</b><div className="text-slate-500">Scores applied</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(schedule.failed||0)+Number(scores.failed||0)}</b><div className="text-slate-500">Write failures</div></div></div></div>
    <div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex flex-wrap items-center justify-between gap-3 mb-3"><b className="text-white">Roster intelligence</b><button type="button" onClick={runRosterNow} disabled={runningNow||!rosterEnabled} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40 hover:bg-white/5"><Play size={13}/>{runningNow?'Following run…':'Run Roster Automation Now'}</button></div>{runMessage&&<div className="mb-3 rounded border border-sky-500/20 bg-sky-500/10 p-2 text-xs text-sky-200">{runMessage}</div>}{rosterLatest?.status==='running'&&total>0&&<div className="mb-3"><div className="flex justify-between text-xs text-slate-500 mb-1"><span>Progress</span><span>{processed}/{total} · {pct}%</span></div><div className="h-2 rounded-full bg-black/40 overflow-hidden"><div className="h-full bg-sky-400" style={{width:`${pct}%`}}/></div></div>}<div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.scanned||0)}</b><div className="text-slate-500">Varsity teams scanned</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.teamsUpdated||0)}</b><div className="text-slate-500">Teams reconciled</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{Number(rs.athletesAdded||0)}</b><div className="text-slate-500">Athletes added</div></div><div className="rounded bg-black/20 p-3"><b className={Number(rs.quarantined||0)?'text-sky-300':'text-white'}>{Number(rs.quarantined||0)}</b><div className="text-slate-500">Safely withheld</div></div></div></div></div>

    <div className="rounded-lg border border-white/10 bg-black/20 p-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div className="flex items-center gap-2"><Bell size={17} className={Number(alertSummary?.error||0)||Number(alertSummary?.deliveriesError||0)?'text-red-300':'text-emerald-300'}/><div><b className="text-white">Fan Alert Delivery Health</b><div className="text-xs text-slate-500">Queue → Resend → follower inbox audit.</div></div></div><Link href="/admin/notifications" className="inline-flex items-center gap-1 text-xs font-semibold text-sky-300">Open Notification Health <ExternalLink size={11}/></Link></div><div className="grid grid-cols-2 md:grid-cols-6 gap-2 mt-3 text-sm">{[[alertSummary?.pending||0,'Pending'],[alertSummary?.sent||0,'Events sent'],[alertSummary?.skipped||0,'Skipped'],[alertSummary?.error||0,'Event errors'],[alertSummary?.deliveriesSent||0,'Deliveries sent'],[alertSummary?.deliveriesError||0,'Delivery errors']].map(([n,label])=><div key={String(label)} className="rounded bg-black/20 p-3"><b className={String(label).includes('error')&&Number(n)>0?'text-red-300':'text-white'}>{n}</b><div className="text-xs text-slate-500">{label}</div></div>)}</div><div className="mt-2 text-[11px] text-slate-500">Latest event: {fmt(alertSummary?.latestEvent?.created_at)} · latest delivery: {fmt(alertSummary?.latestDelivery?.sent_at||alertSummary?.latestDelivery?.created_at)}</div></div>

    <div className="grid lg:grid-cols-2 gap-4">
      <div><div className="flex items-center gap-2 mb-2"><Clock3 size={16}/><h3 className="text-sm font-semibold text-white">Schedule automation history</h3><span className="text-[11px] text-slate-500">Click a run to inspect it</span></div><div className="space-y-2">{(runs||[]).slice(0,8).map((run:any)=>{const t=statusTone(run.status),x=run.summary||{},sch=x.schedule||{},sc=x.scores||{},changes=Number(sch.updated||0)+Number(sch.created||0)+Number(sch.deletedMarked||0)+Number(sc.updated||0),open=openSchedule===run.id,health=healthByRunId[run.id],attention=(health?.quarantines||[]).filter((q:any)=>triageOf(q)==='attention').length,waiting=(health?.quarantines||[]).filter((q:any)=>triageOf(q)==='waiting').length;return <div key={run.id} className="rounded border border-white/10 bg-black/20 p-3 text-xs"><button type="button" onClick={()=>setOpenSchedule(open?null:run.id)} className="w-full flex items-center justify-between gap-2 text-left"><div className="flex flex-wrap items-center gap-2">{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<span className={`w-2 h-2 rounded-full ${t.dot}`}/><b className={t.className}>{t.label}</b><span className="text-slate-500">{fmt(run.started_at)}</span></div><span className={attention?'text-amber-300':'text-slate-500'}>{changes} changes · {attention} attention{waiting?` · ${waiting} waiting`:''}</span></button>{open&&<ScheduleRunDetails run={run} health={health} gameLabels={gameLabels}/>}</div>})}</div></div>
      <div><div className="flex items-center gap-2 mb-2"><Users size={16}/><h3 className="text-sm font-semibold text-white">Roster automation history</h3><span className="text-[11px] text-slate-500">Click a run to inspect it</span></div><div className="space-y-2">{(rosterRuns||[]).slice(0,8).map((run:any)=>{const t=statusTone(run.status),x=run.summary||{},open=openRoster===run.id;return <div key={run.id} className="rounded border border-white/10 bg-black/20 p-3 text-xs"><button type="button" onClick={()=>setOpenRoster(open?null:run.id)} className="w-full flex items-center justify-between gap-2 text-left"><div className="flex flex-wrap items-center gap-2">{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<span className={`w-2 h-2 rounded-full ${t.dot}`}/><b className={t.className}>{t.label}</b><span className="text-slate-500">{fmt(run.started_at)}</span></div><span className="text-slate-500">{Number(x.scanned||0)} scanned · {Number(x.teamsUpdated||0)} changed · {Number(x.quarantined||0)} safely held</span></button>{open&&<RosterRunDetails run={run} teamLabels={teamLabels}/>}</div>})}</div></div>
    </div>
    <div className="rounded-lg border border-white/[.07] bg-black/20 p-3 text-xs text-slate-500">Audit rule: failed historical runs stay visible. A healthy later run does not erase evidence of an earlier failure; it proves the system recovered.</div>
  </div>
}