'use client'

import { useEffect,useState } from 'react'
import Link from 'next/link'
import { Activity,AlertTriangle,CheckCircle2,RefreshCw,ShieldCheck,Users,Upload,BarChart2 } from 'lucide-react'

function readable(v:string){return String(v||'').replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase())}

export default function FallOperations({season}:{season:any}){
  const [data,setData]=useState<any>(null),[rosterScan,setRosterScan]=useState<any>(null),[loading,setLoading]=useState(false),[scanning,setScanning]=useState(false),[scoreSyncing,setScoreSyncing]=useState(false),[rosterSyncing,setRosterSyncing]=useState(false),[error,setError]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null)
  const seasonId=season?.id
  async function check(){if(!seasonId)return;setLoading(true);setError(null);try{const r=await fetch(`/api/admin/arbiter-api/live-ops?seasonId=${encodeURIComponent(seasonId)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Live Operations check failed');setData(j)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  async function scanRosters(){if(!seasonId)return;setScanning(true);setError(null);setMessage(null);try{const r=await fetch(`/api/admin/arbiter-api/roster-scan?seasonId=${encodeURIComponent(seasonId)}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Roster scan failed');setRosterScan(j)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setScanning(false)}}
  async function syncScores(){if(!data?.scores?.safeToApply)return;if(!confirm(`Apply ${data.scores.safeToApply} safe Arbiter final score${data.scores.safeToApply===1?'':'s'}? Manual score conflicts will remain untouched.`))return;setScoreSyncing(true);setError(null);setMessage(null);try{const r=await fetch('/api/admin/arbiter-api/score-sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm:'APPLY_ARBITER_SCORE_SYNC',seasonId})}),j=await r.json();if(!r.ok&&r.status!==207)throw new Error(j.error||'Score sync failed');setMessage(`Score sync complete: ${j.updated} updated, ${j.failed} failed, ${j.conflictsUntouched} conflicts untouched.`);await check()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setScoreSyncing(false)}}
  async function importRosters(){const payloads=rosterScan?.importPayloads||[];if(!payloads.length)return;if(!confirm(`Import/reconcile ${payloads.length} published Arbiter team roster payload${payloads.length===1?'':'s'}? Existing good rosters are protected if a team import fails.`))return;setRosterSyncing(true);setError(null);setMessage(null);try{const r=await fetch('/api/admin/arbiter-rosters',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({teams:payloads})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Roster import failed');setMessage('Roster import completed. Re-running current-season health now.');await check();await scanRosters()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setRosterSyncing(false)}}
  useEffect(()=>{void check()},[seasonId])
  const healthy=data&&data.schedule.pendingChanges===0&&data.schedule.blockers===0&&data.scores.conflicts===0
  return <div className="p-4 max-w-6xl space-y-5">
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Activity size={24} style={{color:'var(--accent-bright)'}}/><h1 className="text-2xl font-bold text-white" style={{fontFamily:'var(--font-display)'}}>Fall Operations Center</h1></div><p className="text-sm mt-1" style={{color:'var(--text-secondary)'}}>Live-season command center for schedules, scores, rosters and Arbiter exceptions.</p></div><button onClick={check} disabled={loading} className="admin-action-btn justify-center md:min-w-[190px] disabled:opacity-40"><RefreshCw size={18} className={loading?'animate-spin':''}/>{loading?'Checking everything…':'Run Full Live Check'}</button></div>
    <div className="card p-4 flex flex-wrap gap-x-6 gap-y-2 text-sm"><div><span style={{color:'var(--text-muted)'}}>Active season</span><div className="font-semibold text-white">{season?.name||'—'}</div></div>{data&&<><div><span style={{color:'var(--text-muted)'}}>Last checked</span><div className="text-white">{new Date(data.checkedAt).toLocaleString()}</div></div><div className={`font-semibold ${healthy?'text-emerald-400':'text-amber-300'}`}>{healthy?'Live operations healthy':'Review items detected'}</div></>}</div>
    {error&&<div className="rounded-lg p-3 border border-red-500/30 bg-red-500/10 text-red-300 text-sm"><AlertTriangle size={16} className="inline mr-2"/>{error}</div>}
    {message&&<div className="rounded-lg p-3 border border-emerald-500/30 bg-emerald-500/10 text-emerald-300 text-sm"><CheckCircle2 size={16} className="inline mr-2"/>{message}</div>}
    {data&&<>
      <div className="grid md:grid-cols-4 gap-3">
        <div className="card p-4"><ShieldCheck className="mb-2"/><div className="text-xl font-bold text-white">{data.schedule.syncedStable}</div><div className="text-sm text-white">Stable schedule links</div><div className="text-xs mt-2" style={{color:'var(--text-muted)'}}>{data.schedule.pendingChanges} pending · {data.schedule.blockers} blockers</div></div>
        <div className="card p-4"><BarChart2 className="mb-2"/><div className="text-xl font-bold text-white">{data.scores.safeToApply}</div><div className="text-sm text-white">Safe scores ready</div><div className="text-xs mt-2" style={{color:'var(--text-muted)'}}>{data.scores.counts?.['score-synced']||0} synced · {data.scores.conflicts} conflicts</div></div>
        <div className="card p-4"><Users className="mb-2"/><div className="text-xl font-bold text-white">{data.rosters.loaded}/{data.rosters.varsityTeams}</div><div className="text-sm text-white">Varsity rosters loaded</div><div className="text-xs mt-2" style={{color:'var(--text-muted)'}}>{data.rosters.missing} missing in Section X</div></div>
        <div className="card p-4"><AlertTriangle className="mb-2"/><div className="text-xl font-bold text-white">{data.exceptions.length}</div><div className="text-sm text-white">Data exceptions</div><div className="text-xs mt-2" style={{color:'var(--text-muted)'}}>Known quarantines + conflicts + missing rosters</div></div>
      </div>
      <div className="grid md:grid-cols-2 gap-3">
        <div className="card p-4 space-y-3"><div><h2 className="font-semibold text-white">Schedule Operations</h2><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Arbiter stable identity remains the schedule authority layer.</p></div><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{data.schedule.pendingChanges}</b><div style={{color:'var(--text-muted)'}}>Changes pending</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{data.schedule.quarantined}</b><div style={{color:'var(--text-muted)'}}>Quarantined</div></div></div><Link href="/admin/schedule-intelligence" className="admin-action-btn justify-center">Open Schedule Intelligence →</Link></div>
        <div className="card p-4 space-y-3"><div><h2 className="font-semibold text-white">Score Intelligence</h2><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Only confirmed Arbiter finals with no protected manual conflict are eligible.</p></div><div className="grid grid-cols-3 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{data.scores.counts?.['score-fill']||0}</b><div style={{color:'var(--text-muted)'}}>Blank fills</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{data.scores.counts?.['score-update']||0}</b><div style={{color:'var(--text-muted)'}}>Arbiter updates</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{data.scores.conflicts}</b><div style={{color:'var(--text-muted)'}}>Manual conflicts</div></div></div><button onClick={syncScores} disabled={!data.scores.safeToApply||scoreSyncing} className="admin-action-btn justify-center w-full disabled:opacity-40">{scoreSyncing?<RefreshCw size={18} className="animate-spin"/>:<Upload size={18}/>} {scoreSyncing?'Applying scores…':`Apply ${data.scores.safeToApply} Safe Scores`}</button></div>
      </div>
      <div className="card p-4 space-y-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-3"><div><h2 className="font-semibold text-white">Roster Intelligence</h2><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Scan Arbiter Partner API for published current-season varsity rosters, then reconcile through the existing protected roster importer.</p></div><button onClick={scanRosters} disabled={scanning||rosterSyncing} className="admin-action-btn justify-center md:min-w-[190px] disabled:opacity-40"><RefreshCw size={18} className={scanning?'animate-spin':''}/>{scanning?'Scanning Arbiter…':'Scan Arbiter Rosters'}</button></div>{rosterScan&&<><div className="grid grid-cols-2 md:grid-cols-5 gap-2 text-sm"><div className="rounded bg-black/20 p-3"><b className="text-white">{rosterScan.counts.available}</b><div style={{color:'var(--text-muted)'}}>Published</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{rosterScan.counts.noRosterPublished}</b><div style={{color:'var(--text-muted)'}}>Not published</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{rosterScan.counts.teamNotFound}</b><div style={{color:'var(--text-muted)'}}>Team not matched</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{rosterScan.counts.ambiguous}</b><div style={{color:'var(--text-muted)'}}>Ambiguous</div></div><div className="rounded bg-black/20 p-3"><b className="text-white">{rosterScan.counts.alreadyLoaded}</b><div style={{color:'var(--text-muted)'}}>Already loaded</div></div></div><button onClick={importRosters} disabled={!rosterScan.importPayloads?.length||rosterSyncing} className="admin-action-btn justify-center w-full disabled:opacity-40">{rosterSyncing?<RefreshCw size={18} className="animate-spin"/>:<Upload size={18}/>} {rosterSyncing?'Reconciling rosters…':`Import/Reconcile ${rosterScan.importPayloads?.length||0} Published Rosters`}</button><div className="max-h-80 overflow-auto space-y-2">{rosterScan.rows.map((r:any)=><div key={r.teamId} className="rounded border border-white/10 bg-black/20 p-3 text-sm flex justify-between gap-3"><div><b className="text-white">{r.teamName}</b><div className="text-xs" style={{color:'var(--text-muted)'}}>{r.school} · {r.sport}{r.gender?` · ${r.gender}`:''}</div></div><div className="text-right"><div className={r.status==='available'?'text-emerald-300':r.status==='ambiguous-team-match'||r.status==='error'?'text-amber-300':'text-slate-300'}>{readable(r.status)}</div><div className="text-xs" style={{color:'var(--text-muted)'}}>{r.rosterFound?`${r.rosterCount} players`:''}</div></div></div>)}</div></>}</div>
      <div className="card p-4"><div className="flex items-center justify-between gap-3 mb-3"><div><h2 className="font-semibold text-white">Exception Review</h2><p className="text-xs mt-1" style={{color:'var(--text-muted)'}}>Nothing here is auto-written.</p></div><Link href="/admin/roster-audit" className="text-sm" style={{color:'var(--accent-bright)'}}>Roster Audit →</Link></div><div className="max-h-96 overflow-auto space-y-2">{data.exceptions.length===0?<div className="text-emerald-300 text-sm">No current exceptions.</div>:data.exceptions.map((x:any,i:number)=><div key={`${x.kind}-${x.arbiterGameId||x.title}-${i}`} className="rounded border border-white/10 bg-black/20 p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-white">{x.title}</b><span className={`text-xs ${x.severity==='blocker'?'text-red-300':x.severity==='review'?'text-amber-300':'text-slate-300'}`}>{readable(x.kind)} · {readable(x.bucket)}</span></div>{x.detail&&<div className="text-xs mt-1" style={{color:'var(--text-muted)'}}>{x.detail}</div>}</div>)}</div></div>
    </>}
  </div>
}
