import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import PublicLayout from '@/components/layout/PublicLayout'
import { calculateStandings } from '@/lib/standings'
import { getSportsRepository } from '@/lib/data/runtime-sports-repository'
import { getPublicContentRepository } from '@/lib/data/runtime-public-content-repository'

export const dynamic = 'force-dynamic'
type Props={params:Promise<{slug:string}>}

function formatTime(t:string|null){if(!t)return'TBD';try{const[h,m]=String(t).split(':').map(Number);if(Number.isNaN(h)||Number.isNaN(m))return t;const isPM=h<8||h>=12;return`${h%12||12}:${String(m).padStart(2,'0')} ${isPM?'PM':'AM'}`}catch{return t}}
function labelSport(s:any){if(!s)return'Sport';const n=String(s.sport_name||''),g=String(s.gender||'');return(g==='Boys'||g==='Girls')&&!n.toLowerCase().startsWith(g.toLowerCase())?`${g} ${n}`:n}

export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const team=await getSportsRepository().getTeamBySlug(slug);if(!team)return{};return{title:`${team.school?.school_name||''} ${labelSport(team.sport)} | Section X Scoreboard`,description:`${team.team_name} scores, schedule, and standings.`}}

export default async function TeamPage({params}:Props){
 const{slug}=await params
 const repo=getSportsRepository(),content=getPublicContentRepository()
 const team=await repo.getTeamBySlug(slug);if(!team)notFound()
 const school:any=team.school,sport:any=team.sport
 const schoolColor=school?.primary_color||'#1e3a5f',schoolColor2=school?.secondary_color||'#0f172a'
 const isGolf=String(sport?.sport_name||'').toLowerCase().includes('golf')
 const activeSeason=await repo.getActiveSeason(),teamSportId=sport?.id||team.sport_id
 const[games,teamSeason,rosterRaw,coaches,allFinals,sportTeamSeasons]=await Promise.all([
  repo.getGamesForTeam(team.id,activeSeason?.id||null),
  activeSeason?repo.getTeamSeason(team.id,activeSeason.id):Promise.resolve(null),
  activeSeason?content.getTeamRoster(team.id,activeSeason.id):Promise.resolve([]),
  activeSeason?content.getTeamCoaches(team.id,activeSeason.id):Promise.resolve([]),
  activeSeason&&teamSportId?repo.getFinalGamesForSport(teamSportId,activeSeason.id):Promise.resolve([]),
  activeSeason&&teamSportId?repo.getTeamSeasonsForSport(teamSportId,activeSeason.id):Promise.resolve([]),
 ])
 const finals=(games||[]).filter((g:any)=>g.status==='Final')
 let wins=0,losses=0,ties=0
 finals.forEach((g:any)=>{if(g.home_score==null||g.away_score==null)return;const mine=g.home_team_id===team.id?g.home_score:g.away_score,opp=g.home_team_id===team.id?g.away_score:g.home_score;if(isGolf?mine<opp:mine>opp)wins++;else if(mine===opp)ties++;else losses++})
 const upcoming=(games||[]).filter((g:any)=>g.status==='Scheduled'||g.status==='Postponed').sort((a:any,b:any)=>String(a.game_date).localeCompare(String(b.game_date)))
 const results=[...finals].sort((a:any,b:any)=>String(b.game_date).localeCompare(String(a.game_date)))
 const form=results.slice(0,5).map((g:any)=>{if(g.home_score==null||g.away_score==null)return'U';const mine=g.home_team_id===team.id?g.home_score:g.away_score,opp=g.home_team_id===team.id?g.away_score:g.home_score;if(isGolf?mine<opp:mine>opp)return'W';if(mine===opp)return'T';return'L'}).reverse()
 let standingsPosition:null|number=null,standingsTotal:null|number=null,standingsLabel:null|string=null
 if(activeSeason&&teamSportId){const standings=calculateStandings(allFinals||[],sportTeamSeasons||[],sport?.sport_name);const division=teamSeason?.division||null;const group=standings.filter((r:any)=>!division||r.division===division);const idx=group.findIndex((r:any)=>r.team_id===team.id);if(idx>=0){standingsPosition=idx+1;standingsTotal=group.length;standingsLabel=division?`${division} Div`:'Overall'}}
 const CLASS_ORDER:Record<string,number>={Senior:1,Junior:2,Sophomore:3,Freshman:4,'8th Grade':5,'7th Grade':6}
 const roster=[...(rosterRaw||[])].sort((a:any,b:any)=>{const ac=CLASS_ORDER[a.class_year||'']||99,bc=CLASS_ORDER[b.class_year||'']||99;if(ac!==bc)return ac-bc;return String(a.athlete?.display_name||'').localeCompare(String(b.athlete?.display_name||''))})
 const classCounts=roster.reduce((acc:Record<string,number>,entry:any)=>{const key=entry.class_year||'Unlisted';acc[key]=(acc[key]||0)+1;return acc},{})

 return <PublicLayout><div className="max-w-3xl mx-auto px-4 py-6">
  <div className="rounded-2xl overflow-hidden mb-6 relative" style={{background:`linear-gradient(135deg, ${schoolColor}ee 0%, ${schoolColor2}cc 100%)`}}>
   <div className="absolute inset-0 opacity-10" style={{backgroundImage:'url("data:image/svg+xml,%3Csvg viewBox=\'0 0 200 200\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cfilter id=\'n\'%3E%3CfeTurbulence type=\'fractalNoise\' baseFrequency=\'0.9\' numOctaves=\'4\'/%3E%3C/filter%3E%3Crect width=\'100%25\' height=\'100%25\' filter=\'url(%23n)\'/%3E%3C/svg%3E")',backgroundSize:'200px'}}/>
   <div className="relative px-6 pt-5 pb-6">
    <div className="flex items-center gap-1.5 text-xs text-white/50 mb-3"><Link href={`/schools/${school?.slug}`} className="hover:text-white transition-colors">{school?.school_name}</Link><span>/</span><span>{labelSport(sport)}</span></div>
    <div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl md:text-4xl font-black text-white leading-none" style={{fontFamily:'var(--font-display)',letterSpacing:'-0.01em'}}>{team.team_name}</h1>{activeSeason&&<p className="text-white/60 text-sm mt-1">{activeSeason.name}</p>}{form.length>0&&<div className="flex items-center gap-1.5 mt-3"><span className="text-white/40 text-xs mr-1">Last {form.length}:</span>{form.map((r,i)=><span key={i} className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-black" style={{background:r==='W'?'rgba(34,197,94,.3)':r==='L'?'rgba(239,68,68,.3)':'rgba(255,255,255,.15)',color:r==='W'?'#4ade80':r==='L'?'#f87171':'#94a3b8',fontFamily:'var(--font-display)'}}>{r}</span>)}</div>}</div>
     <div className="flex items-end gap-4 flex-shrink-0"><div className="text-center"><div className="text-5xl font-black text-white leading-none" style={{fontFamily:'var(--font-display)'}}>{wins}</div><div className="text-xs text-white/50 uppercase tracking-widest mt-1">W</div></div><div className="text-white/30 text-3xl mb-1">-</div><div className="text-center"><div className="text-5xl font-black text-white leading-none" style={{fontFamily:'var(--font-display)'}}>{losses}</div><div className="text-xs text-white/50 uppercase tracking-widest mt-1">L</div></div>{ties>0&&<><div className="text-white/30 text-3xl mb-1">-</div><div className="text-center"><div className="text-5xl font-black text-white leading-none" style={{fontFamily:'var(--font-display)'}}>{ties}</div><div className="text-xs text-white/50 uppercase tracking-widest mt-1">T</div></div></>}</div></div>
    <div className="flex items-center gap-2 mt-4 flex-wrap">{teamSeason?.division&&<span className="px-2.5 py-1 rounded-full text-xs font-bold text-white/70 bg-white/10">{teamSeason.division} Division</span>}{teamSeason?.class&&<span className="px-2.5 py-1 rounded-full text-xs font-bold text-white/70 bg-white/10">Class {teamSeason.class}</span>}{standingsPosition&&<span className="px-2.5 py-1 rounded-full text-xs font-bold text-yellow-400" style={{background:'rgba(234,179,8,.15)',border:'1px solid rgba(234,179,8,.25)'}}>#{standingsPosition} of {standingsTotal} · {standingsLabel}</span>}<Link href={`/standings?sport=${sport?.slug||''}`} className="px-2.5 py-1 rounded-full text-xs font-bold text-blue-400 hover:text-blue-300" style={{background:'rgba(37,99,235,.15)'}}>Full Standings →</Link></div>
   </div>
  </div>

  <div className="flex items-center gap-2 flex-wrap mb-6"><a href="#schedule" className="px-3 py-1.5 rounded-full text-xs font-black text-slate-300 hover:text-white bg-white/[.05] border border-white/[.08]">Schedule</a><a href="#roster" className="px-3 py-1.5 rounded-full text-xs font-black text-slate-300 hover:text-white bg-blue-500/10 border border-blue-400/20">Roster {roster.length?`· ${roster.length}`:''}</a><a href="#coaches" className="px-3 py-1.5 rounded-full text-xs font-black text-slate-300 hover:text-white bg-purple-500/10 border border-purple-400/20">Coaches {coaches.length?`· ${coaches.length}`:''}</a><Link href={`/standings?sport=${sport?.slug||''}`} className="px-3 py-1.5 rounded-full text-xs font-black text-slate-300 hover:text-white bg-white/[.05] border border-white/[.08]">Standings</Link><Link href={`/teams/${team.slug}/photos`} className="px-3 py-1.5 rounded-full text-xs font-black text-blue-300 bg-blue-500/10 border border-blue-400/20">Photos</Link></div>

  <section id="roster" className="mb-6 scroll-mt-24"><div className="flex items-center gap-2 mb-3"><span className="font-black text-xs text-blue-400 uppercase tracking-widest" style={{fontFamily:'var(--font-display)'}}>Roster {roster.length?`· ${roster.length}`:''}</span><div className="flex-1 h-px bg-white/5"/></div>{roster.length?<div className="rounded-2xl overflow-hidden border border-white/6" style={{background:'rgba(8,12,20,.72)'}}><div className="px-4 py-3 border-b border-white/[.05]"><div className="flex items-center gap-2 flex-wrap">{Object.entries(classCounts).map(([label,count])=><span key={label} className="text-xs rounded-full px-2.5 py-1" style={{background:'rgba(255,255,255,.05)',color:'#94a3b8',border:'1px solid rgba(255,255,255,.06)'}}>{Number(count)} {label}{Number(count)!==1?'s':''}</span>)}</div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-slate-500 border-b border-white/[.05]"><th className="text-left px-4 py-2 font-medium w-14">#</th><th className="text-left px-4 py-2 font-medium">Player</th><th className="text-left px-4 py-2 font-medium">Class</th><th className="text-left px-4 py-2 font-medium">Position</th><th className="text-left px-4 py-2 font-medium">Height</th></tr></thead><tbody>{roster.map((entry:any)=><tr key={entry.id} className="border-b border-white/[.04] last:border-0 hover:bg-white/[.025]"><td className="px-4 py-2.5 font-bold" style={{color:entry.jersey_number?'#60a5fa':'#334155',fontFamily:'var(--font-mono)'}}>{entry.jersey_number||'—'}</td><td className="px-4 py-2.5">{entry.athlete?.slug?<Link href={`/athletes/${entry.athlete.slug}`} className="font-semibold text-slate-100 hover:text-blue-400" style={{fontFamily:'var(--font-display)'}}>{entry.athlete.display_name||'Unknown Athlete'}</Link>:<span className="font-semibold text-slate-100" style={{fontFamily:'var(--font-display)'}}>{entry.athlete?.display_name||'Unknown Athlete'}</span>}</td><td className="px-4 py-2.5 text-slate-400">{entry.class_year||'—'}</td><td className="px-4 py-2.5 text-slate-400">{entry.position||'—'}</td><td className="px-4 py-2.5 text-slate-400">{entry.height||'—'}</td></tr>)}</tbody></table></div></div>:<div className="rounded-2xl p-6 text-center border border-white/6" style={{background:'rgba(8,12,20,.55)'}}><p className="text-slate-500 text-sm">Roster not published yet.</p></div>}</section>

  <section id="coaches" className="mb-6 scroll-mt-24"><div className="flex items-center gap-2 mb-3"><span className="font-black text-xs text-purple-400 uppercase tracking-widest" style={{fontFamily:'var(--font-display)'}}>Coaching Staff {coaches.length?`· ${coaches.length}`:''}</span><div className="flex-1 h-px bg-white/5"/></div>{coaches.length?<div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{coaches.map((entry:any)=><div key={entry.id} className="rounded-xl p-4" style={{background:'rgba(168,85,247,.05)',border:'1px solid rgba(168,85,247,.14)'}}><div className="font-black text-white" style={{fontFamily:'var(--font-display)'}}>{entry.coach?.display_name||'Coach'}</div><div className="text-xs text-purple-300 mt-1">{entry.title||'Coach'}</div></div>)}</div>:<div className="rounded-xl p-5 text-center" style={{background:'rgba(8,12,20,.55)',border:'1px solid rgba(255,255,255,.06)'}}><p className="text-sm text-slate-500">Coaching staff not published yet.</p></div>}</section>

  <div id="schedule" className="scroll-mt-24"/>
  {upcoming.length>0&&<div className="mb-6"><div className="flex items-center gap-2 mb-3"><span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse"/><span className="font-black text-xs text-blue-400 uppercase tracking-widest" style={{fontFamily:'var(--font-display)'}}>Upcoming · {upcoming.length}</span><div className="flex-1 h-px bg-white/5"/></div><div className="rounded-2xl overflow-hidden border border-white/6" style={{background:'rgba(8,12,20,.7)'}}>{upcoming.map((game:any)=>{const homeName=game.home_team?.school?.school_name||game.external_home?.name||'TBD',awayName=game.away_team?.school?.school_name||game.external_away?.name||'TBD',isHome=game.home_team_id===team.id,opp=isHome?awayName:homeName,timeStr=game.game_time?formatTime(game.game_time):'TBD',isPpd=game.status==='Postponed';return <Link key={game.id} href={`/game-center/${game.id}`} className="flex items-center px-4 py-3 hover:bg-white/[.03] border-b border-white/[.04] last:border-0"><div className="flex-1 min-w-0"><span className="text-xs text-slate-600 mr-2" style={{fontFamily:'var(--font-display)'}}>{isHome?'vs':'@'}</span><span className="text-sm font-semibold text-slate-200" style={{fontFamily:'var(--font-display)'}}>{opp}</span>{game.league_designation&&<span className={`ml-2 text-[9px] font-black uppercase tracking-wide ${game.league_designation==='League'?'text-emerald-300':'text-slate-500'}`}>{game.league_designation}</span>}</div><div className="text-right flex-shrink-0 ml-4"><div className="text-xs text-slate-500">{String(game.game_date||'').slice(0,10)}</div>{isPpd?<div className="text-xs font-bold text-amber-500" style={{fontFamily:'var(--font-display)'}}>PPD</div>:<div className="text-xs font-bold text-blue-400" style={{fontFamily:'var(--font-display)'}}>{timeStr}</div>}</div></Link>})}</div></div>}

  {results.length>0&&<div><div className="flex items-center gap-2 mb-3"><span className="font-black text-xs text-slate-400 uppercase tracking-widest" style={{fontFamily:'var(--font-display)'}}>Results · {results.length}</span><div className="flex-1 h-px bg-white/5"/></div><div className="rounded-2xl overflow-hidden border border-white/6" style={{background:'rgba(8,12,20,.7)'}}>{results.map((game:any)=>{const homeName=game.home_team?.school?.school_name||game.external_home?.name||'TBD',awayName=game.away_team?.school?.school_name||game.external_away?.name||'TBD',isHome=game.home_team_id===team.id,myScore=isHome?game.home_score:game.away_score,oppScore=isHome?game.away_score:game.home_score,iWon=myScore!=null&&oppScore!=null&&(isGolf?myScore<oppScore:myScore>oppScore),iLost=myScore!=null&&oppScore!=null&&(isGolf?myScore>oppScore:myScore<oppScore),homeWins=game.home_score!=null&&game.away_score!=null&&(isGolf?game.home_score<game.away_score:game.home_score>game.away_score),awayWins=game.home_score!=null&&game.away_score!=null&&(isGolf?game.away_score<game.home_score:game.away_score>game.home_score);return <Link key={game.id} href={`/game-center/${game.id}`} className="flex items-center px-4 py-2.5 hover:bg-white/[.03] border-b border-white/[.04] last:border-0"><div className="w-5 h-5 rounded-full flex items-center justify-center text-xs font-black flex-shrink-0 mr-3" style={{background:iWon?'rgba(34,197,94,.2)':iLost?'rgba(239,68,68,.15)':'rgba(255,255,255,.08)',color:iWon?'#4ade80':iLost?'#f87171':'#64748b',fontFamily:'var(--font-display)',fontSize:'10px'}}>{iWon?'W':iLost?'L':'T'}</div><div className="flex-1 min-w-0"><div className="flex items-center gap-1 mb-0.5"><span className="text-xs text-slate-600 w-6">AWY</span><span style={{fontFamily:'var(--font-display)',fontSize:'13px',fontWeight:awayWins?700:400,color:awayWins?'#e2e8f5':'#6b7a8d'}}>{awayName}</span></div><div className="flex items-center gap-1"><span className="text-xs text-slate-600 w-6">HME</span><span style={{fontFamily:'var(--font-display)',fontSize:'13px',fontWeight:homeWins?700:400,color:homeWins?'#e2e8f5':'#6b7a8d'}}>{homeName}</span></div></div><div className="flex flex-col items-end ml-3 flex-shrink-0"><span style={{fontFamily:'var(--font-mono)',fontWeight:awayWins?800:500,fontSize:awayWins?'16px':'13px',color:awayWins?'#fff':'#374151',lineHeight:1}}>{game.away_score}</span><span style={{fontFamily:'var(--font-mono)',fontWeight:homeWins?800:500,fontSize:homeWins?'16px':'13px',color:homeWins?'#fff':'#374151',lineHeight:1,marginTop:'2px'}}>{game.home_score}</span></div><div className="ml-2 flex flex-col items-center gap-0.5"><span className="text-xs font-black text-emerald-500" style={{fontSize:'10px'}}>F</span><span className="text-xs text-slate-700" style={{fontSize:'10px'}}>{String(game.game_date||'').slice(5,10)}</span></div></Link>})}</div></div>}
 </div></PublicLayout>
}
