'use client'
import { useEffect,useState } from 'react'
import AdminLayout from '@/components/layout/AdminLayout'
import { adminDb } from '@/lib/adminDb'
import { Upload,Save,Check } from 'lucide-react'

export default function AdminSchoolsPage(){
 const [schools,setSchools]=useState<any[]>([]),[loading,setLoading]=useState(true),[editingId,setEditingId]=useState<string|null>(null),[editForm,setEditForm]=useState<any>({}),[uploading,setUploading]=useState<string|null>(null),[saving,setSaving]=useState(false),[msg,setMsg]=useState('')
 useEffect(()=>{void load()},[])
 async function load(){setLoading(true);try{const r=await adminDb.select('schools',{orderBy:'school_name',direction:'asc',limit:500});setSchools(r.data||[])}catch(e:any){setMsg(e?.message||'Could not load schools.')}finally{setLoading(false)}}
 async function uploadLogo(schoolId:string,file:File){
  setUploading(schoolId);setMsg('')
  try{const form=new FormData();form.set('school_id',schoolId);form.set('file',file);const res=await fetch('/api/admin/schools/logo',{method:'POST',credentials:'include',body:form}),json=await res.json().catch(()=>({}));if(!res.ok)throw new Error(json.error||'Upload failed');setSchools(p=>p.map(s=>s.id===schoolId?{...s,logo_url:json.logo_url}:s));setMsg('Logo uploaded!');setTimeout(()=>setMsg(''),3000)}catch(e:any){setMsg(e?.message||'Logo upload failed.')}finally{setUploading(null)}
 }
 async function saveEdit(){if(!editingId)return;setSaving(true);setMsg('');try{const payload={school_name:editForm.school_name,primary_color:editForm.primary_color||null,secondary_color:editForm.secondary_color||null,alias:editForm.alias||null,city:editForm.city||null};await adminDb.update('schools',payload,{id:editingId});setSchools(p=>p.map(s=>s.id===editingId?{...s,...payload}:s));setEditingId(null);setMsg('Saved!');setTimeout(()=>setMsg(''),3000)}catch(e:any){setMsg(e?.message||'Save failed.')}finally{setSaving(false)}}
 function chooseFile(schoolId:string){const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/svg+xml';input.onchange=e=>{const file=(e.target as HTMLInputElement).files?.[0];if(file)void uploadLogo(schoolId,file)};input.click()}
 return <AdminLayout><div className="p-4 max-w-4xl mx-auto"><div className="flex items-center justify-between mb-2"><h1 className="text-2xl font-black text-white" style={{fontFamily:'var(--font-display)'}}>Schools</h1>{msg&&<span className={`text-sm ${/failed|could not|not enabled/i.test(msg)?'text-red-400':'text-green-400'} flex items-center gap-1`}>{!(/failed|could not|not enabled/i.test(msg))&&<Check size={14}/>} {msg}</span>}</div><p className="text-slate-400 text-sm mb-5">Update school colors and logos. Logo uploads now use Cloudflare R2 when the PHOTOS binding is enabled.</p>
 {loading?<div className="text-center py-8 text-slate-500">Loading...</div>:<div className="space-y-2">{schools.map(school=>{const editing=editingId===school.id,isUploading=uploading===school.id;return <div key={school.id} className="card overflow-hidden"><div className="flex items-center gap-4 p-4"><div className="relative group flex-shrink-0"><div className="w-14 h-14 rounded-xl flex items-center justify-center overflow-hidden border border-white/10" style={{background:school.primary_color||'#1e3a5f'}}>{school.logo_url?<img src={school.logo_url} alt={school.school_name} className="w-full h-full object-contain p-1"/>:<span className="text-white/40 text-[10px] font-black text-center px-1">{school.school_name?.split(' ').map((w:string)=>w[0]).join('').slice(0,3)}</span>}</div><button onClick={()=>chooseFile(school.id)} disabled={isUploading} className="absolute inset-0 rounded-xl flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity" style={{background:'rgba(0,0,0,0.7)'}}>{isUploading?<div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin"/>:<Upload size={16} className="text-white"/>}</button></div><div className="flex-1 min-w-0"><p className="font-bold text-white truncate" style={{fontFamily:'var(--font-display)'}}>{school.school_name}</p><div className="flex items-center gap-3 mt-0.5"><span className="text-xs text-slate-500">{school.primary_color||'No color'}</span>{school.secondary_color&&<span className="text-xs text-slate-500">{school.secondary_color}</span>}{school.logo_url&&<span className="text-xs text-emerald-400 flex items-center gap-1"><Check size={10}/> Logo</span>}</div></div><button onClick={()=>{if(editing){setEditingId(null);return}setEditingId(school.id);setEditForm({school_name:school.school_name,primary_color:school.primary_color||'',secondary_color:school.secondary_color||'',alias:school.alias||'',city:school.city||''})}} className={`text-xs px-3 py-1.5 rounded-lg font-bold ${editing?'bg-white/10 text-slate-300':'bg-blue-500/20 text-blue-400'}`}>{editing?'Cancel':'Edit'}</button></div>
 {editing&&<div className="border-t border-white/8 p-4 space-y-3" style={{background:'rgba(10,15,28,0.8)'}}><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><div><label className="label">School Name</label><input className="input w-full" value={editForm.school_name} onChange={e=>setEditForm((p:any)=>({...p,school_name:e.target.value}))}/></div><div><label className="label">Alias</label><input className="input w-full" value={editForm.alias} onChange={e=>setEditForm((p:any)=>({...p,alias:e.target.value}))}/></div><div><label className="label">Primary Color</label><div className="flex gap-2"><input type="color" value={editForm.primary_color||'#1e3a5f'} onChange={e=>setEditForm((p:any)=>({...p,primary_color:e.target.value}))} className="w-10 h-10 rounded"/><input className="input flex-1" value={editForm.primary_color} onChange={e=>setEditForm((p:any)=>({...p,primary_color:e.target.value}))}/></div></div><div><label className="label">Secondary Color</label><div className="flex gap-2"><input type="color" value={editForm.secondary_color||'#ffffff'} onChange={e=>setEditForm((p:any)=>({...p,secondary_color:e.target.value}))} className="w-10 h-10 rounded"/><input className="input flex-1" value={editForm.secondary_color} onChange={e=>setEditForm((p:any)=>({...p,secondary_color:e.target.value}))}/></div></div><div><label className="label">City</label><input className="input w-full" value={editForm.city} onChange={e=>setEditForm((p:any)=>({...p,city:e.target.value}))}/></div></div><div className="flex items-center justify-between gap-3"><button onClick={()=>chooseFile(school.id)} disabled={isUploading} className="btn-secondary flex items-center gap-2 text-sm"><Upload size={14}/>{isUploading?'Uploading...':school.logo_url?'Replace Logo':'Upload Logo'}</button><div className="flex gap-2"><button onClick={()=>setEditingId(null)} className="btn-ghost">Cancel</button><button onClick={saveEdit} disabled={saving} className="btn-primary flex items-center gap-2"><Save size={14}/>{saving?'Saving...':'Save Changes'}</button></div></div></div>}</div>})}</div>}</div></AdminLayout>
}
