// src/app/(public)/page.tsx
import type { Metadata } from 'next'
import { createClient } from '@/lib/supabase/server'
import PublicLayout from '@/components/layout/PublicLayout'
import HomePhotoExperience from '@/components/home/HomePhotoExperience'
import { isScrimmage } from '@/lib/gameType'
import { sectionXDate, sectionXDateOffset } from '@/lib/sectionx-time'

export const metadata: Metadata = { description: 'Section X scores, schedules, standings, results, schools, and stories for Northern New York high school sports.' }
export const revalidate = 60

const GAME_SELECT = `*,sport:sports(*),home_team:teams!games_home_team_id_fkey(*, school:schools(*)),away_team:teams!games_away_team_id_fkey(*, school:schools(*)),external_home:external_opponents!games_external_home_opponent_id_fkey(*),external_away:external_opponents!games_external_away_opponent_id_fkey(*)`
function presentGame(game:any){if(!game)return game;return isScrimmage(game)?{...game,status:'Scrimmage',home_score:null,away_score:null}:game}
function presentGames(games:any[]|null){return(games||[]).map(presentGame)}
function photoDate(photo:any){return String(photo?.game?.game_date||photo?.created_at||'').slice(0,10)}
function photoSchoolIds(photo:any){return Array.from(new Set([photo?.game?.home_team?.school?.id,photo?.game?.away_team?.school?.id,photo?.school?.id].filter(Boolean).map(String)))}
function homepagePhotoLabel(photo:any){const game=photo?.game;const away=game?.away_team?.school?.school_name||game?.external_away?.name||null;const home=game?.home_team?.school?.school_name||game?.external_home?.name||null;const sport=photo?.sport?.sport_name||null;const matchup=away&&home?`${away} at ${home}`:null;return[matchup,sport].filter(Boolean).join(' · ')||photo?.caption||'Section X sports'}
function pickHomepagePhotos(photos:any[],activeSeason:any|null,today:string){
 if(!photos?.length)return[];const seasonType=String(activeSeason?.season_type||'').toLowerCase();const seasonId=String(activeSeason?.id||'');const todayTime=new Date(`${today}T12:00:00`).getTime();const sevenDaysAgoTime=todayTime-7*86400000;
 const currentSeason=photos.filter(photo=>{const photoSeason=String(photo?.sport?.season_type||'').toLowerCase();const gameSeasonId=String(photo?.game?.season_id||'');return(seasonType&&photoSeason===seasonType)||(seasonId&&gameSeasonId===seasonId)});
 const ranked=currentSeason.filter(photo=>{const key=photoDate(photo);if(!key)return false;const time=new Date(`${key}T12:00:00`).getTime();return Number.isFinite(time)&&time>=sevenDaysAgoTime&&time<=todayTime+86400000}).sort((a,b)=>{const dateDiff=photoDate(b).localeCompare(photoDate(a));if(dateDiff)return dateDiff;if(Boolean(a.featured)!==Boolean(b.featured))return a.featured?-1:1;return String(b.created_at||'').localeCompare(String(a.created_at||''))});
 const picked:any[]=[];const usedGames=new Set<string>();const usedSchools=new Set<string>();const take=(photo:any)=>{if(picked.length>=6||picked.some(p=>p.id===photo.id))return false;picked.push({...photo,caption:homepagePhotoLabel(photo)});if(photo?.game?.id)usedGames.add(String(photo.game.id));photoSchoolIds(photo).forEach(id=>usedSchools.add(id));return true};
 for(const photo of ranked){if(picked.length>=6)break;const gameId=String(photo?.game?.id||'');const schoolIds=photoSchoolIds(photo);if(gameId&&usedGames.has(gameId))continue;if(schoolIds.length&&schoolIds.some(id=>usedSchools.has(id)))continue;take(photo)}
 for(const photo of ranked){if(picked.length>=6)break;const gameId=String(photo?.game?.id||'');if(gameId&&usedGames.has(gameId))continue;take(photo)}for(const photo of ranked){if(picked.length>=6)break;take(photo)}if(picked.length)return picked;
 const fallback=currentSeason.slice().sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))[0]||photos[0];return fallback?[{...fallback,caption:homepagePhotoLabel(fallback)}]:[]
}
async function getHomepageData(){
 const supabase=createClient();const today=sectionXDate();const yesterday=sectionXDateOffset(-1);const tomorrow=sectionXDateOffset(1);const fourteenDaysOut=sectionXDateOffset(14);const sevenDaysAgo=sectionXDateOffset(-7);
 const{data:activeSeason}=await supabase.from('seasons').select('*').eq('is_active',true).single();
 const[{data:yesterdayGames},{data:todayGames},{data:tomorrowGames},{data:upcomingGames},{data:recentGames},{data:featuredGame},{data:homepageSponsor},{data:schools},{data:featuredSpotlight},{data:featuredAthlete},{data:allSpotlights},{data:photoCandidates}]=await Promise.all([
 supabase.from('games').select(GAME_SELECT).eq('game_date',yesterday).order('game_time',{ascending:true}),supabase.from('games').select(GAME_SELECT).eq('game_date',today).order('game_time',{ascending:true}),supabase.from('games').select(GAME_SELECT).eq('game_date',tomorrow).order('game_time',{ascending:true}),supabase.from('games').select(GAME_SELECT).gt('game_date',today).lte('game_date',fourteenDaysOut).order('game_date',{ascending:true}).order('game_time',{ascending:true}).limit(160),supabase.from('games').select(GAME_SELECT).eq('status','Final').neq('contest_type','Scrimmage').gte('game_date',sevenDaysAgo).order('game_date',{ascending:false}).order('game_time',{ascending:false}).limit(80),supabase.from('games').select(GAME_SELECT).eq('game_of_the_night',true).eq('game_date',today).order('updated_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('sponsors').select('*').eq('placement_type','homepage').eq('active',true).or(`start_date.is.null,start_date.lte.${today}`).or(`end_date.is.null,end_date.gte.${today}`).order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('schools').select('*').eq('active',true).eq('is_section_x',true).order('school_name'),supabase.from('spotlights').select('*').eq('published',true).eq('featured',true).order('created_at',{ascending:false}).limit(1).maybeSingle(),supabase.from('athlete_of_week').select('*, school:schools(id, school_name, slug, primary_color, logo_url)').eq('published',true).order('week_of',{ascending:false}).limit(1).maybeSingle(),supabase.from('spotlights').select('id, title, body, author, created_at, sport_name').eq('published',true).order('created_at',{ascending:false}).limit(6),supabase.from('photos').select(`*,school:schools(id, school_name, slug, primary_color, logo_url),sport:sports(id, sport_name, gender, season_type),game:games(id, game_date, season_id, sport_id,home_team:teams!games_home_team_id_fkey(id, school:schools(id, school_name)),away_team:teams!games_away_team_id_fkey(id, school:schools(id, school_name)),external_home:external_opponents!games_external_home_opponent_id_fkey(name),external_away:external_opponents!games_external_away_opponent_id_fkey(name))`).eq('approved',true).order('created_at',{ascending:false}).limit(96)]);
 const homepagePhotos=pickHomepagePhotos(photoCandidates||[],activeSeason||null,today);const featuredPhoto=homepagePhotos[0]||null;
 return{activeSeason:activeSeason||null,yesterdayGames:presentGames(yesterdayGames),todayGames:presentGames(todayGames),tomorrowGames:presentGames(tomorrowGames),upcomingGames:presentGames(upcomingGames),recentGames:presentGames(recentGames),featuredGame:presentGame(featuredGame||null),homepageSponsor:homepageSponsor||null,schools:schools||[],today,featuredSpotlight:featuredSpotlight||null,featuredAthlete:featuredAthlete||null,allSpotlights:allSpotlights||[],featuredPhoto,homepagePhotos}
}
export default async function HomePage(){const data=await getHomepageData();return <PublicLayout><HomePhotoExperience {...data}/></PublicLayout>}
