import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/server'
import { arbiterApi } from '@/lib/arbiter/client'
import { normalizeArbiterGame, SECTION_X_SCHOOL_IDS } from '@/lib/arbiter/schedule-intelligence'
import { POST as importRosters } from '@/app/api/admin/arbiter-rosters/route'

export const dynamic='force-dynamic'
export const maxDuration=120

const BATCH_SIZE=6
const STALE_MINUTES=12

const norm=(v:unknown)=>String(v??'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()
const val=(v:unknown)=>String(v??'').replace(/\s+/g,' ').trim()
const clean=(v:unknown)=>String(v??'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
const arr=(v:any):any[]=>Array.isArray(v)?v:v==null?[]:[v]
const nowIso=()=>new Date().toISOString()
const heartbeatMs=(run:any)=>new Date(run?.summary?.progress?.heartbeatAt||run?.started_at||0).getTime()
const isStale=(run:any)=>Date.now()-heartbeatMs(run)>STALE_MINUTES*60_000
const varsityLevel=(v:unknown)=>{const c=clean(v);return c.includes('varsity')&&!c.includes('junior')}
const sportMatches=(dbSport:any,g:any)=>{const raw=clean(g.sportName),gender=clean(g.gender),dbName=clean(dbSport.sport_name),dbGender=clean(dbSport.gender),dbSlug=clean(dbSport.slug);return(dbName===raw&&(!gender||!dbGender||gender===dbGender))||dbName===`${gender} ${raw}`||dbSlug===`${gender} ${raw}`||dbSlug===`${gender}-${raw}`}

function seasonWindow(season:any){const type=clean(season.season_type),year=Number(season.year);if(type==='winter')return{start:`${year}-11-01T00:00:00.000Z`,end:`${year+1}-03-31T23:59:59.999Z`};if(type==='spring')return{start:`${year}-03-01T00:00:00.000Z`,end:`${year}-06-30T23:59:59.999Z`};return{start:`${year}-08-01T00:00:00.000Z`,end:`${year}-11-30T23:59:59.999Z`}}
function findNamedArray(root:any,names:string[]){const wanted=new Set(names.map(clean)),seen=new Set<any>(),q=[root];while(q.length){const cur=q.shift();if(!cur||typeof cur!=='object'||seen.has(cur))continue;seen.add(cur);for(const [k,v] of Object.entries(cur)){if(wanted.has(clean(k))&&Array.isArray(v))return v as any[];if(v&&typeof v==='object')q.push(v)}}return null}
function fullName(p:any){return val(p?.displayName||p?.fullName||p?.name||[p?.firstName,p?.lastName].filter(Boolean).join(' '))}
function normalizePlayer(p:any){const displayName=fullName(p);return{jerseyNumber:val(p?.jerseyNumber||p?.jersey||p?.number),rawName:displayName,displayName,firstName:val(p?.firstName),lastName:val(p?.lastName),classYear:val(p?.classYear||p?.class||p?.grade||p?.graduationYear),position:val(p?.position||p?.positionName),height:val(p?.height)}}
function normalizeCoach(p:any){const displayName=fullName(p);return{rawName:displayName,displayName,firstName:val(p?.firstName),lastName:val(p?.lastName),title:val(p?.title||p?.role||p?.position)}}
function rosterRecord(row:any){const athlete=Array.isArray(row?.athlete)?row.athlete[0]:row?.athlete;return{name:norm(athlete?.display_name),jersey:val(row?.jersey_number),classYear:val(row?.class_year),position:val(row?.position),height:val(row?.height)}}
function incomingRosterRecord(row:any){return{name:norm(row?.displayName),jersey:val(row?.jerseyNumber),classYear:val(row?.classYear),position:val(row?.position),height:val(row?.height)}}
function coachRecord(row:any){const coach=Array.isArray(row?.coach)?row.coach[0]:row?.coach;return{name:norm(coach?.display_name),title:val(row?.title)}}
function incomingCoachRecord(row:any){return{name:norm(row?.displayName),title:val(row?.title)}}
function sig(row:any){return[row.name,row.jersey||'',row.classYear||'',row.position||'',row.height||''].join('|')}
function coachSig(row:any){return[row.name,row.title||''].join('|')}
function duplicates(rows:any[]){const seen=new Set<string>(),dups=new Set<string>();for(const row of rows){if(!row.name)continue;if(seen.has(row.name))dups.add(row.name);seen.add(row.name)}return[...dups]}
function comparePeople(current:any[],incoming:any[],type:'roster'|'coach'){
  const currentClean=current.filter(r=>r.name),incomingClean=incoming.filter(r=>r.name),currentNames=new Set(currentClean.map(r=>r.name)),incomingNames=new Set(incomingClean.map(r=>r.name)),removed=[...currentNames].filter(name=>!incomingNames.has(name)),added=[...incomingNames].filter(name=>!currentNames.has(name)),dupes=duplicates(incomingClean)
  const maxReasonable=type==='roster'?(currentClean.length===0?60:Math.max(currentClean.length*2+10,60)):(currentClean.length===0?15:Math.max(currentClean.length*2+5,15)),implausible=incomingClean.length>maxReasonable,currentMap=new Map(currentClean.map(r=>[r.name,type==='roster'?sig(r):coachSig(r)])),incomingMap=new Map(incomingClean.map(r=>[r.name,type==='roster'?sig(r):coachSig(r)])),metadataChanged=[...incomingNames].filter(name=>currentMap.has(name)&&currentMap.get(name)!==incomingMap.get(name)),safe=removed.length===0&&dupes.length===0&&!implausible,changed=safe&&(added.length>0||metadataChanged.length>0||currentClean.length!==incomingClean.length)
  return{safe,changed,removed,added,dupes,metadataChanged,implausible,currentCount:currentClean.length,incomingCount:incomingClean.length}
}
function mergeSummary(base:any,batch:any){const prior=base||{},warnings=prior.scanWarnings||{},progress=prior.progress||{};return{...prior,scanned:Number(prior.scanned||0)+Number(batch.scanned||0),published:Number(prior.published||0)+Number(batch.published||0),alreadyLoaded:Number(prior.alreadyLoaded||0)+Number(batch.alreadyLoaded||0),teamsUpdated:Number(prior.teamsUpdated||0)+Number(batch.teamsUpdated||0),safeTeams:Number(prior.safeTeams||0)+Number(batch.safeTeams||0),unchanged:Number(prior.unchanged||0)+Number(batch.unchanged||0),athletesAdded:Number(prior.athletesAdded||0)+Number(batch.athletesAdded||0),athleteMetadataUpdated:Number(prior.athleteMetadataUpdated||0)+Number(batch.athleteMetadataUpdated||0),coachesAdded:Number(prior.coachesAdded||0)+Number(batch.coachesAdded||0),coachMetadataUpdated:Number(prior.coachMetadataUpdated||0)+Number(batch.coachMetadataUpdated||0),quarantined:Number(prior.quarantined||0)+Number(batch.quarantined||0),failed:Number(prior.failed||0)+Number(batch.failed||0),unlinked:Number(prior.unlinked||0)+Number(batch.unlinked||0),scanWarnings:{notPublished:Number(warnings.notPublished||0)+Number(batch.scanWarnings?.notPublished||0),unmatched:Number(warnings.unmatched||0)+Number(batch.scanWarnings?.unmatched||0),ambiguous:Number(warnings.ambiguous||0)+Number(batch.scanWarnings?.ambiguous||0),apiErrors:Number(warnings.apiErrors||0)+Number(batch.scanWarnings?.apiErrors||0)},actions:[...(prior.actions||[]),...(batch.actions||[])].slice(-100),quarantines:[...(prior.quarantines||[]),...(batch.quarantines||[])].slice(-100),failures:[...(prior.failures||[]),...(batch.failures||[])].slice(-100),progress:{...progress,...batch.progress}}}

async function markStale(db:any,run:any){const summary={...(run.summary||{}),error:'Roster automation heartbeat expired before completion.',stale:true,staleDetectedAt:nowIso(),progress:{...(run.summary?.progress||{}),phase:'stale',heartbeatAt:run.summary?.progress?.heartbeatAt||run.started_at}};await db.from('arbiter_roster_automation_runs').update({status:'failed',summary,finished_at:nowIso()}).eq('id',run.id).eq('status','running')}

async function refreshTeamLinks(db:any,season:any,varsity:any[],schools:any[],sports:any[]){
  const window=seasonWindow(season)
  const raw=await arbiterApi.games({SchoolIds:Array.from(SECTION_X_SCHOOL_IDS),DateFilter:'Range',GameStartDate:window.start,GameEndDate:window.end,IncludeDeletedGames:false,IncludePendingInformation:false})
  const games=arr(raw).map(normalizeArbiterGame).filter((g:any)=>varsityLevel(g.levelName)&&g.isContest&&!g.isPractice)
  const schoolByArbiter=new Map(schools.map((s:any)=>[Number(s.arbiter_entity_id),s])),candidates=new Map<string,Map<number,{count:number,schoolId:number}>>()
  const record=(side:any,g:any)=>{if(!side?.isSectionX||!side?.teamId||!side?.schoolId)return;const school=schoolByArbiter.get(Number(side.schoolId)) as any;if(!school)return;const sport=sports.find((s:any)=>sportMatches(s,g));if(!sport)return;const team=varsity.find((t:any)=>t.school_id===school.id&&t.sport_id===sport.id);if(!team)return;const map=candidates.get(team.id)||new Map<number,{count:number,schoolId:number}>(),prior=map.get(Number(side.teamId))||{count:0,schoolId:Number(side.schoolId)};prior.count++;map.set(Number(side.teamId),prior);candidates.set(team.id,map)}
  for(const g of games){record(g.home,g);record(g.away,g)}
  let linked=0,ambiguous=0,failed=0
  for(const [teamId,map] of candidates){const ranked=[...map.entries()].sort((a,b)=>b[1].count-a[1].count);if(ranked.length>1&&ranked[0][1].count===ranked[1][1].count){ambiguous++;continue}const [arbiterTeamId,meta]=ranked[0];const {error}=await db.from('arbiter_team_links').upsert({team_id:teamId,arbiter_team_id:arbiterTeamId,arbiter_school_id:meta.schoolId,source:'schedule-observation',confidence:'stable',observed_count:meta.count,last_seen_at:nowIso(),updated_at:nowIso()},{onConflict:'team_id'});if(error)failed++;else linked++}
  return{linked,ambiguous,failed,observedTeams:candidates.size}
}

export async function GET(req:NextRequest){
  const db=createAdminClient(),token=req.headers.get('x-sectionx-automation-key')||''
  const {data:allowed,error:authError}=await db.rpc('verify_sectionx_automation_key',{p_token:token})
  if(authError||allowed!==true)return NextResponse.json({ok:false,error:'Unauthorized'},{status:401})

  const {data:latestRunning,error:runningError}=await db.from('arbiter_roster_automation_runs').select('id,season_id,status,summary,started_at').eq('status','running').order('started_at',{ascending:false}).limit(1).maybeSingle()
  if(runningError)return NextResponse.json({ok:false,error:runningError.message},{status:500})
  let run:any=latestRunning||null
  if(run&&isStale(run)){await markStale(db,run);run=null}
  if(run&&run.summary?.progress?.phase!=='queued-next')return NextResponse.json({ok:true,automated:true,runId:run.id,status:'running',message:'Roster worker already active.',progress:run.summary?.progress||{}},{status:202})

  if(!run){const initial={progress:{phase:'queued-next',cursor:0,processed:0,total:0,batchSize:BATCH_SIZE,batchNumber:0,heartbeatAt:nowIso(),lastBatchStartedAt:null,lastBatchFinishedAt:null}};const {data:newRun,error:runError}=await db.from('arbiter_roster_automation_runs').insert({status:'running',trigger_source:'supabase-roster-cron',summary:initial}).select('id,season_id,status,summary,started_at').single();if(runError)return NextResponse.json({ok:false,error:`Could not start roster automation: ${runError.message}`},{status:500});run=newRun}

  const cursor=Math.max(0,Number(run.summary?.progress?.cursor||0)),currentSummary=run.summary||{},claimedSummary={...currentSummary,progress:{...(currentSummary.progress||{}),phase:'processing',cursor,batchSize:BATCH_SIZE,heartbeatAt:nowIso(),lastBatchStartedAt:nowIso()}}
  const {data:claimed,error:claimError}=await db.from('arbiter_roster_automation_runs').update({summary:claimedSummary}).eq('id',run.id).eq('status','running').eq('summary->progress->>phase','queued-next').eq('summary->progress->>cursor',String(cursor)).select('id').maybeSingle()
  if(claimError)return NextResponse.json({ok:false,error:`Could not claim roster batch: ${claimError.message}`},{status:500})
  if(!claimed)return NextResponse.json({ok:true,automated:true,runId:run.id,status:'running',message:'Another roster worker claimed this batch.'},{status:202})

  const runId=run.id
  try{
    const {data:season,error:seasonError}=run.season_id?await db.from('seasons').select('id,name,season_type,year,is_active').eq('id',run.season_id).single():await db.from('seasons').select('id,name,season_type,year,is_active').eq('is_active',true).limit(1).maybeSingle()
    if(seasonError||!season)throw new Error(seasonError?.message||'No active season found.')
    const [{data:teams,error:teamError},{data:teamSeasons,error:tsError},{data:schools,error:schoolError},{data:sports,error:sportError}]=await Promise.all([db.from('teams').select('id,school_id,sport_id,team_name,level,active').eq('active',true),db.from('team_seasons').select('team_id,season_id,active_for_season').eq('season_id',season.id).eq('active_for_season',true),db.from('schools').select('id,school_name,arbiter_entity_id').eq('active',true).not('arbiter_entity_id','is',null),db.from('sports').select('id,sport_name,gender,season_type,slug')])
    const baseError=teamError||tsError||schoolError||sportError;if(baseError)throw new Error(baseError.message)
    const activeIds=new Set((teamSeasons||[]).map((x:any)=>x.team_id)),varsity=(teams||[]).filter((t:any)=>activeIds.has(t.id)&&varsityLevel(t.level)).sort((a:any,b:any)=>String(a.id).localeCompare(String(b.id)))

    let {data:links,error:linkError}=await db.from('arbiter_team_links').select('team_id,arbiter_team_id,arbiter_school_id,last_seen_at').in('team_id',varsity.map((t:any)=>t.id))
    if(linkError)throw new Error(`Stable team-link read failed: ${linkError.message}`)
    if(cursor===0&&(!links||links.length<varsity.length)){const refreshed=await refreshTeamLinks(db,season,varsity,schools||[],sports||[]);const reread=await db.from('arbiter_team_links').select('team_id,arbiter_team_id,arbiter_school_id,last_seen_at').in('team_id',varsity.map((t:any)=>t.id));if(reread.error)throw new Error(`Stable team-link refresh failed: ${reread.error.message}`);links=reread.data||[];currentSummary.teamLinks=refreshed}

    const linkByTeam=new Map((links||[]).map((l:any)=>[l.team_id,l])),batchTeams=varsity.slice(cursor,cursor+BATCH_SIZE),batchIds=batchTeams.map((t:any)=>t.id)
    const [{data:currentRoster,error:rosterError},{data:currentCoaches,error:coachError}]=await Promise.all([batchIds.length?db.from('roster_entries').select('team_id,jersey_number,class_year,position,height,athlete:athletes(display_name)').eq('season_id',season.id).eq('source','arbiter').eq('active',true).in('team_id',batchIds):Promise.resolve({data:[],error:null} as any),batchIds.length?db.from('team_coaches').select('team_id,title,coach:coaches(display_name)').eq('season_id',season.id).eq('source','arbiter').eq('active',true).in('team_id',batchIds):Promise.resolve({data:[],error:null} as any)])
    if(rosterError)throw new Error(`Current roster read failed: ${rosterError.message}`);if(coachError)throw new Error(`Current coach read failed: ${coachError.message}`)
    const rosterByTeam=new Map<string,any[]>(),coachesByTeam=new Map<string,any[]>();for(const row of currentRoster||[]){const list=rosterByTeam.get((row as any).team_id)||[];list.push(rosterRecord(row));rosterByTeam.set((row as any).team_id,list)}for(const row of currentCoaches||[]){const list=coachesByTeam.get((row as any).team_id)||[];list.push(coachRecord(row));coachesByTeam.set((row as any).team_id,list)}

    const payloads:any[]=[],quarantines:any[]=[],failures:any[]=[],actions:any[]=[];let published=0,alreadyLoaded=0,unlinked=0,apiErrors=0,notPublished=0
    for(let i=0;i<batchTeams.length;i+=3){const slice=batchTeams.slice(i,i+3),fetched=await Promise.all(slice.map(async(team:any)=>{const link=linkByTeam.get(team.id) as any;if(!link)return{team,link:null,payload:null,error:null};try{return{team,link,payload:await arbiterApi.teamWithRoster(Number(link.arbiter_team_id),Number(link.arbiter_school_id)||undefined),error:null}}catch(error){return{team,link,payload:null,error:error instanceof Error?error.message:String(error)}}}));for(const f of fetched){if(!f.link){unlinked++;quarantines.push({teamId:f.team.id,area:'identity',reason:'arbiter-team-link-missing'});continue}if(f.error){apiErrors++;failures.push({teamId:f.team.id,message:f.error});continue}const playersRaw=findNamedArray(f.payload,['roster','rosters','players','athletes','studentAthletes']),coachesRaw=findNamedArray(f.payload,['coaches','coachingStaff','staff']),roster=(playersRaw||[]).map(normalizePlayer).filter((p:any)=>p.displayName),coaches=(coachesRaw||[]).map(normalizeCoach).filter((p:any)=>p.displayName),rosterFound=playersRaw!==null,coachesFound=coachesRaw!==null;if(!rosterFound&&!coachesFound){notPublished++;continue}published++;if((rosterByTeam.get(f.team.id)||[]).length>0)alreadyLoaded++;payloads.push({team_id:f.team.id,season_id:season.id,source_url:null,roster_found:rosterFound,coaches_found:coachesFound,roster,coaches})}}

    const safePayloads:any[]=[];let unchanged=0,athletesAdded=0,athleteMetadataUpdated=0,coachesAdded=0,coachMetadataUpdated=0
    for(const payload of payloads){const currentR=rosterByTeam.get(payload.team_id)||[],incomingR=(payload.roster||[]).map(incomingRosterRecord),currentC=coachesByTeam.get(payload.team_id)||[],incomingC=(payload.coaches||[]).map(incomingCoachRecord),rosterCmp=payload.roster_found===true?comparePeople(currentR,incomingR,'roster'):{safe:false,changed:false,removed:[],added:[],dupes:[],metadataChanged:[],implausible:false,currentCount:currentR.length,incomingCount:0},coachCmp=payload.coaches_found===true?comparePeople(currentC,incomingC,'coach'):{safe:false,changed:false,removed:[],added:[],dupes:[],metadataChanged:[],implausible:false,currentCount:currentC.length,incomingCount:0};if(payload.roster_found===true&&!rosterCmp.safe)quarantines.push({teamId:payload.team_id,area:'roster',reason:rosterCmp.dupes.length?'duplicate-athlete-names':rosterCmp.implausible?'implausible-roster-size':'roster-removal-or-replacement',currentCount:rosterCmp.currentCount,incomingCount:rosterCmp.incomingCount,removed:rosterCmp.removed.slice(0,20),duplicates:rosterCmp.dupes.slice(0,20)});if(payload.coaches_found===true&&!coachCmp.safe)quarantines.push({teamId:payload.team_id,area:'coaches',reason:coachCmp.dupes.length?'duplicate-coach-names':coachCmp.implausible?'implausible-coach-size':'coach-removal-or-replacement',currentCount:coachCmp.currentCount,incomingCount:coachCmp.incomingCount,removed:coachCmp.removed.slice(0,20),duplicates:coachCmp.dupes.slice(0,20)});const rosterWrite=payload.roster_found===true&&rosterCmp.safe&&rosterCmp.changed,coachWrite=payload.coaches_found===true&&coachCmp.safe&&coachCmp.changed;if(!rosterWrite&&!coachWrite){unchanged++;continue}safePayloads.push({...payload,roster_found:rosterWrite,coaches_found:coachWrite,roster:rosterWrite?payload.roster:[],coaches:coachWrite?payload.coaches:[]});athletesAdded+=rosterWrite?rosterCmp.added.length:0;athleteMetadataUpdated+=rosterWrite?rosterCmp.metadataChanged.length:0;coachesAdded+=coachWrite?coachCmp.added.length:0;coachMetadataUpdated+=coachWrite?coachCmp.metadataChanged.length:0;actions.push({teamId:payload.team_id,roster:rosterWrite?{added:rosterCmp.added.length,metadataUpdated:rosterCmp.metadataChanged.length,newCount:rosterCmp.incomingCount}:null,coaches:coachWrite?{added:coachCmp.added.length,metadataUpdated:coachCmp.metadataChanged.length,newCount:coachCmp.incomingCount}:null})}

    let teamsUpdated=0,failed=apiErrors;for(let i=0;i<safePayloads.length;i+=3){const batch=safePayloads.slice(i,i+3),importReq=new NextRequest('http://sectionx.internal/api/admin/arbiter-rosters',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({teams:batch})}),response=await importRosters(importReq),result:any=await response.json(),resultRows=Array.isArray(result?.results)?result.results:[];teamsUpdated+=resultRows.filter((r:any)=>!Array.isArray(r.errors)||r.errors.length===0).length;const batchErrors=[...(Array.isArray(result?.errors)?result.errors:[]),...resultRows.flatMap((r:any)=>(r.errors||[]).map((message:string)=>({teamId:r.team_id,message})))];if(!response.ok||result?.success===false||batchErrors.length){failed+=Math.max(1,batchErrors.length);failures.push(...batchErrors.slice(0,25))}}

    const processed=batchTeams.length,total=varsity.length,nextOffset=Math.min(total,cursor+processed),hasMore=nextOffset<total,batchSummary={scanned:processed,published,alreadyLoaded,teamsUpdated,safeTeams:safePayloads.length,unchanged,athletesAdded,athleteMetadataUpdated,coachesAdded,coachMetadataUpdated,quarantined:quarantines.length,failed,unlinked,scanWarnings:{notPublished,unmatched:unlinked,ambiguous:0,apiErrors},actions,quarantines,failures,progress:{phase:hasMore?'queued-next':'complete',cursor:nextOffset,processed:nextOffset,total,batchSize:BATCH_SIZE,batchNumber:Number(currentSummary.progress?.batchNumber||0)+1,heartbeatAt:nowIso(),lastBatchStartedAt:claimedSummary.progress.lastBatchStartedAt,lastBatchFinishedAt:nowIso(),hasMore}},merged=mergeSummary({...currentSummary,season:{id:season.id,name:season.name}},batchSummary)

    if(hasMore){await db.from('arbiter_roster_automation_runs').update({season_id:season.id,status:'running',summary:merged}).eq('id',runId).eq('status','running');const {error:queueError}=await db.rpc('trigger_sectionx_arbiter_rosters');if(queueError){const failedSummary={...merged,error:`Could not queue next roster batch: ${queueError.message}`,progress:{...merged.progress,phase:'failed',heartbeatAt:nowIso()}};await db.from('arbiter_roster_automation_runs').update({status:'failed',summary:failedSummary,finished_at:nowIso()}).eq('id',runId);return NextResponse.json({ok:false,automated:true,runId,error:failedSummary.error},{status:500})}return NextResponse.json({ok:true,automated:true,runId,status:'running',progress:merged.progress,batch:{offset:cursor,processed,teamsUpdated,athletesAdded,quarantined:quarantines.length,failed}},{status:202})}

    const finalStatus=Number(merged.failed||0)>0?'completed-with-errors':'completed';await db.from('arbiter_roster_automation_runs').update({status:finalStatus,season_id:season.id,summary:merged,finished_at:nowIso()}).eq('id',runId);return NextResponse.json({ok:finalStatus==='completed',automated:true,runId,status:finalStatus,...merged},{status:finalStatus==='completed'?200:207})
  }catch(error){const message=error instanceof Error?error.message:String(error);console.error('Automated Arbiter roster reconciliation batch failed:',error);const {data:current}=await db.from('arbiter_roster_automation_runs').select('summary').eq('id',runId).maybeSingle();const failedSummary={...(current?.summary||{}),error:message,progress:{...(current?.summary?.progress||{}),phase:'failed',heartbeatAt:nowIso()}};await db.from('arbiter_roster_automation_runs').update({status:'failed',summary:failedSummary,finished_at:nowIso()}).eq('id',runId);return NextResponse.json({ok:false,automated:true,runId,error:message},{status:500})}
}
