'use client'
import { useEffect, useState } from 'react'
import AdminLayout from '@/components/layout/AdminLayout'
import { createClient } from '@/lib/supabase/client'

function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function extractEmbed(input:string){const match=input.match(/src=["']([^"']+facebook\.com\/plugins\/video\.php[^"']*)["']/i);return match?match[1].replaceAll('&amp;','&'):input.includes('facebook.com/plugins/video.php')?input.trim():''}
function extractFacebookUrl(input:string){const href=input.match(/href=([^&"']+)/i)?.[1];if(href){try{return decodeURIComponent(href)}catch{}}return input.startsWith('http')&&!input.includes('/plugins/video.php')?input.trim():''}

export default function WeeklyRecapAdmin(){
 const db=createClient();const [items,setItems]=useState<any[]>([]);const [saving,setSaving]=useState(false);const [form,setForm]=useState({title:'',week_label:'',season_label:'Fall 2026',published_date:new Date().toLocaleDateString('en-CA'),summary:'',facebook_input:''})
 const load=async()=>{const{data}=await db.from('weekly_recaps').select('*').order('published_date',{ascending:false});setItems(data||[])};useEffect(()=>{load()},[])
 async function publish(){if(!form.title||!form.facebook_input)return alert('Add a title and Facebook embed code/link.');setSaving(true);const embed=extractEmbed(form.facebook_input);const fb=extractFacebookUrl(form.facebook_input);const res=await fetch('/api/admin/weekly-recap',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:form.title,slug:slugify(form.title+'-'+form.published_date),summary:form.summary||null,published_date:form.published_date,season_label:form.season_label||null,week_label:form.week_label||null,facebook_url:fb||null,facebook_embed_url:embed||null})});const json=await res.json();if(!res.ok)alert(json.error||'Publish failed.');else{setForm({...form,title:'',week_label:'',summary:'',facebook_input:''});await load();alert('Weekly Recap published.')}setSaving(false)}
 return <AdminLayout><div className="p-4 md:p-6 max-w-3xl"><div className="mb-5"><div className="text-xs uppercase tracking-[.18em] text-blue-400 font-black">Content</div><h1 className="text-2xl font-black text-white" style={{fontFamily:'var(--font-display)'}}>Weekly Recap</h1><p className="text-sm text-slate-400 mt-1">Post to Facebook, paste the embed code here, publish. The newest recap automatically becomes the featured episode.</p></div><div className="card p-4 space-y-3 mb-6"><input className="input w-full" placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><div className="grid grid-cols-2 md:grid-cols-3 gap-3"><input className="input" placeholder="Week 2" value={form.week_label} onChange={e=>setForm({...form,week_label:e.target.value})}/><input className="input" placeholder="Fall 2026" value={form.season_label} onChange={e=>setForm({...form,season_label:e.target.value})}/><input className="input" type="date" value={form.published_date} onChange={e=>setForm({...form,published_date:e.target.value})}/></div><textarea className="input w-full min-h-24" placeholder="Short episode summary" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><textarea className="input w-full min-h-32 font-mono text-xs" placeholder="Paste Facebook embed code (preferred) or direct video URL" value={form.facebook_input} onChange={e=>setForm({...form,facebook_input:e.target.value})}/><button onClick={publish} disabled={saving} className="btn-primary w-full h-11 font-black">{saving?'Publishing...':'Publish Weekly Recap'}</button></div><h2 className="text-sm font-black text-white mb-2">Published Recaps</h2><div className="space-y-2">{items.map(item=><div key={item.id} className="card p-3"><div className="text-xs text-blue-400 font-black">{item.season_label} · {item.week_label}</div><div className="text-white font-bold">{item.title}</div><div className="text-xs text-slate-500">{item.published_date} · {item.published?'Published':'Draft'}</div></div>)}</div></div></AdminLayout>
}
