'use client'
import { useEffect,useState } from 'react'
import AdminLayout from '@/components/layout/AdminLayout'
import { adminDb } from '@/lib/adminDb'
import { Plus,Save,Star } from 'lucide-react'

export default function AthleteOfWeekAdmin(){
 const [athletes,setAthletes]=useState<any[]>([]),[nominations,setNominations]=useState<any[]>([]),[schools,setSchools]=useState<any[]>([]),[editing,setEditing]=useState<any|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[tab,setTab]=useState<'featured'|'nominations'>('featured')
 const blank={athlete_name:'',school_id:'',sport_name:'',grade:'',stats:'',body:'',photo_url:'',week_of:new Date().toISOString().split('T')[0],published:false}
 useEffect(()=>{void load()},[])
 async function load(){
  setLoading(true)
  try{
   const [a,n,s]=await Promise.all([
    adminDb.select('athlete_of_week',{orderBy:'week_of',direction:'desc',limit:500}),
    adminDb.select('athlete_nominations',{orderBy:'created_at',direction:'desc',limit:500}),
    adminDb.select('schools',{columns:['id','school_name'],orderBy:'school_name',direction:'asc',limit:500})
   ])
   const schoolMap=new Map((s.data||[]).map((x:any)=>[x.id,x.school_name]))
   setAthletes((a.data||[]).map((x:any)=>({...x,published:Boolean(x.published),school:x.school_id?{school_name:schoolMap.get(x.school_id)||''}:null})))
   setNominations((n.data||[]).map((x:any)=>({...x,reviewed:Boolean(x.reviewed)})));setSchools(s.data||[])
  }catch(e:any){setMsg(e?.message||'Could not load Athlete of the Week data.')}
  finally{setLoading(false)}
 }
 async function save(){
  if(!editing?.athlete_name||!editing?.body){setMsg('Name and story are required.');return}
  setSaving(true)
  try{
   const payload={athlete_name:editing.athlete_name,school_id:editing.school_id||null,sport_name:editing.sport_name||null,grade:editing.grade||null,stats:editing.stats||null,body:editing.body,photo_url:editing.photo_url||null,week_of:editing.week_of,published:Boolean(editing.published),updated_at:new Date().toISOString()}
   if(editing.id)await adminDb.update('athlete_of_week',payload,{id:editing.id});else await adminDb.insert('athlete_of_week',{...payload,created_at:new Date().toISOString()})
   setEditing(null);setMsg('Saved!');setTimeout(()=>setMsg(''),3000);await load()
  }catch(e:any){setMsg(e?.message||'Could not save athlete.')}finally{setSaving(false)}
 }
 async function togglePublished(id:string,current:boolean){
  try{
   if(!current)for(const athlete of athletes)if(athlete.id!==id&&athlete.published)await adminDb.update('athlete_of_week',{published:false,updated_at:new Date().toISOString()},{id:athlete.id})
   await adminDb.update('athlete_of_week',{published:!current,updated_at:new Date().toISOString()},{id});await load()
  }catch(e:any){setMsg(e?.message||'Could not update featured athlete.')}
 }
 async function markNomReviewed(id:string){try{await adminDb.update('athlete_nominations',{reviewed:true},{id});await load()}catch(e:any){setMsg(e?.message||'Could not update nomination.')}}
 async function promoteNomination(nom:any){setEditing({...blank,athlete_name:nom.athlete_name,sport_name:nom.sport_name,grade:nom.grade||'',body:nom.achievement});setTab('featured');void markNomReviewed(nom.id)}
 return <AdminLayout><div className="p-4 max-w-3xl mx-auto"><div className="flex items-center justify-between mb-2"><h1 className="text-2xl font-black text-white" style={{fontFamily:'var(--font-display)'}}>🏅 Athlete of the Week</h1>{msg&&<span className="text-sm text-green-400">{msg}</span>}</div><p className="text-slate-400 text-sm mb-4">Feature one athlete per week. Published athlete shows on the homepage.</p>
 <div className="flex gap-2 mb-5">{(['featured','nominations'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className="text-xs font-black px-4 py-1.5 rounded-full uppercase tracking-widest transition-all" style={{fontFamily:'var(--font-display)',background:tab===t?'rgba(37,99,235,0.2)':'rgba(255,255,255,0.05)',color:tab===t?'#60a5fa':'#4a5f7a',border:`1px solid ${tab===t?'rgba(37,99,235,0.3)':'rgba(255,255,255,0.06)'}`}}>{t==='nominations'?`Nominations (${nominations.filter(n=>!n.reviewed).length})`:'Featured Athletes'}</button>)}</div>
 {tab==='featured'&&<>{editing?<div className="card p-5 mb-5 space-y-3"><p className="text-sm font-bold text-white">{editing.id?'Edit Athlete':'Feature New Athlete'}</p><div className="grid grid-cols-2 gap-3"><div><label className="label">Athlete Name *</label><input className="input w-full" value={editing.athlete_name} onChange={e=>setEditing((p:any)=>({...p,athlete_name:e.target.value}))}/></div><div><label className="label">School</label><select className="input w-full" value={editing.school_id||''} onChange={e=>setEditing((p:any)=>({...p,school_id:e.target.value}))}><option value="">Select school...</option>{schools.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></div><div><label className="label">Sport</label><input className="input w-full" value={editing.sport_name||''} onChange={e=>setEditing((p:any)=>({...p,sport_name:e.target.value}))}/></div><div><label className="label">Grade</label><input className="input w-full" value={editing.grade||''} onChange={e=>setEditing((p:any)=>({...p,grade:e.target.value}))}/></div><div className="col-span-2"><label className="label">Stats / Achievement</label><input className="input w-full" value={editing.stats||''} onChange={e=>setEditing((p:any)=>({...p,stats:e.target.value}))}/></div><div className="col-span-2"><label className="label">Story *</label><textarea className="input w-full h-32 resize-none" value={editing.body||''} onChange={e=>setEditing((p:any)=>({...p,body:e.target.value}))}/></div><div><label className="label">Week Of</label><input type="date" className="input w-full" value={editing.week_of} onChange={e=>setEditing((p:any)=>({...p,week_of:e.target.value}))} style={{colorScheme:'dark'}}/></div><div><label className="label">Photo URL (optional)</label><input className="input w-full" value={editing.photo_url||''} onChange={e=>setEditing((p:any)=>({...p,photo_url:e.target.value}))}/></div></div><label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={Boolean(editing.published)} onChange={e=>setEditing((p:any)=>({...p,published:e.target.checked}))}/><span className="text-sm text-slate-300">⭐ Publish to homepage</span></label><div className="flex gap-2 justify-end"><button onClick={()=>setEditing(null)} className="btn-ghost">Cancel</button><button onClick={save} disabled={saving} className="btn-primary flex items-center gap-2"><Save size={14}/>{saving?'Saving...':'Save'}</button></div></div>:<button onClick={()=>setEditing({...blank})} className="btn-primary flex items-center gap-2 mb-5"><Plus size={14}/> Feature New Athlete</button>}
 {loading?<div className="text-center py-8 text-slate-500">Loading...</div>:<div className="space-y-2">{athletes.length===0&&<div className="card p-8 text-center text-slate-500">No athletes featured yet.</div>}{athletes.map(a=><div key={a.id} className={`card p-4 flex items-start gap-3 ${a.published?'border-yellow-400/20':''}`} style={a.published?{background:'rgba(251,191,36,0.04)'}:{}}><div className="flex-1 min-w-0"><div className="flex items-center gap-2 flex-wrap mb-1"><p className="font-black text-white text-sm" style={{fontFamily:'var(--font-display)'}}>{a.athlete_name}</p>{a.published&&<span className="text-xs text-yellow-400">⭐ Featured</span>}<span className="text-xs text-slate-500">{a.sport_name}</span><span className="text-xs text-slate-600">{a.school?.school_name}</span></div>{a.stats&&<p className="text-xs text-blue-400 mb-1">{a.stats}</p>}<p className="text-xs text-slate-500 line-clamp-2">{a.body}</p><p className="text-xs text-slate-700 mt-1">Week of {new Date(a.week_of+'T12:00:00').toLocaleDateString()}</p></div><div className="flex items-center gap-1 flex-shrink-0"><button onClick={()=>togglePublished(a.id,a.published)} className={`p-1.5 ${a.published?'text-yellow-400':'text-slate-600 hover:text-yellow-400'}`}><Star size={14}/></button><button onClick={()=>setEditing({...a,school_id:a.school_id||''})} className="p-1.5 text-slate-400 hover:text-white text-sm">✏️</button></div></div>)}</div>}</>}
 {tab==='nominations'&&<div className="space-y-2">{nominations.length===0&&<div className="card p-8 text-center text-slate-500">No nominations yet.</div>}{nominations.map(n=><div key={n.id} className={`card p-4 ${n.reviewed?'opacity-50':''}`}><div className="flex items-start justify-between gap-3"><div className="flex-1"><div className="flex items-center gap-2 mb-1"><p className="font-black text-white text-sm" style={{fontFamily:'var(--font-display)'}}>{n.athlete_name}</p><span className="text-xs text-slate-500">{n.school_name} · {n.sport_name}</span>{n.grade&&<span className="text-xs text-slate-600">{n.grade}</span>}</div><p className="text-xs text-slate-300 mb-1">{n.achievement}</p>{n.nominator_name&&<p className="text-xs text-slate-600">Nominated by {n.nominator_name}{n.nominator_email?` (${n.nominator_email})`:''}</p>}<p className="text-xs text-slate-700 mt-1">{new Date(n.created_at).toLocaleDateString()}</p></div>{!n.reviewed&&<div className="flex gap-1 flex-shrink-0"><button onClick={()=>promoteNomination(n)} className="text-xs px-2 py-1 rounded font-bold" style={{background:'rgba(37,99,235,0.2)',color:'#60a5fa'}}>Feature →</button><button onClick={()=>markNomReviewed(n.id)} className="text-xs px-2 py-1 rounded text-slate-600 hover:text-slate-400">Dismiss</button></div>}</div></div>)}</div>}</div></AdminLayout>
}
