'use client'

import { useEffect, useMemo, useState } from 'react'

export default function PhotoAthleteSuggestor({ gameId, selected, onChange }: { gameId: string; selected: string[]; onChange: (ids:string[])=>void }) {
  const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(false),[search,setSearch]=useState('')
  useEffect(()=>{let active=true;async function load(){if(!gameId){setRows([]);return}setLoading(true);try{const r=await fetch(`/api/photos/game-roster?gameId=${encodeURIComponent(gameId)}`,{cache:'no-store'}),d=await r.json();if(active)setRows(r.ok&&d.ok?d.rows||[]:[])}catch{if(active)setRows([])}finally{if(active)setLoading(false)}}void load();return()=>{active=false}},[gameId])
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?rows.filter((r:any)=>`${r.athlete?.display_name||''} ${r.jersey_number||''}`.toLowerCase().includes(q)):rows},[rows,search])
  function toggle(id:string){onChange(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id])}
  if(!gameId)return null
  return <div className="rounded-xl border border-white/10 bg-black/20 p-4 space-y-3"><div><div className="text-sm font-bold text-white">Who is in the photo? <span className="text-slate-500 font-normal">Optional</span></div><p className="text-xs text-slate-500 mt-1">Tag rostered athletes now. Tags stay private until the photo and tags are approved by Section X.</p></div>{loading?<div className="text-xs text-slate-500">Loading game rosters…</div>:rows.length?<><input className="input w-full" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search athlete or jersey number…"/><div className="max-h-52 overflow-auto rounded-lg border border-white/10">{filtered.map((r:any)=>{const yes=selected.includes(r.athlete_id);return <button type="button" key={r.athlete_id} onClick={()=>toggle(r.athlete_id)} className={`w-full flex items-center gap-3 px-3 py-2 border-b border-white/5 last:border-0 text-left ${yes?'bg-blue-500/10':'hover:bg-white/[0.03]'}`}><span className={`w-4 h-4 rounded border flex items-center justify-center text-[10px] ${yes?'bg-blue-600 border-blue-500 text-white':'border-white/20'}`}>{yes?'✓':''}</span><span className="flex-1 text-sm text-white">{r.athlete?.display_name||'Athlete'}</span>{r.jersey_number&&<span className="text-xs text-slate-500">#{r.jersey_number}</span>}</button>})}</div><div className="text-xs text-blue-300">{selected.length} athlete{selected.length===1?'':'s'} selected</div></>:<div className="text-xs text-slate-500">No published roster is available for this game yet. You can still submit the photo.</div>}</div>
}
