'use client'

import { useEffect,useMemo,useRef,useState } from 'react'
import type { Sport } from '@/types'
import PhotoAthleteSuggestor from './PhotoAthleteSuggestor'

type GameOption={id:string;game_date:string;game_time:string|null;sport_id:string|null;sport_name:string;home_team_id:string|null;away_team_id:string|null;home_school_id:string|null;away_school_id:string|null;home_name:string;away_name:string}
interface Props{schools:{id:string;school_name:string}[];sports:Sport[];games:GameOption[];initialGameId?:string}
type DayFilter='yesterday'|'today'|'tomorrow'|'all'
type BatchItem={key:string;file:File;preview:string;status:'ready'|'uploading'|'uploaded'|'failed';error?:string;photoId?:string}

const MAX_BATCH=10
const MAX_FILE_BYTES=15*1024*1024
function localDateKey(offset=0){const d=new Date();d.setDate(d.getDate()+offset);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function timeLabel(value:string|null){if(!value)return'TBA';const[hRaw,mRaw]=value.split(':'),h=Number(hRaw),m=Number(mRaw);if(Number.isNaN(h)||Number.isNaN(m))return value;return`${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'PM':'AM'}`}
function dateLabel(value:string){return new Date(`${value}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function makeItem(file:File):BatchItem{return{key:`${file.name}-${file.size}-${file.lastModified}-${Math.random()}`,file,preview:URL.createObjectURL(file),status:'ready'}}

export default function SubmitPhotoForm({schools,sports,games,initialGameId=''}:Props){
 const initialGame=games.find(g=>g.id===initialGameId)
 const [form,setForm]=useState({submitter_name:'',submitter_email:'',photographer_credit_name:'',school_id:initialGame?.home_school_id||initialGame?.away_school_id||'',sport_id:initialGame?.sport_id||'',game_id:initialGameId,caption:''})
 const [items,setItems]=useState<BatchItem[]>([]),[permission,setPermission]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const [dayFilter,setDayFilter]=useState<DayFilter>(initialGame?'all':'today'),[gameSearch,setGameSearch]=useState(''),[gameSport,setGameSport]=useState(''),[gameSchool,setGameSchool]=useState('')
 const [singleTags,setSingleTags]=useState<string[]>([]),[dragging,setDragging]=useState(false),[progress,setProgress]=useState({done:0,total:0})
 const fileRef=useRef<HTMLInputElement>(null),selectedGame=games.find(g=>g.id===form.game_id),uploaded=items.filter(i=>i.status==='uploaded')
 useEffect(()=>()=>{items.forEach(i=>URL.revokeObjectURL(i.preview))},[])
 const filteredGames=useMemo(()=>{const dayMap:{[K in Exclude<DayFilter,'all'>]:string}={yesterday:localDateKey(-1),today:localDateKey(0),tomorrow:localDateKey(1)},q=gameSearch.trim().toLowerCase();return games.filter(g=>{if(dayFilter!=='all'&&g.game_date!==dayMap[dayFilter])return false;if(gameSport&&g.sport_id!==gameSport)return false;if(gameSchool&&g.home_school_id!==gameSchool&&g.away_school_id!==gameSchool)return false;if(q&&!`${g.home_name} ${g.away_name} ${g.sport_name}`.toLowerCase().includes(q))return false;return true}).slice(0,80)},[games,dayFilter,gameSearch,gameSport,gameSchool])
 function addFiles(list:FileList|File[]){setError('');const incoming=Array.from(list).filter(f=>f.type.startsWith('image/'));const allowed=incoming.filter(f=>f.size<=MAX_FILE_BYTES);if(allowed.length<incoming.length)setError('Images over 15 MB were skipped.');setItems(prev=>{const room=Math.max(0,MAX_BATCH-prev.length);if(allowed.length>room)setError(`You can upload up to ${MAX_BATCH} photos at a time.`);return[...prev,...allowed.slice(0,room).map(makeItem)]})}
 function removeItem(key:string){setItems(prev=>{const found=prev.find(i=>i.key===key);if(found)URL.revokeObjectURL(found.preview);return prev.filter(i=>i.key!==key)})}
 function handleGame(gameId:string){const game=games.find(g=>g.id===gameId);setSingleTags([]);setForm(prev=>({...prev,game_id:gameId,sport_id:game?.sport_id||prev.sport_id,school_id:game?.home_school_id||game?.away_school_id||prev.school_id}))}
 const set=(k:string,v:string)=>setForm(p=>({...p,[k]:v}))
 async function uploadOne(item:BatchItem,tags:string[]){setItems(p=>p.map(i=>i.key===item.key?{...i,status:'uploading',error:undefined}:i));try{const game=games.find(g=>g.id===form.game_id);const teamId=game&&form.school_id===game.home_school_id?game.home_team_id:game&&form.school_id===game.away_school_id?game.away_team_id:'';const body=new FormData();body.set('file',item.file);body.set('submitter_name',form.submitter_name);body.set('submitter_email',form.submitter_email);body.set('photographer_credit_name',form.photographer_credit_name);body.set('school_id',form.school_id);body.set('team_id',teamId||'');body.set('game_id',form.game_id);body.set('sport_id',form.sport_id);body.set('caption',form.caption);body.set('permission_confirmed',String(permission));body.set('athlete_ids',tags.join(','));const r=await fetch('/api/photos/upload',{method:'POST',body});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Upload failed');setItems(p=>p.map(i=>i.key===item.key?{...i,status:'uploaded',photoId:d.id}:i));return true}catch(e:any){setItems(p=>p.map(i=>i.key===item.key?{...i,status:'failed',error:e?.message||'Upload failed'}:i));return false}}
 async function submit(e:React.FormEvent){e.preventDefault();const targets=items.filter(i=>i.status==='ready'||i.status==='failed');if(!targets.length||!permission||!form.photographer_credit_name){setError('Choose at least one photo, enter photographer credit, and confirm permission.');return}setLoading(true);setError('');setMessage('');setProgress({done:0,total:targets.length});let success=0;for(let i=0;i<targets.length;i++){if(await uploadOne(targets[i],targets.length===1?singleTags:[]))success++;setProgress({done:i+1,total:targets.length})}setLoading(false);setMessage(`${success} photo${success===1?'':'s'} submitted${success<targets.length?`; ${targets.length-success} failed and can be retried.`:'.'}`)}
 function reset(){items.forEach(i=>URL.revokeObjectURL(i.preview));setItems([]);setSingleTags([]);setProgress({done:0,total:0});setMessage('');setError('');setPermission(false)}
 if(uploaded.length&&uploaded.length===items.length&&items.length===1)return <div className="card p-8 text-center space-y-4"><div className="text-5xl">📷</div><h2 className="text-xl font-bold" style={{fontFamily:'var(--font-display)'}}>Photo Submitted!</h2><p className="text-sm text-slate-400">Your photo is in the review queue. Once approved, it can appear throughout Section X Scoreboard.</p><button onClick={reset} className="btn-primary px-5 py-3">Submit Another Photo</button></div>
 return <form onSubmit={submit} className="card p-4 sm:p-6 space-y-5">
  {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">{error}</div>}{message&&<div className="rounded-lg border border-blue-500/30 bg-blue-500/10 px-4 py-3 text-sm text-blue-200">{message}</div>}
  <div><div className="flex items-center justify-between mb-2"><label className="label mb-0">Photos *</label>{items.length>0&&<button type="button" onClick={reset} className="text-xs text-slate-400 hover:text-white">Clear all</button>}</div><div onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();setDragging(false)}} onDrop={e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files)}} onClick={()=>fileRef.current?.click()} className={`rounded-xl border-2 border-dashed p-5 text-center cursor-pointer transition-colors ${dragging?'border-blue-400 bg-blue-500/10':'border-white/15 hover:border-blue-500/40'}`}><div className="text-3xl mb-2">📸</div><p className="text-sm font-semibold text-white">Choose up to {MAX_BATCH} photos</p><p className="text-xs mt-1 text-slate-500">JPG, PNG, WEBP, HEIC · 15 MB max each</p><input ref={fileRef} type="file" accept="image/*" multiple className="hidden" onChange={e=>{if(e.target.files)addFiles(e.target.files);e.currentTarget.value=''}}/></div>{items.length>0&&<div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3">{items.map(i=><div key={i.key} className="relative rounded-lg border border-white/10 overflow-hidden bg-black/20"><img src={i.preview} alt="Selected" className="w-full aspect-square object-cover"/><div className="absolute inset-x-0 bottom-0 bg-black/70 px-2 py-1 text-[10px] flex justify-between"><span>{i.status}</span>{!loading&&i.status!=='uploaded'&&<button type="button" onClick={e=>{e.stopPropagation();removeItem(i.key)}}>Remove</button>}</div>{i.error&&<div className="absolute top-1 left-1 right-1 bg-red-950/90 text-[9px] p-1">{i.error}</div>}</div>)}</div>}</div>
  <div><div className="flex items-center justify-between mb-2"><label className="label mb-0">Which game?</label>{form.game_id&&<button type="button" onClick={()=>handleGame('')} className="text-xs text-slate-400">Clear</button>}</div>{selectedGame?<div className="rounded-xl border border-blue-500/30 bg-blue-500/10 p-4"><div className="text-sm font-bold text-white">{selectedGame.away_name} at {selectedGame.home_name}</div><div className="text-xs text-slate-400 mt-1">{selectedGame.sport_name} · {dateLabel(selectedGame.game_date)} · {timeLabel(selectedGame.game_time)}</div></div>:<><div className="grid grid-cols-4 gap-1.5 mb-3">{(['yesterday','today','tomorrow','all'] as DayFilter[]).map(day=><button key={day} type="button" onClick={()=>setDayFilter(day)} className={`rounded-lg px-2 py-2 text-[11px] font-bold capitalize border ${dayFilter===day?'bg-blue-600 border-blue-500 text-white':'bg-white/[0.03] border-white/10 text-slate-400'}`}>{day==='all'?'Search':day}</button>)}</div><div className="grid sm:grid-cols-3 gap-2 mb-3"><input className="input" value={gameSearch} onChange={e=>{setGameSearch(e.target.value);if(e.target.value)setDayFilter('all')}} placeholder="Search matchup..."/><select className="input" value={gameSport} onChange={e=>{setGameSport(e.target.value);if(e.target.value)setDayFilter('all')}}><option value="">All sports</option>{sports.map(s=><option key={s.id} value={s.id}>{s.sport_name}</option>)}</select><select className="input" value={gameSchool} onChange={e=>{setGameSchool(e.target.value);if(e.target.value)setDayFilter('all')}}><option value="">All schools</option>{schools.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></div><div className="rounded-xl border border-white/10 overflow-hidden max-h-72 overflow-y-auto">{filteredGames.length?filteredGames.map(g=><button key={g.id} type="button" onClick={()=>handleGame(g.id)} className="w-full text-left p-3 border-b border-white/5 hover:bg-white/[0.04]"><div className="text-sm font-semibold text-white">{g.away_name} at {g.home_name}</div><div className="text-xs text-slate-500">{g.sport_name} · {dateLabel(g.game_date)} · {timeLabel(g.game_time)}</div></button>):<div className="p-4 text-sm text-slate-500">No matching games.</div>}</div></>}</div>
  <div className="grid sm:grid-cols-2 gap-3"><label className="label">School<select className="input w-full mt-1" value={form.school_id} onChange={e=>set('school_id',e.target.value)}><option value="">Choose school</option>{schools.map(s=><option key={s.id} value={s.id}>{s.school_name}</option>)}</select></label><label className="label">Sport<select className="input w-full mt-1" value={form.sport_id} onChange={e=>set('sport_id',e.target.value)}><option value="">Choose sport</option>{sports.map(s=><option key={s.id} value={s.id}>{s.sport_name}</option>)}</select></label></div>
  <div className="grid sm:grid-cols-2 gap-3"><label className="label">Photographer credit *<input className="input w-full mt-1" required value={form.photographer_credit_name} onChange={e=>set('photographer_credit_name',e.target.value)} placeholder="Name shown with photo"/></label><label className="label">Your email<input type="email" className="input w-full mt-1" value={form.submitter_email} onChange={e=>set('submitter_email',e.target.value)} placeholder="Optional"/></label></div>
  <label className="label block">Your name<input className="input w-full mt-1" value={form.submitter_name} onChange={e=>set('submitter_name',e.target.value)} placeholder="Optional"/></label><label className="label block">Caption<textarea className="input w-full mt-1 min-h-[90px]" value={form.caption} onChange={e=>set('caption',e.target.value)} placeholder="Optional caption"/></label>
  {items.length===1&&form.game_id&&<PhotoAthleteSuggestor gameId={form.game_id} selected={singleTags} onChange={setSingleTags}/>} 
  <label className="flex items-start gap-3 text-sm text-slate-300"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)} className="mt-1"/><span>I took these photos or have permission to submit them to Section X Scoreboard.</span></label>
  {loading&&<div className="text-sm text-blue-300">Uploading {progress.done} of {progress.total}...</div>}
  <button disabled={loading||!items.length||!permission} className="btn-primary w-full py-3">{loading?'Uploading...':'Submit Photo'+(items.length===1?'':'s')}</button>
 </form>
}
