'use client'
import { useState } from 'react'

export default function FanZoneAdminClient({plays,snapshots}:{plays:any[];snapshots:any[]}){
 const [items,setItems]=useState(plays)
 async function setStatus(id:string,status:string){const r=await fetch('/api/admin/fan-zone/top-plays',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json();if(d.ok)setItems(p=>p.map(x=>x.id===id?{...x,status}:x))}
 return <div className="space-y-8">
  <section><div className="flex items-center justify-between mb-3"><h2 className="font-black text-white">Top 5 Play Inbox</h2><span className="text-xs text-slate-500">{items.filter(x=>x.status==='pending').length} pending</span></div><div className="space-y-3">{items.length?items.map(p=><div key={p.id} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="flex flex-col md:flex-row gap-4 md:items-start md:justify-between"><div><div className="text-xs text-blue-300">{p.sport?.gender} {p.sport?.sport_name} · {p.school?.school_name||'School not selected'} · {p.game_date||'Date not supplied'}</div><div className="text-lg font-black text-white mt-1">{p.athlete_name}</div><div className="text-sm text-slate-300 mt-2">{p.play_description}</div>{p.why_top_five&&<div className="text-xs text-slate-500 mt-2">Why Top 5: {p.why_top_five}</div>}<div className="text-[11px] text-slate-600 mt-2">{p.opponent?'vs '+p.opponent+' · ':''}submitted {new Date(p.created_at).toLocaleString()}</div></div><div className="flex gap-2 flex-wrap"><button onClick={()=>setStatus(p.id,'featured')} className="px-3 py-2 rounded-lg text-xs font-black bg-yellow-300 text-black">Top 5</button><button onClick={()=>setStatus(p.id,'approved')} className="px-3 py-2 rounded-lg text-xs font-bold bg-emerald-500/15 text-emerald-300">Approve</button><button onClick={()=>setStatus(p.id,'rejected')} className="px-3 py-2 rounded-lg text-xs font-bold bg-red-500/10 text-red-300">Reject</button></div></div><div className="mt-2 text-[10px] uppercase tracking-widest text-slate-500">Status: {p.status}</div></div>):<div className="text-sm text-slate-500">No play nominations yet.</div>}</div></section>
  <section><h2 className="font-black text-white mb-3">Fan Power Rankings</h2><div className="grid md:grid-cols-2 gap-3">{snapshots.length?snapshots.map(s=><div key={s.id} className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="text-xs text-yellow-300">{s.sport?.gender} {s.sport?.sport_name} · {s.group_type} {s.group_value}</div><div className="text-2xl font-black text-white mt-1">{s.ballot_count} ballots</div><div className="mt-3 space-y-1">{(Array.isArray(s.results)?s.results:[]).slice(0,5).map((r:any,i:number)=><div key={r.teamId} className="flex justify-between text-sm"><span className="text-slate-300">{i+1}. {r.teamName}</span><b className="text-white">{r.points}</b></div>)}</div></div>):<div className="text-sm text-slate-500">No fan ballots yet.</div>}</div></section>
 </div>
}
