'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { adminDb } from '@/lib/adminDb'

function one(v:any){return Array.isArray(v)?v[0]:v}
function gameLabel(g:any){const home=one(g.home_team)?.team_name||'Home',away=one(g.away_team)?.team_name||'Away',s=one(g.sport);const sport=s?(s.gender&&s.gender!=='Both'?`${s.gender} ${s.sport_name}`:s.sport_name):'Sport';return `${g.game_date} · ${sport} · ${away} at ${home}`}

export default function ContributorAdmin({profiles,games,pendingUpdates,assignments}:{profiles:any[];games:any[];pendingUpdates:any[];assignments:any[]}){
  const router=useRouter(); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [msg,setMsg]=useState(''); const [assignGame,setAssignGame]=useState<Record<string,string>>({}); const [assignRole,setAssignRole]=useState<Record<string,string>>({})
  async function patch(id:string,data:any){setBusy(id);setError('');setMsg('');try{await adminDb.update('contributor_profiles',{...data,updated_at:new Date().toISOString()},{id});setMsg('Contributor updated.');router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function assign(profile:any){const gameId=assignGame[profile.id];if(!gameId)return;setBusy(`assign-${profile.id}`);setError('');try{await adminDb.upsert('contributor_game_assignments',{contributor_id:profile.id,game_id:gameId,assignment_role:assignRole[profile.id]||'coverage',active:true},'contributor_id,game_id,assignment_role');setMsg(`Game assigned to ${profile.public_credit_name||profile.display_name}.`);router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function unassign(a:any){setBusy(a.id);try{await adminDb.update('contributor_game_assignments',{active:false},{id:a.id});router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function review(updateId:string,action:'approve'|'reject'){setBusy(updateId);setError('');setMsg('');try{const r=await fetch('/api/admin/contributors/score-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({updateId,action})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Review failed');setMsg(`Score report ${action==='approve'?'published':'rejected'}.`);router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  return <div className="p-4 max-w-7xl space-y-5">
    <div><div className="text-xs uppercase tracking-widest text-blue-300 font-black">Community Operations</div><h1 className="text-3xl font-black text-white mt-1" style={{fontFamily:'var(--font-display)'}}>Contributor Control Room</h1><p className="text-sm text-slate-500 mt-1">Approve people, grant only the permissions they earned, assign games, and audit every score report.</p></div>
    {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>}{msg&&<div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-emerald-300 text-sm">{msg}</div>}
    <div className="grid md:grid-cols-4 gap-3"><div className="card p-4"><div className="text-2xl font-black text-white">{profiles.length}</div><div className="text-xs text-slate-500">Contributor accounts</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{profiles.filter(p=>p.status==='pending').length}</div><div className="text-xs text-slate-500">Applications pending</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{profiles.filter(p=>p.can_live_score&&p.status==='approved').length}</div><div className="text-xs text-slate-500">Live scorers</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{pendingUpdates.length}</div><div className="text-xs text-slate-500">Score reports to review</div></div></div>
    <section className="space-y-3"><h2 className="text-xl font-black text-white">Contributors</h2>{profiles.length?profiles.map(p=>{const school=one(p.school);const mine=assignments.filter(a=>a.contributor_id===p.id);return <div key={p.id} className="card p-4 space-y-4"><div className="flex flex-col md:flex-row md:items-start justify-between gap-3"><div><div className="flex items-center gap-2 flex-wrap"><b className="text-lg text-white">{p.public_credit_name||p.display_name}</b><span className={`text-xs font-black uppercase px-2 py-1 rounded-full ${p.status==='approved'?'bg-emerald-500/10 text-emerald-300':p.status==='pending'?'bg-amber-500/10 text-amber-300':'bg-red-500/10 text-red-300'}`}>{p.status}</span><span className="text-xs px-2 py-1 rounded-full bg-white/5 text-slate-400">{p.trust_level}</span></div><div className="text-xs text-slate-500 mt-1">{p.email||'No email'}{school?` · ${school.school_name}`:''} · {p.submissions_count||0} submissions · {p.verified_count||0} verified</div>{p.bio&&<p className="text-sm text-slate-400 mt-2">{p.bio}</p>}</div><div className="flex gap-2 flex-wrap">{p.status!=='approved'&&<button disabled={busy===p.id} onClick={()=>patch(p.id,{status:'approved',approved_at:new Date().toISOString(),approved_by:'admin'})} className="admin-action-btn">Approve</button>}{p.status==='approved'&&<button disabled={busy===p.id} onClick={()=>patch(p.id,{status:'suspended'})} className="admin-action-btn">Suspend</button>}{p.status==='suspended'&&<button onClick={()=>patch(p.id,{status:'approved'})} className="admin-action-btn">Restore</button>}</div></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-2 text-sm">{[['can_submit_photos','Photos'],['can_tag_photos','Tag Athletes'],['can_submit_scores','Report Scores'],['can_live_score','Live Score'],['can_publish_photos','Publish Photos']].map(([key,label])=><label key={key} className="rounded-lg border border-white/10 bg-black/20 p-3 flex items-center justify-between gap-2"><span className="text-slate-300">{label}</span><input type="checkbox" checked={Boolean(p[key])} onChange={e=>patch(p.id,{[key]:e.target.checked})}/></label>)}</div>
      <div className="flex flex-col lg:flex-row gap-2"><select className="input lg:w-44" value={p.trust_level} onChange={e=>patch(p.id,{trust_level:e.target.value})}><option value="new">New</option><option value="trusted">Trusted</option><option value="veteran">Veteran</option></select><select className="input flex-1" value={assignGame[p.id]||''} onChange={e=>setAssignGame(a=>({...a,[p.id]:e.target.value}))}><option value="">Assign an upcoming game…</option>{games.map(g=><option key={g.id} value={g.id}>{gameLabel(g)}</option>)}</select><select className="input lg:w-44" value={assignRole[p.id]||'coverage'} onChange={e=>setAssignRole(a=>({...a,[p.id]:e.target.value}))}><option value="coverage">Coverage</option><option value="score-reporter">Score Reporter</option><option value="photographer">Photographer</option></select><button disabled={!assignGame[p.id]||busy===`assign-${p.id}`} onClick={()=>assign(p)} className="admin-action-btn justify-center">Assign Game</button></div>
      {mine.length>0&&<div className="flex flex-wrap gap-2">{mine.map(a=>{const g=games.find(x=>x.id===a.game_id);return <button key={a.id} onClick={()=>unassign(a)} title="Click to remove assignment" className="text-xs rounded-full border border-white/10 px-3 py-1 text-slate-400 hover:text-red-300">{g?gameLabel(g):a.game_id} · {a.assignment_role} ×</button>})}</div>}
    </div>}):<div className="card p-6 text-slate-500">No contributor applications yet.</div>}</section>
    <section className="space-y-3"><h2 className="text-xl font-black text-white">Pending Score Reports</h2>{pendingUpdates.length?pendingUpdates.map(u=>{const c=one(u.contributor),g=one(u.game);return <div key={u.id} className="card p-4 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-white font-black">{one(g?.away_team)?.team_name||'Away'} {u.away_score} at {one(g?.home_team)?.team_name||'Home'} {u.home_score}</div><div className="text-xs text-slate-500 mt-1">{g?.game_date} · {c?.public_credit_name||c?.display_name} · {u.game_status||'Score update'}</div>{u.note&&<div className="text-sm text-slate-400 mt-2">{u.note}</div>}</div><div className="flex gap-2"><button disabled={busy===u.id} onClick={()=>review(u.id,'approve')} className="admin-action-btn">Approve & Publish</button><button disabled={busy===u.id} onClick={()=>review(u.id,'reject')} className="admin-action-btn">Reject</button></div></div>}):<div className="card p-6 text-emerald-300 text-sm">No contributor score reports waiting.</div>}</section>
  </div>
}
