'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

function one(v:any){return Array.isArray(v)?v[0]:v}
function gameLabel(g:any){const home=one(g.home_team)?.team_name||'Home',away=one(g.away_team)?.team_name||'Away',s=one(g.sport);const sport=s?(s.gender&&s.gender!=='Both'?`${s.gender} ${s.sport_name}`:s.sport_name):'Sport';return `${g.game_date} · ${sport} · ${away} at ${home}`}
async function adminAction(body:any){const r=await fetch('/api/admin/contributors',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Contributor action failed.');return j}
function stageLabel(stage:string){if(stage==='claim-required')return 'Claim required';if(stage==='unverified')return 'Email not verified';if(stage==='verified-incomplete')return 'Application incomplete';if(stage==='pending')return 'Pending approval';if(stage==='approved')return 'Approved';if(stage==='suspended')return 'Suspended';return stage}
function stageClass(stage:string){if(stage==='approved')return 'bg-emerald-500/10 text-emerald-300';if(stage==='pending'||stage==='verified-incomplete')return 'bg-amber-500/10 text-amber-300';if(stage==='claim-required')return 'bg-purple-500/10 text-purple-300';if(stage==='unverified')return 'bg-slate-500/10 text-slate-300';return 'bg-red-500/10 text-red-300'}

export default function ContributorAdmin({accounts,profiles,games,pendingUpdates,assignments}:{accounts:any[];profiles:any[];games:any[];pendingUpdates:any[];assignments:any[]}){
  const router=useRouter(); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [msg,setMsg]=useState(''); const [assignGame,setAssignGame]=useState<Record<string,string>>({}); const [assignRole,setAssignRole]=useState<Record<string,string>>({})
  async function patch(id:string,data:any){setBusy(id);setError('');setMsg('');try{await adminAction({action:'profile-update',id,patch:data});setMsg('Contributor updated.');router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function assign(profile:any){const gameId=assignGame[profile.id];if(!gameId)return;setBusy(`assign-${profile.id}`);setError('');try{await adminAction({action:'assign',contributorId:profile.id,gameId,role:assignRole[profile.id]||'coverage'});setMsg(`Game assigned to ${profile.public_credit_name||profile.display_name}.`);router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function unassign(a:any){setBusy(a.id);try{await adminAction({action:'unassign',id:a.id});router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  async function review(updateId:string,action:'approve'|'reject'){setBusy(updateId);setError('');setMsg('');try{const r=await fetch('/api/admin/contributors/score-review',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({updateId,action})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Review failed');setMsg(`Score report ${action==='approve'?'published':'rejected'}.`);router.refresh()}catch(e:any){setError(e.message)}finally{setBusy('')}}
  const unverified=accounts.filter(a=>a.stage==='unverified').length,incomplete=accounts.filter(a=>a.stage==='verified-incomplete').length,pending=accounts.filter(a=>a.stage==='pending').length,approved=accounts.filter(a=>a.stage==='approved').length,claimRequired=accounts.filter(a=>a.stage==='claim-required').length
  return <div className="p-4 max-w-7xl space-y-5">
    <div><div className="text-xs uppercase tracking-widest text-blue-300 font-black">Community Operations</div><h1 className="text-3xl font-black text-white mt-1" style={{fontFamily:'var(--font-display)'}}>Contributor Control Room</h1><p className="text-sm text-slate-500 mt-1">See every signup from registration through approval, then manage permissions, assignments, and score reports.</p></div>
    {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>}{msg&&<div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-emerald-300 text-sm">{msg}</div>}
    <div className="grid sm:grid-cols-2 lg:grid-cols-6 gap-3"><div className="card p-4"><div className="text-2xl font-black text-white">{accounts.length}</div><div className="text-xs text-slate-500">Total signups</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{claimRequired}</div><div className="text-xs text-slate-500">Claim required</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{unverified}</div><div className="text-xs text-slate-500">Email not verified</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{incomplete}</div><div className="text-xs text-slate-500">Incomplete applications</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{pending}</div><div className="text-xs text-slate-500">Pending approval</div></div><div className="card p-4"><div className="text-2xl font-black text-white">{approved}</div><div className="text-xs text-slate-500">Approved</div></div></div>
    <section className="space-y-3"><div><h2 className="text-xl font-black text-white">Registration Pipeline</h2><p className="text-xs text-slate-500 mt-1">Every contributor account appears here immediately after signup. Recovered Supabase registrations are marked claim required until the owner verifies the email and sets a new password.</p></div>{accounts.length?<div className="card overflow-hidden"><div className="divide-y divide-white/5">{accounts.map(a=><div key={a.id} className="p-4 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><div className="font-bold text-white">{a.public_credit_name||a.display_name||a.email}</div><div className="text-xs text-slate-500 mt-1">{a.email} · Signed up {a.created_at?new Date(a.created_at).toLocaleString():'Unknown time'}</div></div><span className={`text-xs font-black uppercase px-2 py-1 rounded-full w-fit ${stageClass(a.stage)}`}>{stageLabel(a.stage)}</span></div>)}</div></div>:<div className="card p-6 text-slate-500">No contributor signups yet.</div>}</section>
    <section className="space-y-3"><h2 className="text-xl font-black text-white">Submitted Contributors</h2>{profiles.length?profiles.map(p=>{const school=one(p.school);const mine=assignments.filter(a=>a.contributor_id===p.id);return <div key={p.id} className="card p-4 space-y-4"><div className="flex flex-col md:flex-row md:items-start justify-between gap-3"><div><div className="flex items-center gap-2 flex-wrap"><b className="text-lg text-white">{p.public_credit_name||p.display_name}</b><span className={`text-xs font-black uppercase px-2 py-1 rounded-full ${p.status==='approved'?'bg-emerald-500/10 text-emerald-300':p.status==='pending'?'bg-amber-500/10 text-amber-300':'bg-red-500/10 text-red-300'}`}>{p.status}</span><span className="text-xs px-2 py-1 rounded-full bg-white/5 text-slate-400">{p.trust_level}</span></div><div className="text-xs text-slate-500 mt-1">{p.email||'No email'}{school?` · ${school.school_name}`:''} · {p.submissions_count||0} submissions · {p.verified_count||0} verified</div>{p.bio&&<p className="text-sm text-slate-400 mt-2">{p.bio}</p>}</div><div className="flex gap-2 flex-wrap">{p.status!=='approved'&&<button disabled={busy===p.id} onClick={()=>patch(p.id,{status:'approved',approved_at:new Date().toISOString(),approved_by:'admin'})} className="admin-action-btn">Approve</button>}{p.status==='approved'&&<button disabled={busy===p.id} onClick={()=>patch(p.id,{status:'suspended'})} className="admin-action-btn">Suspend</button>}{p.status==='suspended'&&<button onClick={()=>patch(p.id,{status:'approved'})} className="admin-action-btn">Restore</button>}</div></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-2 text-sm">{[['can_submit_photos','Photos'],['can_tag_photos','Tag Athletes'],['can_submit_scores','Report Scores'],['can_live_score','Live Score'],['can_publish_photos','Publish Photos']].map(([key,label])=><label key={key} className="rounded-lg border border-white/10 bg-black/20 p-3 flex items-center justify-between gap-2"><span className="text-slate-300">{label}</span><input type="checkbox" checked={Boolean(p[key])} onChange={e=>patch(p.id,{[key]:e.target.checked})}/></label>)}</div>
      <div className="flex flex-col lg:flex-row gap-2"><select className="input lg:w-44" value={p.trust_level} onChange={e=>patch(p.id,{trust_level:e.target.value})}><option value="new">New</option><option value="trusted">Trusted</option><option value="veteran">Veteran</option></select><select className="input flex-1" value={assignGame[p.id]||''} onChange={e=>setAssignGame(a=>({...a,[p.id]:e.target.value}))}><option value="">Assign an upcoming game…</option>{games.map(g=><option key={g.id} value={g.id}>{gameLabel(g)}</option>)}</select><select className="input lg:w-44" value={assignRole[p.id]||'coverage'} onChange={e=>setAssignRole(a=>({...a,[p.id]:e.target.value}))}><option value="coverage">Coverage</option><option value="score-reporter">Score Reporter</option><option value="photographer">Photographer</option></select><button disabled={!assignGame[p.id]||busy===`assign-${p.id}`} onClick={()=>assign(p)} className="admin-action-btn justify-center">Assign Game</button></div>
      {mine.length>0&&<div className="flex flex-wrap gap-2">{mine.map(a=>{const g=games.find(x=>x.id===a.game_id);return <button key={a.id} onClick={()=>unassign(a)} title="Click to remove assignment" className="text-xs rounded-full border border-white/10 px-3 py-1 text-slate-400 hover:text-red-300">{g?gameLabel(g):a.game_id} · {a.assignment_role} ×</button>})}</div>}
    </div>}):<div className="card p-6 text-slate-500">No submitted contributor applications yet.</div>}</section>
    <section className="space-y-3"><h2 className="text-xl font-black text-white">Pending Score Reports</h2>{pendingUpdates.length?pendingUpdates.map(u=>{const c=one(u.contributor),g=one(u.game);return <div key={u.id} className="card p-4 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-white font-black">{one(g?.away_team)?.team_name||'Away'} {u.away_score} at {one(g?.home_team)?.team_name||'Home'} {u.home_score}</div><div className="text-xs text-slate-500 mt-1">{g?.game_date} · {c?.public_credit_name||c?.display_name} · {u.game_status||'Score update'}</div>{u.note&&<div className="text-sm text-slate-400 mt-2">{u.note}</div>}</div><div className="flex gap-2"><button disabled={busy===u.id} onClick={()=>review(u.id,'approve')} className="admin-action-btn">Approve & Publish</button><button disabled={busy===u.id} onClick={()=>review(u.id,'reject')} className="admin-action-btn">Reject</button></div></div>}):<div className="card p-6 text-emerald-300 text-sm">No contributor score reports waiting.</div>}</section>
  </div>
}
