'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { adminDb } from '@/lib/adminDb'

function one(v:any){return Array.isArray(v)?v[0]:v}
function gameLabel(g:any){const home=one(g.home_team)?.team_name||'Home',away=one(g.away_team)?.team_name||'Away',s=one(g.sport);const sport=s?(s.gender&&s.gender!=='Both'?`${s.gender} ${s.sport_name}`:s.sport_name):'Sport';return `${g.game_date} · ${sport} · ${away} at ${home}`}
function roleLabel(v:string){return String(v||'coverage').replace(/-/g,' ')}

export default function CoverageBoard({profiles,games,requests}:{profiles:any[];games:any[];requests:any[]}){
  const router=useRouter(),[gameId,setGameId]=useState(''),[role,setRole]=useState('photographer'),[notes,setNotes]=useState(''),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('')
  async function create(){if(!gameId)return;setBusy('create');setMessage('');setError('');try{await adminDb.insert('contributor_coverage_requests',{game_id:gameId,coverage_role:role,status:'open',notes:notes.trim()||null,requested_by:'admin'});setGameId('');setNotes('');setMessage('Coverage opportunity opened.');router.refresh()}catch(e:any){setError(e.message||'Could not open coverage request.')}finally{setBusy('')}}
  async function cancel(id:string){setBusy(id);setMessage('');setError('');try{await adminDb.update('contributor_coverage_requests',{status:'cancelled',closed_at:new Date().toISOString(),updated_at:new Date().toISOString()},{id});setMessage('Coverage request closed.');router.refresh()}catch(e:any){setError(e.message||'Could not close coverage request.')}finally{setBusy('')}}
  return <section className="space-y-3">
    <div><div className="text-xs uppercase tracking-widest text-amber-300 font-black">Coverage Network</div><h2 className="text-xl font-black text-white mt-1">Coverage Board</h2><p className="text-sm text-slate-500 mt-1">Open a game for photographers, score reporters, or trusted live scorers. Approved contributors can claim matching opportunities from their dashboard.</p></div>
    {error&&<div className="rounded-lg border border-red-500/30 bg-red-500/10 p-3 text-red-300 text-sm">{error}</div>}{message&&<div className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 p-3 text-emerald-300 text-sm">{message}</div>}
    <div className="card p-4 grid lg:grid-cols-[1fr_180px_1fr_auto] gap-2 items-end"><label className="text-xs text-slate-500">Game<select className="input mt-1 w-full" value={gameId} onChange={e=>setGameId(e.target.value)}><option value="">Choose an upcoming game…</option>{games.map(g=><option key={g.id} value={g.id}>{gameLabel(g)}</option>)}</select></label><label className="text-xs text-slate-500">Need<select className="input mt-1 w-full" value={role} onChange={e=>setRole(e.target.value)}><option value="photographer">Photographer</option><option value="score-reporter">Score Reporter</option><option value="live-score">Live Scorer</option><option value="coverage">General Coverage</option></select></label><label className="text-xs text-slate-500">Notes<input className="input mt-1 w-full" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional: senior night, rivalry, tournament…" maxLength={300}/></label><button disabled={!gameId||busy==='create'} onClick={create} className="btn-primary px-4 py-3">{busy==='create'?'Opening…':'Request Coverage'}</button></div>
    <div className="grid lg:grid-cols-2 gap-3">{requests.length?requests.map(r=>{const g=games.find(x=>x.id===r.game_id),claimed=profiles.find(p=>p.id===r.claimed_by);return <div key={r.id} className="card p-4 flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 flex-wrap"><b className="text-white">{g?gameLabel(g):'Game'}</b><span className={`text-[10px] uppercase font-black px-2 py-1 rounded-full ${r.status==='claimed'?'bg-emerald-500/10 text-emerald-300':'bg-amber-500/10 text-amber-300'}`}>{r.status}</span></div><div className="text-xs text-blue-300 mt-1 capitalize">{roleLabel(r.coverage_role)}</div>{claimed&&<div className="text-xs text-emerald-300 mt-1">Claimed by {claimed.public_credit_name||claimed.display_name}</div>}{r.notes&&<div className="text-sm text-slate-400 mt-2">{r.notes}</div>}</div><button disabled={busy===r.id} onClick={()=>cancel(r.id)} className="admin-action-btn text-xs">Close</button></div>}):<div className="card p-5 text-sm text-slate-500 lg:col-span-2">No open coverage requests. Pick a game above whenever you want the community coverage crew involved.</div>}</div>
  </section>
}
